### ISSUE TITLE
improvement: validate empty cmpTags.

### ISSUE THREAD

**Issue by natoehv** [ionic-team/stencil#4391] opened 2023-05-16 12:36 UTC
if the cmpTags is empty, we should skip this part of the code

https://github.com/ionic-team/stencil/blob/bf466d7979c972ee47956cc21103e36add851f15/src/runtime/bootstrap-lazy.ts#LL169C33-L169C40

context: Im using an external library (based on stencil), but when I run the test, this part is executed twice, therefore the first time all go well, but the second time, it show the error below:

<img width="435" alt="image" src="https://github.com/ionic-team/stencil/assets/6584680/c796042b-581a-4136-9aeb-a9ab6d299258">

```ts
visibilityStyle.innerHTML = cmpTags + HYDRATED_CSS; //  '{visibility:hidden}.hydrated{visibility:inherit}'
```

**Comment by rwaskiewicz** [comment] 2023-05-16 12:51
Hey @natoehv 👋 

Can you do me a favor an provide a minimal reproduction case for the team and I to take a look at? This will help us understand the problem a little bit better, including:
- the library you're using (and the version of Stencil they're using)
- what your test looks like and how it works
- other libraries involved and how they're configured

Thanks!

**Comment by rwaskiewicz** [comment] 2023-05-18 19:55
Possibly related: https://github.com/ionic-team/stencil/pull/3771

**Comment by rwaskiewicz** [comment] 2023-11-03 20:38
Closing as a duplicate of #3771

**Closed by rwaskiewicz** 2023-11-03 20:38 UTC
Labels: ionitron: needs reproduction
