### ISSUE TITLE
CustomElementsDefineOptions is missing transformTagName

### ISSUE THREAD

**Issue by Snapu** [ionic-team/stencil#2847] opened 2021-03-09 10:46 UTC
**Stencil version:**

```
 @stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

error:
```
Argument of type '{ transformTagName: (tagName: any) => string; }' is not assignable to parameter of type 'CustomElementsDefineOptions'.
  Object literal may only specify known properties, and 'transformTagName' does not exist in type 'CustomElementsDefineOptions'.
 ```
 
**Expected behavior:**

No type errors

**Steps to reproduce:**

1. set config:
```
config.extras.tagNameTransform: true
```
2. call defineCustomElements:
```
defineCustomElements(window, { transformTagName: tagName => `YOUR_APP_ID-${tagName}` });
```
3. observe error

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by alicewriteswrongs** [comment] 2023-01-18 16:13
Hi @Snapu, first off I want to apologize that no one from the Stencil team got to this for so long. Sorry about that! We are working to be more responsive to community issues, part of which is staying on top of _new_ issues, and part of which is following up on _old_ ones.

In any case, I've been able to confirm that this is an issue in the latest version of Stencil. 

In the course of doing so, I put together a quick reproduction case, here: https://github.com/alicewriteswrongs/stencil-transform-tag-name-repro

I'm going to label this issue so we ingest it into our backlog and can prioritize it.

Thanks for reporting, and sorry again for the wait!

**Comment by oscargm** [comment] 2023-05-09 15:32
Hi here,

Is there a plan to have this fixed?
Do you know which is the latest working version?
Would you have some advice on where to start looking into it to try to provide a fix?

It would be quite important for us and I could dedicate some time

**Comment by pathi-yugandhar** [comment] 2023-07-16 00:57
`tagNameTransform` is also missing in the documentation. Please help to provide a fix for this.

**Comment by christian-bromann** [comment] 2024-06-24 19:07
> is also missing in the documentation. Please help to provide a fix for this.

documentation for this feature has been proposed in https://github.com/ionic-team/stencil-site/pull/1452/files

**Comment by christian-bromann** [comment] 2024-06-24 19:49
It seems that this feature doesn't fulfill the requirements anymore we have to current Stencil enhancements. If there is still interest in this we should tackle it from a new feature request since a lot has changed since the original issue was posted. Thank you!

**Closed by christian-bromann** 2024-06-24 19:49 UTC
Labels: Bug: Validated

**Comment by deleonio** [comment] 2024-11-16 03:31
Hi @christian-bromann,

that could be interesting for you: https://stackblitz.com/edit/vitejs-vite-sokywz?file=src%2FApp.tsx

We use the Tag-Name-Transform-Feature to prevent collisions in micro-frontend scenarios. That works for the web components, the stencil-adapters and our theming engine.

**Comment by christian-bromann** [comment] 2024-11-20 00:46
@deleonio very interesting! I currently have this tracked in #3269 and have this as prioritized item for our 2025 roadmap. I see this being in the same bucket as [feat: component versioning](https://github.com/ionic-team/stencil/issues/3138) and [Support for Scope Elements](https://github.com/ionic-team/stencil/issues/2957), would you agree?

**Comment by claire-cassan** [comment] 2025-03-05 14:30
Hi @christian-bromann ,
Like @deleonio , we also plan to use the Tag name transformation feature to control version collisions between microfrontend

**Comment by michaelrgalloway** [comment] 2025-03-08 00:00
@christian-bromann Thanks for making this a priority, you mentioned in your comment that this was prioritized for 2025, is still the plan?

**Comment by christian-bromann** [comment] 2025-03-08 00:32
That is correct!

**Comment by deleonio** [comment] 2025-03-08 07:36
Hi together, 

we had published own adapter npm packages for tag name transforming, becouse we could not merge our code back to stencil, right now.

If you need our feature take a look here: https://github.com/public-ui/stencil-ds-output-targets

**Comment by michaelrgalloway** [comment] 2025-03-08 11:56
Hi, Thanks for the link. It looks like this way changes the tag name for the current project only, which may solve some use cases but not ours. 

We have several higher complexity components, each their own Stencil project, but share a common design system library underneath. 

Our use case is as Component A uses design library version 1.2 and Component B uses design library 1.3. So it’s not the top level component that needs to change tag names,  it’s the underlying lower components that are used within that needs to be scoped to the components using them if need be.

We use the esm modules directly without any framework wrapper so we support all tech stacks.
