### ISSUE TITLE
SVG: Icon no longer load

### ISSUE THREAD

**Issue by dfraize** [ionic-team/stencil#446] opened 2018-01-24 18:33 UTC
**Stencil version:**

```
@stencil/core@0.1.5
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Any version of Stencil Compiler later that 0.1.5 does not load in the SVG file

**Expected behavior:**
When I reference a SVG definition file into my ICON component I am allow the name of the icon to be passed into the component to finish URL path to the correct SVG icon

**Steps to reproduce:**

**Related code:**

```tsx
<use xlinkHref={('../../assets/icons/symbol-defs.svg#' + this.icon)}></use>
```

**Other information:**

**Comment by bfmatei** [comment] 2018-01-24 19:36
You are not proceeding correctly. Adjust your code to this:
```tsx
<use xlinkHref={`/assets/icons/symbol-defs.svg#${this.icon}`}></use>
```

Whatever is in the assets folder, it will get copied over in the www folder. Referencing it like above triggers the browser request in order to fetch the symbol-defs.svg file.

**Comment by dfraize** [comment] 2018-01-24 21:58
I have updated my code to the suggested but still doesn't seem to be loading the proper file, in previous versions of the compiler I noticed the the .svg file would show in the network tab in chrome inspect now it no longer is showing.

`<svg class={classes} role={(this.role)} aria-hidden={(this.ariahidden)}>
    <use xlinkHref={`/assets/icons/symbol-defs.svg#${this.icon}`}></use>
</svg>`

**Comment by adamdbradley** [comment] 2018-01-25 00:34
Are the files copied over to `www/assets`? What does the dom actually look like in the inspector?

**Comment by bfmatei** [comment] 2018-01-25 08:42
@dfraize: Please have a look here: https://github.com/bfmatei/stencil-boilerplate/blob/master/src/components/shared/app-icon/app-icon.tsx as it is working perfectly.

**Comment by dfraize** [comment] 2018-01-25 12:28
I have attached some screen grabs, 1 shows the `www/root` folder which as the assets folder with the svg symbol-defs file, the other two are screen grabs of the chrome inspect. 1 shows the network panel which you can see has no .svg being loaded, the other is of the DOM and the component that I am working with, you will see that the `<use>` tag is getting the correct URL but there is no shadow dom happening like it was in previous versions

![screen shot 2018-01-25 at 7 22 33 am](https://user-images.githubusercontent.com/42154/35388334-5bef1c48-01a1-11e8-9436-ba37fb6bbe0b.png)
![screen shot 2018-01-25 at 7 22 58 am](https://user-images.githubusercontent.com/42154/35388335-5c09055e-01a1-11e8-877c-511ee0e60266.png)
![screen shot 2018-01-25 at 7 23 53 am](https://user-images.githubusercontent.com/42154/35388336-5c21319c-01a1-11e8-93f5-5e2ceb9bac78.png)

**Comment by jgw96** [comment] 2018-01-25 18:04
@dfraize if you point straight to a specific SVG (not using #) does this work?

**Comment by jgw96** [comment] 2018-01-25 18:05
Also, can you make sure your running `@stencil/core@0.2.2` please

**Comment by dfraize** [comment] 2018-01-25 18:15
I was on `@stencil/core@0.2.3` but I am back to `@stencil/core@0.2.2`

The below works directly on my page:
`<svg>
  <use xlinkHref="../../assets/icons/symbol-defs.svg#home" />
</svg>`

**Comment by dfraize** [comment] 2018-01-25 19:17
@jgw96 I was able to find the following:

This renders when server up on my html page
`<svg>
  <use xlinkHref={`/assets/icons/symbol-defs.svg#home`} />
</svg>`

The server is loading the svg file as I can see it in the browser, but when I use the actually component that I created it doesn't seem to load up the svg file.

**Comment by dfraize** [comment] 2018-01-25 19:34
@jgw96 
Looks like the issue was that I was providing a `title` element for accessibility

This works:
`<svg class={classes} role={(this.role)} aria-hidden={(this.ariahidden)}>
  <use xlinkHref={`/assets/icons/symbol-defs.svg#${this.icon}`} />
</svg>`

This does not work:
`<svg class={classes} role={(this.role)} aria-hidden={(this.ariahidden)}>
  <title>{this.icon}</title>
  <use xlinkHref={`/assets/icons/symbol-defs.svg#${this.icon}`} />
</svg>`

**Comment by jgw96** [comment] 2018-01-29 16:30
@dfraize interesting! So this sounds like https://github.com/ionic-team/stencil/issues/448. It sounds like it was maybe only rendering the `title` element but not the SVG. When you have a title element in the SVG, what does the dom look like if you inspect it in dev tools?

**Comment by jgw96** [comment] 2018-02-05 21:20
Closing this one for now as it has been a while since there was any activity. Also, it sounds like #448 is a duplicate of this issue. Thanks for using Stencil!

**Closed by jgw96** 2018-02-05 21:20 UTC
Labels: help wanted, needs reply

**Comment by Vijay-Barve** [comment] 2018-09-29 07:08
npm i rxjs@6 rxjs-compat@6 promise-polyfill --save

installing rxjs package worked for me :)
