### ISSUE TITLE
Stencil component consumed in Angular fails building.

### ISSUE THREAD

**Issue by dkundel** [ionic-team/stencil#512] opened 2018-02-09 11:49 UTC
**Stencil version:**

```
 @stencil/core@0.3.0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

I build a very basic component using Stencil and published it afterwards to `npm` and tried to consume it in an out of the box Angular application. I followed the steps described in the documentation.

It failed building due to `HTMLAttributes` not being defined in the `components.d.ts` file. 

The fix was to ad `/// <reference types="@stencil/core" />` to the top of the `components.d.ts` file.

**Expected behavior:**

It builds without manually editing the compiled output.

**Steps to reproduce:**

1. Clone [dkundel/webcomponents-by-example](/dkundel/webcomponents-by-example)
2. `cd angular-demo`
3. `npm install`
4. `npm start`

This will fail building. Afterwards open `angular-demo/node_modules/@dkundel/stencil-demo-components/dist/types/components.d.ts` and add to the top `/// <reference types="@stencil/core" />`, save the file and try `npm start` again. The project builds successfully.

**Related code:**
All related code is in [dkundel/webcomponents-by-example](/dkundel/webcomponents-by-example).

The code for the component is in the `stencil-demo-components` folder, the example project is in `angular-demo`.

**Other information:**

**Comment by danbucholtz** [comment] 2018-02-15 16:11
I have validated this is still an issue, even when building with the latest version of Stencil and linking.

This is a duplicate of a closed issue: https://github.com/ionic-team/stencil/issues/338

Thanks,
Dan

**Comment by jgw96** [comment] 2018-02-21 21:55
cc @jthoms1 any ideas here? Looks like a typings thing

**Comment by dkundel** [comment] 2018-02-23 18:45
The solution is already in the issue :) You are using global types that have to be referenced in the generated type files:

```typescript
/// <reference types="@stencil/core" />
```

**Comment by jgw96** [comment] 2018-02-23 18:46
@dkundel yep that's a good workaround, although you actually should not need to do that if we had the correct behavior here.

**Comment by Aaron-Sterling** [comment] 2018-02-23 21:19
I would *love* a fix here. I've published updates to npm twice now, and then had to re-publish immediately, because I forgot to add the line in after performing the build. It's easy to slip -- at least easy for me -- with multiple public-facing web components.

**Comment by jgw96** [comment] 2018-02-23 21:21
@Aaron-Sterling sorry about that, that does sound frustrating. We have this issue scheduled for our next milestone, so we will be getting to it very soon. In the meantime as a workaround, maybe you could write a little node script to include this snippet for you when you deploy?

**Comment by Aaron-Sterling** [comment] 2018-02-23 21:45
...and then lose my ability to complain on the internet about this????

Thanks for the idea, I'll probably do that.

**Comment by jgw96** [comment] 2018-02-23 21:46
😆

**Comment by adamdbradley** [comment] 2018-03-01 17:58
This should be fixed in the latest releases of stencil and ionic/core. Thanks!

**Closed by adamdbradley** 2018-03-01 17:58 UTC
Labels: bug

**Comment by trazek** [comment] 2018-03-01 20:27
I am on `@stencil/core": "^0.6.1",` and needed to use the proposed work around to get rid of the error.

**Comment by trazek** [comment] 2018-03-15 13:35
This seems fixed. I am using ``` "dependencies": {
    "@stencil/core": "^0.6.18"
  },``` and have no more issues.

**Comment by jarrettj** [comment] 2018-08-23 13:37
Hi,

Good day.

I'm getting this error in my angular app. And googling led me here. Excuse me if it is the wrong repo. 

Would any of you know where I would add <reference types="@stencil/core" /> in my angular app?

Regards.
JJ
