### ISSUE TITLE
styleUrls not working properly

### ISSUE THREAD

**Issue by juny58** [ionic-team/stencil#2430] opened 2020-05-12 14:41 UTC
**Stencil version:**

```
 @stencil/core@"^1.12.2"
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**

When entering multiple css file paths, it applies only the first one and ignores the rest. That is really frustrating.

**Expected behavior:**

As the name of the property oes, it should support multiple style files.

**Steps to reproduce:**

Put multiple files in styleUrls array, only first one applies.

**Comment by Nightmaster** [comment] 2020-05-14 08:04
Duplicate of #2324

**Comment by rwaskiewicz** [comment] 2022-08-26 13:44
Closing as a duplicate of #2324

**Closed by rwaskiewicz** 2022-08-26 13:44 UTC
Labels: triage
