### ISSUE TITLE
browserHeadless + browserSlowMo works only for the first Chromium window, which is empty

### ISSUE THREAD

**Issue by InvisibleKind** [ionic-team/stencil#2237] opened 2020-03-04 17:34 UTC
**Stencil version:**

```
@stencil/core@1.8.11
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

e2e tests start multiple Chromium windows, the first window is always empty and is the only window, which is affected by _browserSlowMo_. 
Each test starts in it's own Chromium window and _browserSlowMo_ doesn't affect them. They are opened and closed immediately after test execution.

**Expected behavior:**

Chromium windows, used for actual tests should respect _browserSlowMo_ setting.

**Steps to reproduce:**

1. Create at least one e2e test
2. Configure tests to run in Chromium without headless mode and with delay.
3. Run tests with `npm test`

**Related code:**

stencil.config.ts
```ts
// skip
testing: {
    browserHeadless: false,
    browserSlowMo: 3000,
    browserDevtools: true
}
```

**Comment by bison92** [comment] 2020-04-21 15:44
Same here, I can confirm this issue is still present as of 1.12.5

**Comment by jcfranco** [comment] 2021-10-29 18:56
This issue is still present in 2.9.0.

**Comment by Aex12** [comment] 2022-08-11 09:19
Same issue here, working with 2.13.0 stencil

**Comment by rwaskiewicz** [comment] 2022-08-12 13:54
Hey folks, if someone can create a reproduction case that the team can pull down, that'd be much appreciated!

**Comment by rwaskiewicz** [comment] 2022-09-01 17:28
I'm going to close this issue due to lack of being able to reproduce this issue. If this is still an issue, please feel free to create a new issue with a minimal reproduction URL for the team to pull down and take a look at. Thanks!

**Closed by rwaskiewicz** 2022-09-01 17:28 UTC
Labels: ionitron: needs reproduction
