### ISSUE TITLE
npm start fails after npm init

### ISSUE THREAD

**Issue by oliverjanik** [ionic-team/stencil#1068] opened 2018-09-06 05:55 UTC
```
> @stencil/starter@0.0.1 start D:\temp\stencil-test
> stencil build --dev --watch --serve

[53:09.6]  @stencil/core v0.11.0
[53:09.6]  build, app, dev mode, started ...
[53:09.8]  transpile started ...
[53:11.3]  transpile finished in 1.52 s
[53:11.3]  module map started ...
[53:11.4]  generate styles started ...
[53:11.6]  compile global style start ...
[53:11.8]  compile global style finish in 149 ms
[53:11.8]  generate styles finished in 409 ms
[53:11.9]  module map finished in 602 ms
[53:11.9]  generate bundles started ...
[53:11.9]  generate bundles finished in 7 ms
[53:12.0]  generate app files started ...
[53:13.2]  generate app files finished in 1.20 s

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           D:\temp\stencil-test\node_modules\request-promise-native\lib\rp.js:8:12 at module.exports
           (D:\temp\stencil-test\node_modules\stealthy-require\lib\index.js:62:23) at Object.<anonymous>
           (D:\temp\stencil-test\node_modules\request-promise-native\lib\rp.js:7:15) at Module._compile
           (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32)

[53:13.2]  dev server: http://localhost:3333/
```

Not a good start

**Comment by jthoms1** [comment] 2018-09-06 18:33
Closing as a duplicate of #800.

**Closed by jthoms1** 2018-09-06 18:33 UTC
Labels: triage
