### ISSUE TITLE
Changing a boolean attribute with mutable and reflectToAttr set to true from true to false leads to too many changes

### ISSUE THREAD

**Issue by ErikSchierboom** [ionic-team/stencil#1238] opened 2018-11-23 07:26 UTC
**Stencil version:**
```
@stencil/core@0.15.2
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
If one declares a `boolean` `mutable` property that also has the `reflectToAttrr` property, changing from `true` to `false` does not result in a single change, but in four changes. 

Note that the reverse (changing from `false` to `true` works correctly). Removing the `reflectToAttr` property also fixes the issue.

**Expected behavior:**
Changing such a boolean property from `true` to `false` should only lead to a single change.

**Steps to reproduce:**
* Create a component with a `boolean` property with the `mutable` and `reflectToAttr` attributes set to `true`.
* Add a watch on changes on that component.
* Add code to change the boolean property from `true` to `false` (and vice versa).
* Log the old and new value within that watch.
* Verify that changing the property value from `true` to `false` leads to the four different changes:
    - change from `true` to `false`
    - change from `false` to `null`
    - change from `null` to `undefined`
    - change from `undefined` to `null`

**Related code:**

```tsx
import { Component, Prop, Watch } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true
})
export class MyComponent {
  @Prop({ mutable: true, reflectToAttr: true }) boolAttr: boolean = false;

  propChanges: string[] = [];

  changeBoolAttr() {
    this.boolAttr = !this.boolAttr;
  }

  @Watch('boolAttr')
  boolAttrChanged(newValue: boolean, oldValue: boolean) {
    this.propChanges.push(`boolAtrr has changed from ${oldValue} to ${newValue}`);
  }

  render() {
    return (
      <div>
        <h1>Props with mutable:true and reflectToAttr:true changes demo</h1>

        <div>
          Bool attr: {this.boolAttr ? 'true' : 'false'}&nbsp;
          <button onClick={this.changeBoolAttr.bind(this)}>change</button>
        </div>
        <ul>
          {this.propChanges.map(propChange => <li>{propChange}</li>)}
        </ul>
      </div>);
  }
}
```

**Other information:**

**Comment by safebyte** [comment] 2019-01-26 11:55
I've experienced the same issue; only now it doesn't matter if the value is `true` or `false`, it always renders twice (see example below). Since I can understand that this might not be an easy fix, I would like to ask if we can expect a fix at any time - or if the double render might even be intentional?

Right now, the performance issues caused by the extra render isn't really a problem for me, but in some scenarios it might be better to avoid reflectingToAttr in favour of rendering times, even though other solutions (as [discussed in slack](https://stencil-worldwide.slack.com/archives/C79EANFL7/p1548438652756500)) might be more verbose. Please tell me I can safely ignore the double render because it will be fixed at some point and is not intentional. 🍰 

Thank you

Code to reproduce:
```typescript
import {Component, Prop, State} from "@stencil/core";

@Component({
	tag: 'test-component'
})

export class TestComponent {
	// changing this will cause two calls to render()
	@Prop({mutable:true,reflectToAttr:true}) prop;
	
	// changing this will case a single call to render()
	@State() state;

	// not a prop or state
	private renderings = 0;

	render(){
		this.renderings++;
		return [
			<p>
				Change <strong onClick={() => this.prop = !this.prop}>Prop</strong> or 
				<strong onClick={() => this.state = !this.state}>State</strong>
			</p>,
			Renderings: {this.renderings}
		]
	}
}
```

**Comment by dgibson666** [comment] 2019-05-02 13:06
I'm still on .15.2, awaiting the [ES6 polyfills fix](https://github.com/ionic-team/stencil/issues/1269) for Angular, but I'm having issues with booleans and came across this bug still open. Basically if I have a boolean prop (mutable and reflected to attr) that is defaulted to false, but set as a prop such as "active" on my custom element, when the attribute is removed dynamically, it becomes null. This doesn't work for strict boolean conditionals any longer, or for aria-selected={''+this.active+''} because null is not an appropriate value. Is this bug fixed or still lingering in newer versions?

**Comment by adamdbradley** [comment] 2020-01-02 02:02
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-02 02:02 UTC
Labels: triage
