### ISSUE TITLE
Inconsistent rendering of a slot's fallback content

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2307] opened 2020-03-24 16:43 UTC
**Stencil version:**

```
 @stencil/core@1.11.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The fallback content of a slot is rendered differently in evergreen browsers (works as expected ✅), old Edge ❌and IE11 ❌(rendering is different between these two). See screenshots

![default-slot-content__chrome-ff-safari](https://user-images.githubusercontent.com/1526846/77452549-10bc1280-6dc4-11ea-85f5-d4efeac3e7bd.png)
![default-slot-content__ie11](https://user-images.githubusercontent.com/1526846/77452562-13b70300-6dc4-11ea-9721-f9f2e1025b0b.png)
![default-slot-content__old-edge](https://user-images.githubusercontent.com/1526846/77452576-174a8a00-6dc4-11ea-8906-999ff5b03482.png)

**Expected behavior:**
Same as evergreen browsers in pre-chromium Edge and IE11.

**Steps to reproduce:**
Sample app: https://github.com/jcfranco/stencil-default-slot-content-old-edge-and-ie11

Components displays slotted data with a fallback value of `label`: https://github.com/jcfranco/stencil-default-slot-content-old-edge-and-ie11/blob/master/src/components/my-component/my-component.tsx#L10-L12

Tests with fallback label, with and without slotted content: https://github.com/jcfranco/stencil-default-slot-content-old-edge-and-ie11/blob/master/src/index.html#L14-L15

Note: sample uses 1.8.8, but I upgraded to 1.11.2 locally on a Windows machine, and the issue still exists.

**Comment by kevin-coyle** [comment] 2020-04-03 23:14
I've tested this on 1.12.1 and I'm still getting this issue as well, should it be reopened or should I open a new issue?

**Comment by PsySolix** [comment] 2020-05-11 10:41
Is there any progress on this? On all browsers this offers an issue... A framework for webcomponents should make sure that default/fallback slots work as intended (even with shadowDOM)..


component-a.tsx
`
render(){
....
	<div class="wrapper"><slot><input type="text" id={inputId} ... /> </slot></div>
....
}
`
Usage
`<xx-input/>` -> should render with the default input -> WORKS
`<xx-input><p>test</p></xx-input>` -> should render with ONLY the `<div><p>test</p></div>`

**Comment by viljamis** [comment] 2020-07-27 07:08
This issue isn’t fixed I believe? Just testing in IE11 and both the fallback and contents entered are shown.

**Comment by viljamis** [comment] 2020-07-27 07:21
It would be great to get this fixed. Currently preventing the usage of fallback content completely for us at least. We also have some components where shadow dom is disabled and we use the scoped styles and in that case this issue is showing up in all browsers, even Chrome (so not just Edge issue).

**Comment by viljamis** [comment] 2020-09-03 06:58
This issue does still exist and we just added a new pull couple days back for additional improvements over the previous pull request: https://github.com/ionic-team/stencil/pull/2650

**Comment by claviska** [comment] 2020-11-19 14:15
I've replicated the issue and the patch in #2650 does resolve it. I'll try to get this merged ASAP. Thanks for your patience!

**Closed** 2020-11-19 16:54 UTC
Labels: bug, help wanted
