### ISSUE TITLE
Changes to locally referenced packages are not rebundle with watch

### ISSUE THREAD

**Issue by wjhdev** [ionic-team/stencil#2587] opened 2020-07-22 23:50 UTC
**Stencil version:**
```
@stencil/core@v1.16.5 🐬
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When developing multiple locally linked packages a running compiler will not rebundle changes made to components in another locally linked (using `file:`) package.

**Expected behavior:**

Based on verbose logs, it appears that:
[37:02.3]  load collection: package1, ../package1/dist/collection/collection-manifest.json  MEM: 210.2MB

Does not run on rebuilds

**Steps to reproduce:**
Repo: https://github.com/wjhdev/stencil-multi-watch-example

Steps:
1. `cd package1/ ; npm install ; npm run build`
2. `cd package2/ ; npm install ; npm run start`
3. While the package2 compiler is watching, edit `/package1/src/my-component.tsx` (add something additional to render)
4. rebuilt package1: `cd package1/ ; npm run build`

What's odd is this will cause the running compiler from step 2 to initiate a rebuild, but it appears the changes to package1 are not then re-bundled.

Quit the compiler and restart it. Changes from step 3 should now be reflected.

**Comment by bitflower** [comment] 2020-07-23 14:31
Have you tried adding `package1` to the `include` array of `tsconfig` ?

**Comment by wjhdev** [comment] 2020-07-23 14:48
I have, yes. I've also tried creating compiling all components together with a single `stencil.config.ts` at a lerna root level, but haven't yet succeeded in getting that to work perfectly yet either.

Given this works after a forced full rebuild I don't think `tsconfig` is the issue here. I don't think it's a watch issue either, as changes in `node_modules/package1/dist/` do trigger a watch rebuild.

But from what I can tell the in memory file system only loads external components once (on initial compiler boot). So watch rebuilds don't recognize changes to external components.

**Comment by wjhdev** [comment] 2020-07-24 15:58
Digging into compiler code, the assumption in [parseCollection](https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/compiler/transformers/collections/parse-collection-module.ts#L6-L15) appears to be:

```
  let collection: d.CollectionCompilerMeta = compilerCtx.collections.find(c => c.collectionName === collectionName);
  if (collection != null) {
    // we've already cached the collection, no need for another resolve/readFile/parse
    // thought being that /node_modules/ isn't changing between watch builds
    return collection;
  }
```

So perhaps this is working as intended – though not ideal for developing across multiple packages

**Comment by bitflower** [comment] 2020-09-05 05:06
Dup of #2648 I think.

Have you tried the latest `2.0.3` release ? Something has been changed. It doesn't work for me yet but maybe you have some new findings in the new code?

**Comment by wjhdev** [comment] 2021-01-01 23:26
Returning to this as my current build scripts are wildly inefficient for my multi-module project. I saw [this](https://github.com/ionic-team/stencil/commit/7f739a0cac7423e91ac8614206b71894796965d8) monorepo related commit in v2.0 which gave me some hope, but isn't a fix for this specifically.

I did update the demo repo to v2.3.0:
https://github.com/wjhdev/stencil-multi-watch-example

If anyone has suggestions on other monorepo approaches I'd be interested to here/see examples!

**Comment by bitflower** [comment] 2021-01-02 00:09
It feels that there is not much missing for it to pick up the child changes! I hope to get some hours during Jan to have a look at this.

**Comment by wjhdev** [comment] 2021-01-03 14:03
Yep. I think if the watcher can recognize the change in local `.node_modules/` and delete the appropriate collection from the `compilerCtx.collections` cache before rebuild then `parseCollection` above would be forced to re-read it from disk.

**Comment by bitflower** [comment] 2021-01-03 19:31
Sounds like you would be able to pull this off? 

@adamdbradley Would you say this is the right path ?

**Comment by wjhdev** [comment] 2021-03-11 01:10
Still looking for a solution here and stumbled [on this](https://github.com/ionic-team/stencil/blob/master/notes/2020-09-09.md). 

Sounds like exactly like the issue here:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/3745345/110720253-dfef0c00-81d3-11eb-9748-ea7aa8063c43.png">

**Comment by splitinfinities** [comment] 2021-08-10 20:02
Duplicate of #2648 

If folks can share all their learnings in that issue, I would appreciate it.

**Closed by splitinfinities** 2021-08-10 20:02 UTC
Labels: Duplicate, Feature: Bundling, Feature: Compiler, Integration: Monorepo
