### ISSUE TITLE
bug: Rollup: Parse Error: Duplicate export

### ISSUE THREAD

**Issue by danyball** [ionic-team/stencil#4424] opened 2023-05-25 14:14 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.3.0

### Current Behavior

Throws error on `npm run build`:

```
[ ERROR ]  Rollup: Parse Error: ./src/components/my-component/my-component.tsx:80:9
           Duplicate export 'MyComponent' (Note that you need plugins to import files that are not JavaScript) Error
           parsing: /Users/XXXX/stencilboilerplate/test/src/components/my-component/my-component.tsx,
           line: 80, column: 9

```

### Expected Behavior

No error.

### System Info

```shell
MacOS, NPM 8.15.0
```

### Steps to Reproduce

1. create project: `npm init stencil`
2. add `private static myVar = "input"` to `my-component.tsx`
3. also change this line: `return format(this.first, this.middle, MyComponent.myVar);`
4. run `npm run build`

### Code Reproduction URL

notyet

### Additional Information

Creating a static variable is common to add a native event to the documentation with `@event` in JSDoc comment. For example:
```
  /**
   * Emitted when a user clicks on the button.
   * @event
   */
  private static eventInput = "input"
```

**Comment by rwaskiewicz** [comment] 2023-05-25 15:13
Thanks @danyball! I've confirmed that this is related to the TypeScript 5 upgrade.

**Comment by deleonio** [comment] 2023-05-26 10:57
Yes, we have the same issue, since update stencil from 3.2 to 3.3.

https://github.com/public-ui/kolibri/actions/runs/5081216007/jobs/9129248718

**Comment by rwaskiewicz** [comment] 2023-06-01 20:56
Hey folks,

I have a dev build that I believe will fix the issue. Can anyone running into this problem please install it and provide the team and I with some feedback?
```
npm i @stencil/core@3.3.0-dev.1685651872.3091be9
```

Thanks!

**Comment by danyball** [comment] 2023-06-02 06:46
Is working, thanks @rwaskiewicz !

**Comment by rwaskiewicz** [comment] 2023-06-02 19:10
Stencil v3.3.1 has just been released with a fix for this issue. If you encountered it on Stencil v3.3.0, please upgrade to 3.3.1. I'm going to close this issue out, but please feel free to open a new one should the issue reoccur. Thanks!

**Closed by rwaskiewicz** 2023-06-02 19:10 UTC
Labels: Bug: Validated
