### ISSUE TITLE
[2.6.0] jest can't resolve lerna dependencies (sym links)

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#2221] opened 2020-02-26 09:49 UTC
**Stencil version:**

```
 @stencil/core@2.0.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Currently `jest` has issues resolving internal `lerna`-sym-linked packages. They work during normal build (both dev and prod). After researching and trying many possible workarounds I wonder if I have to switch to another test runner. However Stencil is closely tied to `jest`. 

Would appreciate any help here!

Findings that make me believe that `jest` maintainers are not too keen on making sym links work better:
https://github.com/facebook/jest/issues/1477

Things I have tried:
- custom resolver: https://gist.github.com/gcangussu/af52da296aef829eba15ea626453f031
- `moduleNameMapper`, e.g.: https://github.com/kulshekhar/ts-jest/issues/269
- `transformIgnorePatterns `: https://jaketrent.com/post/jest-on-lerna-repo/
- artificial jest config at the root and inherited folder structure: https://github.com/facebook/jest/issues/3112

**Expected behavior:**
Tests run fine.

**Related code:**
Repo that re-produces the error scenario: https://github.com/bitflower/stencil-lerna-tests

**Comment by bitflower** [comment] 2020-03-05 16:52
Tried -22 quickly, unfortunately not solved:

![image](https://user-images.githubusercontent.com/6666636/76004609-08319400-5f0a-11ea-989e-7bf1ee2b62bd.png)

**Comment by bitflower** [comment] 2020-03-11 16:18
Ok, updated the repo to use latest `1.9.1` and `--next`.

**Comment by bitflower** [comment] 2020-03-11 16:19
Also added a branch which directly calls `jest` as discussed in the contributors chat. It can be found here:
https://github.com/bitflower/stencil-lerna-tests/tree/jest-directly

**Comment by bitflower** [comment] 2020-09-05 04:59
Just tried this again with Stencil 2.0.3 but it's still uncapable of resolving `lerna` sym linked packages in my components.

**Comment by bitflower** [comment] 2021-07-19 18:53
@rwaskiewicz @splitinfinities Hey guys! This is still a thing in the recent version `2.6.0`. Any chance this can be looked at anytime soon? Let me know if I can provide anything more then the above repo. Thanks!

https://github.com/bitflower/stencil-lerna-tests

![image](https://user-images.githubusercontent.com/6666636/126212040-d49dec79-7c7c-406b-b63f-bca94347af10.png)

**Comment by bitflower** [comment] 2021-07-20 11:53
Good news: I've fixed the issue with `jest` not being able to resolve the symlinked `lerna` packages.

Commit: https://github.com/bitflower/stencil-lerna-tests/commit/56e3b49835882d1fb9e510703f437628ac0810da

Still open: transform of imported sub-packages.

**Comment by splitinfinities** [comment] 2021-08-10 20:04
Duplicate of #2648

If you can share all their learnings in that issue, I would appreciate it.

**Closed by splitinfinities** 2021-08-10 20:04 UTC
Labels: triage
