### ISSUE TITLE
bug: shadowRoot gets removed by prototype overwrite from third party scripts

### ISSUE THREAD

**Issue by venkatesh-nagineni** [ionic-team/stencil#3856] opened 2022-11-29 16:49 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.19.3 (can be producible in old versions as well like 2.18)

### Current Behavior

We are using stencil components into angular project with MS clarity script to record user sessions but those components with `shadow` Dom and `shadowDomShim` enabled in config extras, shadowRoot not render because of MS clarity script overwrite attachShadow prototype but stencil checking if it is only native prototype otherwise not rendering shadow dom which seems to be not correct 

https://github.com/ionic-team/stencil/blob/80ef14361613706d38ad6799a03d3e5f1e1e6cbe/src/client/client-window.ts#L33-L36 

<img width="672" alt="Screenshot 2022-11-29 at 17 37 52" src="https://user-images.githubusercontent.com/21661817/204588622-f9043b71-b758-4688-9089-06ce4fe5d12e.png">

shadow root render if it's only native
<img width="545" alt="Screenshot 2022-11-29 at 17 38 37" src="https://user-images.githubusercontent.com/21661817/204588814-3716f93c-db2c-4cab-bd05-54d2db996557.png">

without clarity snippet
![Screenshot 2022-11-29 at 17 54 21](https://user-images.githubusercontent.com/21661817/204593083-0d0b8bdc-260a-420a-a1c0-be734eff3ae5.png)

### Expected Behavior

should render shadow root even prototype changes by other scripts

### Steps to Reproduce

inject following script into head section of index.html

 

    <script>
      // located in clarity -> https://www.clarity.ms/eus2/s/0.6.43/clarity.js
      var Ke = Element.prototype.attachShadow;
      try {
        Element.prototype.attachShadow = function (options) {
          return Ke.bind(this)(options);
        };
      } catch (t) {
        Ke = null;
      }
    </script>`

### Code Reproduction URL

https://github.com/venkatesh-nagineni/shadow-dom-test

### Additional Information

live reproduction [link](https://stackblitz.com/edit/github-s8keqq?file=package.json,src%2Fcomponents%2Fmy-component%2Fmy-component.tsx,src%2Fcomponents%2Fmy-component%2Fmy-component.css,src%2Fcomponents%2Fsvg%2Fsvg.css) 

original clarity script with prototype changes https://www.clarity.ms/eus2/s/0.6.43/clarity.js

**Comment by rwaskiewicz** [comment] 2022-12-15 17:53
Today, our check for `shadowDomShim` is [documented as ](https://stenciljs.com/docs/config-extras#shadowdomshim) (emphasis mine):

> If enabled true, the runtime will check if the shadow dom shim is required. However, if it's determined that shadow dom is already _natively supported_ by the browser then it does not request the shim. Setting to false will avoid all shadow dom tests. If the app does not need to support IE11 or Edge 18 and below, it's recommended to set shadowDomShim to false. Defaults to false.

where I'm not entirely sure it'd be possible to check for native support any other way.

I did a bit of research into _why_ we check for the native implementation of `attachShadow`, as opposed to just checking if it exists like so:
```
 export const supportsShadow = /* BUILD stuff omitted */ !!doc.head.attachShadow
```
And it turns out that we _used_ to do just that, until https://github.com/ionic-team/stencil/commit/8b5aa06e31919b16a9e11268441d250e254da36f, which fixes a similar bug where _another_ polyfill outside of Stencil’s control was setting `doc.head.attachShadow`.

 With that in mind, I'd argue that this feature is working as intended, but unfortunately doesn't play well with Clarity. I'm going to mark this as "won't fix", as I don't believe we can achieve a desirable outcome here.

**Closed by rwaskiewicz** 2022-12-15 17:53 UTC
Labels: Resolution: Needs Investigation
