### ISSUE TITLE
Feature request: Access elements by ref

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/stencil#237] opened 2017-10-11 09:17 UTC
In Vue and React you can put `ref="myElement"` on element, and access myElement from code, in Angular you use `#myElement`, I think it would be great idea to use any way to access elements

**Comment by jgw96** [comment] 2017-10-12 19:11
Hello, thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/ionic-team/stencil/issues/226

**Closed by jgw96** 2017-10-12 19:11 UTC
