### ISSUE TITLE
bug: ReferenceError: indexedDB is not defined at createStore

### ISSUE THREAD

**Issue by kpatel1989** [ionic-team/stencil#5019] opened 2023-11-03 20:17 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

I am trying to prerender our stencil application. I just got started on this. 
With minimal configs I tried to run the build command and it ended up with this error. 
```
> stencil build --docs --prerender

[02:25.7]  @stencil/core
[02:25.9]  v2.13.0 🍣
[02:29.7]  build, condition-report-widgets, prod mode, started ...
[02:29.7]  transpile started ...
[02:34.3]  transpile finished in 4.58 s
[02:34.3]  copy started ...
[02:34.3]  generate custom elements started ...
[02:34.3]  generate hydrate app started ...
[02:34.3]  generate lazy started ...
[02:35.3]  copy finished (106 files) in 1.02 s
[03:09.6]  generate custom elements finished in 35.25 s
[03:16.4]  generate hydrate app finished in 42.02 s
[03:22.8]  generate lazy finished in 48.47 s
[03:23.3]  build finished in 53.53 s

[03:24.9]  prerendering started ...
[03:25.4]  prerendering failed in 528 ms

[ ERROR ]  Hydrate Error
           ReferenceError: indexedDB is not defined at createStore
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:9550:17)
           at new IndexDBClass
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:9829:56)
           at /Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:9844:26
           at createCommonjsModule
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:9446:5) at
           hydrateAppClosure
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:9821:22)
           at hydrateFactory
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:100357:3)
           at render
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:100624:9)
           at
           /Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:100556:62
           at new Promise (<anonymous>) at Object.hydrateDocument
           (/Users/kartik.patel/Documents/newwave/condition-report-widgets/lib/dist-stencil/hydrate/index.js:100548:33)
```

I tried looking or this in the docs and on the net. I didnt find any reference to solve this problem. I didnt see any config to fix this. 
When I check the code base for `createStore`, I found that we reference the indexedDB object which is available on the browser, but it throws error during pre-rendering. 

Can you suggest what to do ? 

Here is my stencil config
```
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { inlineSvg } from 'stencil-inline-svg';
import nodePolyfills from 'rollup-plugin-node-polyfills';

import { stencilname, distDirs } from './package.json';

export const config: Config = {
  namespace: stencilname,
  buildEs5: false,
  hashedFileNameLength: 16,
  taskQueue: 'async',
  plugins: [
    sass({
      includePaths: ['node_modules/@kar-dmp/pattern-library/lib/dist-stencil/pattern-library'],
    }),
    inlineSvg(),
  ],
  testing: {
    setupFiles: ['fake-indexeddb/auto'],
    moduleNameMapper: {
      '.+\\.(svg|png|jpg)$': 'identity-obj-proxy',
    },
    collectCoverage: true,
    coverageReporters: ['json-summary', 'text', 'lcov'],
    collectCoverageFrom: ['<rootDir>/src/**/*.{ts,tsx}'],
    coveragePathIgnorePatterns: [
      '.stories.ts',
      '<rootDir>/src/test/mock.ts',
      '.d.ts',
      '<rootDir>/src/models/constants/index.ts',
      'cases/',
      'mocks/',
      'types/',
      'LoggingService.ts',
      'BaseWidget.tsx',
    ],
    coverageThreshold: {
      'global': {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
      'src/**/*.{ts,tsx}': {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
      'src/services/**/*.{ts,tsx}': {
        statements: 85,
        branches: 85,
        functions: 85,
        lines: 85,
      },
    },
  },
  devServer: {
    reloadStrategy: 'hmr',
    openBrowser: false,
  },
  outputTargets: [
    // creates /dist dir
    {
      type: 'dist',
      dir: distDirs.stencil,
      esmLoaderPath: '../loader',
      copy: [
        // copy fonts into static for storybook and stencil build
        { src: 'assets' },
      ],
    },
    // one file in es6
    {
      type: 'dist-custom-elements',
      dir: distDirs.stencil,
    },
    // creates readme.md for components
    {
      type: 'docs-readme',
    },
    // create components(.d.ts|json) into dist
    {
      type: 'docs-json',
      file: `${distDirs.stencil}/components.json`,
    },
    {
      type: 'www',
      baseUrl: 'https://stenciljs.com/',
      serviceWorker: null, // disable service workers
      prerenderConfig: './prerender.config.ts'
    },
  ],
  rollupPlugins: {
    // required to pack up Buffer under node modules in stencil build.
    // https://stenciljs.com/docs/module-bundling
    after: [nodePolyfills()],
  },
};
```

Here is my prerender config
```
import { PrerenderConfig } from '@stencil/core';
export const config: PrerenderConfig = {

};

```

### Expected Behavior

I would expect this to successfully render some html files. even if its empty. Since I havent configured anything or havent made any code change yet. 

### System Info

```shell
System: node 18.16.1
     Plaform: darwin (23.0.0)
   CPU Model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 cpus)
    Compiler: /Users/kartik.patel/Documents/newwave/condition-report-widgets/node_modules/@stencil/core/compiler/stencil.js
       Build: 20220124181123
     Stencil: 2.13.0 🍣
  TypeScript: 4.3.5
      Rollup: 2.42.3
      Parse5: 6.0.1
      Sizzle: 2.42.3
      Terser: 5.6.1
```

### Steps to Reproduce

1. Add www outputTarget with prerender config
2. Add prerender config with empty config. 
3. Run `stencil build --docs --prerender` 

### Code Reproduction URL

This is in a private org repo.

**Comment by alicewriteswrongs** [comment] 2023-11-03 20:33
Hey @kpatel1989, thanks for filing this issue.

Three things — first off, it looks like you're using Stencil v2.13.0, which is unfortunately now in [extended support status](https://stenciljs.com/docs/support-policy#stencil-maintenance-and-support-status) so the team isn't able to provide bugfixes and so on for it. Sorry about that! If you're still seeing the issue on a newer version of Stencil we'd be happy to help out, but until then I'm going to close this.

Second thing - `window.indexedDB` is a [runtime browser construct](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB) that won't be available during a pre-render, but will be available once your app boots in the browser. I'd suggest that you rewrite your code to not assume that `window.indexedDB` is available if you want to take advantage of pre-rendering - maybe you can gate the relevant code with something like

```js
if (window.indexedDB !== undefined) {
  // initialize DB
}
```

but not knowing your specific use case I can't really offer more specific help than that.

Third thing - if you file an issue for Stencil in the future we do require a minimal reproduction in order to work on an issue. We have this policy in place because we're a small team and if a minimal reproduction isn't provided we can lose a lot of time trying to reproduce issues, often without success. So in the future you could create a new project with `npm init stencil` and then push that to a new git repo.

Thanks!

**Closed by alicewriteswrongs** 2023-11-03 20:33 UTC
Labels: triage
