### ISSUE TITLE
bug: `connectedCallback` does not work as expected when `async`

### ISSUE THREAD

**Issue by jgroth** [ionic-team/stencil#3325] opened 2022-04-12 09:02 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v2.15.0

### Current Behavior

According to the documentation,  `connectedCallback` will run before `componentWillLoad`. However, when `connectedCallback` is `async` it will not wait for the promise from `connectedCallback` before running `componentWillLoad`. I'm not sure if this should work or not since the documentation is a bit vague. For `connectedCallback` it says 

> This lifecycle hook follows the same semantics as the one described by the [Custom Elements Spec](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements)

But further down it also says

> Lifecycle methods can also return promises which allows the method to asynchronously retrieve data or perform any async tasks. A great example of this is fetching data to be rendered in a component

### Expected Behavior

Either `componentWillLoad` should not run until `connectedCallback` has resolved its promise when it is `async`, or the documentation should be more clear on how this is supposed to work.

### Steps to Reproduce

Clone the repo and `npm start` to see the behavior

### Code Reproduction URL

https://github.com/jgroth/stencil-connected-callback

### Additional Information

Might be related to #2954

**Comment by rwaskiewicz** [comment] 2022-04-12 17:20
Thanks for the report! I'm going to label this to get it ingested to get looked into further

**Comment by adrianschmidt** [comment] 2022-04-13 13:33
It's not _super_ explicit from the reproduction code, but note that the value `'init'` is never rendered, because the `render` method _does_ wait for the async `componentWillLoad`. It's just the async `componentConnected` that it doesn't wait for.

**Comment by adrianschmidt** [comment] 2022-07-08 09:13
Stencil exports the following `ComponentInterface`:

```typescript
export interface ComponentInterface {
    connectedCallback?(): void;
    disconnectedCallback?(): void;
    ...
}
```

So I think this issue can be resolved by simply changing the docs from:

> Lifecycle methods can also return promises which allows […]

to:

> Some lifecycle methods can also return promises which allows […]

**Comment by christian-bromann** [comment] 2024-06-13 20:37
Thanks @adrianschmidt for your comment, I documented which lifecycle methods actually support async.

@jgroth if you need more lifecycle functions to support async operations, let's create a new issue for this. Thanks so much for pointing this out.

**Closed by christian-bromann** 2024-06-13 20:37 UTC
Labels: Resolution: Refine
