### ISSUE TITLE
Stenciljs w/ Cordova --prerender fails to load resources (all the js files)

### ISSUE THREAD

**Issue by jpgilchrist** [ionic-team/stencil#383] opened 2017-12-23 12:56 UTC
**Stencil version:**
```
$ npm list @stencil/core
stencil-cordova@1.0.0 /Users/jpgilchrist/Development/temp/cordova
└── @stencil/core@0.1.1-0
```

**I'm submitting a:**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
It renders, but nothing works past that (see steps to reproduce)

**Expected behavior:**
It should at least work as well as w/o prerender on cordova. I did the exact same steps below but instead of `npm run build`, I ran `./node_modules/.bin/stencil build --dev` and the application works (but it has issues with the included stencil-router - ticket opened there about that).

**Steps to reproduce:**
https://github.com/jpgilchrist/stencil-cordova
- `npm run build` (`stencil build --prerender`)
- `cordova run android`
- open chrome inspector and debug your device

**Related code:**

see linked github... the only real code I changed was to my-app.tsx and modified the route url pattern in order to make it "functional".

**Other information:**
I know this is new and you are focusing on web, however I know you'll eventually be incorporating the rest of the ionic framework at some point in time. Keep up the good work!

**Comment by jgw96** [comment] 2017-12-27 16:07
Hey, thanks for opening an issue with us! Are you getting 404's or anything in the console? Im guessing that maybe some paths are not correct in cordova.

**Comment by jpgilchrist** [comment] 2017-12-27 19:56
@jgw96 yes, you can run the project I setup pretty easily. 

running the project and then clicking on the profile page icon: 

![image](https://user-images.githubusercontent.com/5065660/34391782-e2e1667c-eb15-11e7-911f-8739efe977be.png)

I know with other routers in cordova, you have to make sure you don't use html5 history mode and instead use the legacy `index.html#/path/like/this` because otherwise it fails in a similar fashion. (for instance vue-router).

**Comment by jgw96** [comment] 2018-01-09 16:53
Hello! I am going to close this issue as a duplicate of https://github.com/ionic-team/stencil-router/issues/27 for now. Thanks for using Stencil!

**Closed by jgw96** 2018-01-09 16:53 UTC
Labels: needs reply

**Comment by jgw96** [comment] 2018-01-10 17:33
No problem
