### ISSUE TITLE
Cannot find module '../core/renderer/h'.

### ISSUE THREAD

**Issue by lifeiscontent** [ionic-team/stencil#591] opened 2018-03-03 15:06 UTC
**Stencil version:**

```
@stencil/core@0.6.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
throws an error

**Expected behavior:**
requires expected file

**Steps to reproduce:**
I'm using alm typescript ide.
open an `@stencil` component starter kit project
see the following error

./node_modules/@stencil/core/dist/testing/index.d.ts:8 Cannot find module '../core/renderer/h'.

**Related code:**

https://github.com/ionic-team/stencil/blob/2b36449ea1ac4ed86b56e059df10198f513c0ebd/src/testing/index.ts#L10

**Other information:**

**Comment by adamdbradley** [comment] 2018-03-04 13:32
Would you be able to test with the latest version? I believe this might have already been fixed.

**Comment by lifeiscontent** [comment] 2018-03-05 17:32
@adamdbradley how would I do that? is it just `npm install @stencil/core@beta`?

**Comment by jgw96** [comment] 2018-03-05 17:50
@lifeiscontent , you can run `npm install @stencil/core@latest`

**Comment by jgw96** [comment] 2018-03-05 20:14
Hey @lifeiscontent , im going to close this issue for now as I cannot reproduce with the latest version. Also, note to self, document how to get the latest version of Stencil https://github.com/ionic-team/stencil-site/issues/143

**Closed by jgw96** 2018-03-05 20:14 UTC
Labels: needs reply

**Comment by lifeiscontent** [comment] 2018-03-05 20:22
@jgw96 cool, seems to be working thanks!

**Comment by jgw96** [comment] 2018-03-05 20:23
No problem!
