### ISSUE TITLE
Cannot set property 'ES6Promise' of undefined

### ISSUE THREAD

**Issue by marisaoliva** [ionic-team/stencil#676] opened 2018-03-28 07:08 UTC
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

In windows lastest version chrome or the lastest chronium version. when you compile for the first time show the error

Uncaught TypeError: Cannot set property 'ES6Promise' of undefined
    at mutua-components-guide.core.pf.js:50
    at mutua-components-guide.core.pf.js:50

**Expected behavior:**
normal behavior

**Steps to reproduce:**
1. compile files
2. open windows lastest version chrome 
3. saves files
4. error
-->

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment] 2018-03-28 14:46
@marisaoliva I have not seen this issue on my surface book running the latest version of windows 10 and latest stable version of Chrome. Do you have a repo I could use to reproduce this?

**Comment by bitflower** [comment] 2018-03-28 14:50
Might be related https://github.com/ionic-team/stencil-postcss/issues/6

**Comment by jgw96** [comment] 2018-03-28 14:52
Thanks @bitflower . @marisaoliva are you using PostCSS ?

**Comment by jagreehal** [comment] 2018-03-28 15:20
@jgw96 @marisaoliva I get this error and I am using PostCSS

**Comment by jgw96** [comment] 2018-03-29 15:02
Hello all! Since it looks like this is an issue specifically with PostCSS I am going to be closing this issue in favor of https://github.com/ionic-team/stencil-postcss/issues/6 . Ill ping someone on the team who knows about the PostCSS plugin. Thanks for using Stencil everyone!

**Comment by marisaoliva** [comment] 2018-03-29 15:13
Hello, I'm not use postcss, I use sass, and  I also  building es5 

thanks!!

**Comment by bfmatei** [comment] 2018-03-29 17:15
PR created to fix this issue.

**Comment by brandyscarney** [comment] 2018-03-30 17:22
I am able to reproduce this in `@ionic/core` by running the following command:

```
npm run dev --no-open --es5
```

The initial build works fine, but after I make a change to a file (I specifically changed a `*.scss` file) after the rebuild I am seeing the following error in Chrome:

```
ionic.core.pf.js:49 Uncaught TypeError: Cannot set property 'ES6Promise' of undefined
```

This error does not exist in Firefox.

**Closed** 2018-04-01 22:13 UTC
Labels: bug

**Comment by tyvdh** [comment] 2020-09-02 16:50
Just ran into this with `2.0.2`. A bit puzzling why it's calling using `undefined` as an argument rather than `this` or `global`.

```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.ES6Promise = factory());
}(undefined, (function () { 'use strict';
```
