### ISSUE TITLE
Stencil does not provide support for true source-mapping

### ISSUE THREAD

**Issue by FDiskas** [ionic-team/stencil#1465] opened 2019-04-13 20:42 UTC
We need it. Please add it :)
Suggestion:
* Development: Inline Source maps
* Production: separate files. (usually source maps are uploaded after the build e.x. to sentry.io)

**Comment by jthoms1** [comment] 2019-04-30 13:31
Duplicate of #1255

**Closed by jthoms1** 2019-04-30 13:31 UTC
Labels: triage
