### ISSUE TITLE
Stencil method isn't instantiated at lifeCycle time of NgAfterViewInit (Angular)

### ISSUE THREAD

**Issue by MiguelC1990** [ionic-team/stencil#1338] opened 2019-01-28 18:18 UTC
**Stencil version:**

```
 @stencil/core@0.17.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When a method is immediately called on NgAfterViewInit, nothing occurs as the method has not been instantiated yet by stencil web component.

**Expected behavior:**
At time of view initialization, all methods should be instantiated by stencil

**Steps to reproduce:**

**Related code:**
Angular: 
```ts
  ngAfterViewInit() {
    console.log('ewfewfewf', this.container.nativeElement.setNavItemOverride);
    this.container.nativeElement.setNavItemOverride('settings-SettingsDashboard', {
      attributes: {
        href: 'https://www.google.com',
      },
    });
    setTimeout(() => {
      console.log('ewfewfewf', this.container.nativeElement.setNavItemOverride);
    }, 3000);
  }
```

stencil:
```tsx
  @Method()
  setNavItemOverride(uniqueId: UniqueId, override: Partial<NavItem>) {
    console.log('i have benn called');
    this.navItemOverrides = {
      ...this.navItemOverrides,
      [uniqueId]: override,
    };
  }
```
first log: `ewfewfewf ƒ (){}`
second log: `ewfewfewf ƒ (e,t){var n;console.log("i have benn called"),this.navItemOverrides=Object.assign({},this.navItemOverrides,((n={})[e]=t,n))}`
Stencil core version: 0.17.0

**Comment by MiguelC1990** [comment] 2019-01-28 21:18
after reading `https://stenciljs.com/docs/methods#methods-must-be-async` it seems the issue is the method is not being queued properly to execute once component is finished loading as stated in documentation

**Comment by Jefftopia** [comment] 2019-03-08 15:05
Bump, I just ran into this issue as well.

**Comment by jthoms1** [comment] 2019-03-08 20:46
Not sure the reason that this is a Method instead of just using a Prop.  Methods may not be ready yet when you try to execute them directly, but props are handled for you. This is especially true if you are just using the method to set some internal state.

Either way if you want to keep using this code the way it is you will need to use this in your Angular code.

```ts
  async ngAfterViewInit() {
    console.log('ewfewfewf', this.container.nativeElement.setNavItemOverride);
    await this.container.nativeElement.componentOnReady();
    this.container.nativeElement.setNavItemOverride('settings-SettingsDashboard', {
      attributes: {
        href: 'https://www.google.com',
      },
    });
    setTimeout(() => {
      console.log('ewfewfewf', this.container.nativeElement.setNavItemOverride);
    }, 3000);
  }
```

**Comment by Jefftopia** [comment] 2019-03-08 20:51
@jthoms1 The props thing is beside the point. An `@Method` should be invocable here.

I just tried to reproduce and `await`ing for `componentOnReady()` still throws an error. See the referenced issue.

**Comment by jthoms1** [comment] 2019-03-11 15:28
I think @Jefftopia issue was answered in #17735. @MiguelC1990 Did the code I provided resolve the issue for you?

**Comment by Jefftopia** [comment] 2019-03-11 16:00
@jthoms1 Yes and no. including `@ionic/angular` solves the problem if a developer is using that package. What if you're not?

It seems like ionic's root angular ng-module should be packaged with stencil.

**Comment by axelboc** [comment] 2019-04-18 13:01
Same problem here. I have an `async` method that doesn't do anything unless I call it after `componentOnReady`.

The line below throws an unhandled promise rejection error on some browsers, notably Edge, IE11 and some old versions of Chrome.

```
await elementRef.nativeElement.componentOnReady();
```

Even though I check for the existence of `nativeElement` beforehand, I get this error:

```
Unable to get property 'componentOnReady' of undefined or null reference.
```

**Comment by adamdbradley** [comment] 2020-01-02 02:13
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-02 02:13 UTC
Labels: triage
