### ISSUE TITLE
Capture events not working in JSX

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#2889] opened 2021-04-20 13:31 UTC
**Stencil version:**

```
 @stencil/core@2.5.2
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The following talks about a _specific_ event, but the same applies to other events as well.

When `onKeyDownCapture` is bound on an HTML element in the JSX, it is never fired. For example:

```html
<input onKeyDown={() => console.log('JSX: onKeyDown')}
            onKeyDownCapture={() => console.log('JSX: onKeyDownCapture')} />;
```

When the component containing this is rendered and the user types in the input, only the "JSX: onKeyDown" is output to the console.

Placing this same input markup inside a React component will result in first the "JSX: onKeyDownCapture" and then the "JSX: onKeyDown" message being logged to the console.

It should be noted that adding a method to the component with a `@Listen('keydown', { capture: true })` _does_ work as expected. It is only the bindings on elements within the JSX that is not working as expected.

**Expected behavior:**
Capture events bound on the HTML elements should fire as expected during the capture phase of the event.

**Steps to reproduce:**

- Clone and run: https://github.com/jcfranco/stencil-vdom-capture-listeners-not-firing
- Open the devtools and display the console
- Type stuffs in the input

**Related code:**

Key portion of demo: https://github.com/jcfranco/stencil-vdom-capture-listeners-not-firing/blob/master/src/components/my-component/my-component.tsx

**Comment by tanner-reits** [comment] 2023-12-07 19:17
This was fixed in #4968 and released in [Stencil v4.7.0](https://github.com/ionic-team/stencil/releases/tag/v4.7.0)

**Closed by tanner-reits** 2023-12-07 19:17 UTC
Labels: Bug: Validated

**Comment by nwhittaker** [comment] 2024-10-21 21:54
Can this issue be reopened? When using `onKeyDownCapture`, I see an event listener is created on the element listening for `keyDown` event types. However, it never hits because the actual event type should be `keydown` (all lower case).

The linked PR only tests click capture events, so it's unclear if this is a regression or if this issue was never really resolved.

**Comment by christian-bromann** [comment] 2024-10-22 01:33
@nwhittaker mind raising a new issue with a reproducible example? Thank you!
