### ISSUE TITLE
bug: spyOnEvent() removes properties in event.detail that contain callback functions

### ISSUE THREAD

**Issue by buddamus** [ionic-team/stencil#3324] opened 2022-04-11 21:20 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.14.2

### Current Behavior

Emitting an event in a component that looks like 
```ts
this.doEvent.emit({
      errorHandler:(err)=>{console.error(err)},
      successHandler:(val)=>{this._value = val},
      foo:"bar",
      test:true
})
```

And listening in a test with
```ts
const page = await newE2EPage();
await page.setContent('<my-component></my-component>');
const element = await page.find('my-component');
expect(element).toHaveClass('hydrated');
const eventSpy = await element.spyOnEvent("doEvent");
element.setProperty("last","updated");
await page.waitForChanges();
expect(eventSpy).toHaveReceivedEvent();
const keys = Object.keys(eventSpy.lastEvent.detail);
//THESE WILL SUCCEED
expect(keys).toContain("foo");
expect(keys).toContain("test");
//THESE WILL FAIL
expect(keys).toContain("successHandler");
expect(keys).toContain("errorHandler");
```
### Expected Behavior

All properties emitted are available in the test

### Steps to Reproduce

1. checkout the project
2. npm install 
3. npm run test

### Code Reproduction URL

https://github.com/buddamus/stencilJsSpyOnEventWithCallbacks

**Comment by rwaskiewicz** [comment] 2022-04-20 12:57
Hey @buddamus,

Thanks for the detailed report! I was able to confirm the behavior you described by using the reproduction you provided. 

This appears that this may be a duplicate of https://github.com/ionic-team/stencil/issues/3076, where functions aren't being serialized for event spies. In the linked PR it's _slightly_ different from your reproduction - that reproduction uses an array of objects, where each object contains a property that is a function, where your reproduction has a little less nesting.  

With that being said, I'm going to close this as a duplicate of https://github.com/ionic-team/stencil/issues/3076. https://github.com/ionic-team/stencil/issues/3076 is currently in our backlog to be investigated further. While we can't provide a definite timeline, this'll definitely help us sort this issue out. Thanks again!

**Closed by rwaskiewicz** 2022-04-20 12:57 UTC
Labels: triage
