### ISSUE TITLE
Event listening is clashed when same componet is used twice on single page

### ISSUE THREAD

**Issue by urvesh86** [ionic-team/stencil#2881] opened 2021-04-12 05:05 UTC
**Stencil core version: 2.0.1**

I am using stencil framework in my project to create components. Project structure is tree base means subcompacts are having sub components as well. I have used custom events at many places.

My concern is when I listen events with parameter target:body, code is executed twice as I have used same component twice on single page. I have created sample component to show the issue/concern.

**Main component code snippet**

```
import { Event, EventEmitter, Component, Prop, h } from '@stencil/core';
@Component({
   tag: 'my-component'
})
export class MyComponent {
  @Prop() first: string;
  @Prop() middle: string;
  @Prop() last: string;
  @Event() nameClick: EventEmitter;

  handleClickEvent(e): void {
    this.nameClick.emit({ name: `${this.first} ${this.middle} ${this.last}` });
  }

render() {
   return (
     <div>
       <div onClick={(e) => this.handleClickEvent(e)}><u>Click here to show you name!!</u></div>
       <p><div>Your full name</div><sub-component></sub-component></p>
     </div>
   )
 }
}


```

**Sub component snippet**

```
import { Component, h, Listen, State } from '@stencil/core';
@Component({
  tag: 'sub-component'
})
export class SubComponent {

@State() fullName: string;

@Listen('nameClick', { target: 'body' })
onNameClick(event: CustomEvent) {
    this.fullName = event.detail.name;
}
render() {
    return <input type="text" value={this.fullName}></input>
 }
}
````

**Html page where component is used**

```
<div id="content" class="tabcontent">
 <div style="width:50%;float:left">
  <p>Component 1</p>
  <my-component first="Stencil" middle="web" last="component"></my-component>
 </div>
 <div style="width:50%;float:right">
  <p>Component 2</p>
  <my-component first="Stencil" middle="web" last="component"></my-component>
 </div>
</div>
```

It seems this code is culprit to listen event twice  `@Listen('nameClick', { target: 'body' })`.

[GIF for demo](https://i.imgur.com/22l3cBh.gif)

Thanks in advance for a help!!

**Comment by felixblaschke** [comment] 2021-04-13 09:01
Works as intended. You have two components... also two subComponents...so two listener on body.

Don't listen on events on body.
Use JSX listener: https://stenciljs.com/docs/events#using-events-in-jsx

**Comment by urvesh86** [comment] 2021-04-13 12:17
@felixblaschke Thanks for the reply.. 

Where can I listen the event instead of body?

**Comment by felixblaschke** [comment] 2021-04-13 12:34
Read the manual. I posted you a link to the relevant part: https://stenciljs.com/docs/events#using-events-in-jsx

**Comment by rwaskiewicz** [comment] 2022-01-14 14:10
Hey all, the code snippet in the PR summary appears to be working as expected.

In this particular example, I'd recommend altering `sub-component` to accept a `@Prop` containing the name from `my-component`, since `sub-component` is a child of `my-component`. I recreated this project locally, and made the following changes:

```diff
// my-component.tsx
-import { Component, Prop, h, Event, EventEmitter } from '@stencil/core';
+import { Component, Prop, h, Event, EventEmitter, State } from '@stencil/core';
 
 @Component({
   tag: 'my-component',
@@ -21,15 +21,17 @@ export class MyComponent {
 
   @Event() nameClick: EventEmitter;
 
+  @State() wholeName: string;
+
   handleClickEvent(_e): void {
-    this.nameClick.emit({name: `${this.first} ${this.middle} ${this.last}`});
+    this.wholeName = `${this.first} ${this.middle} ${this.last}`;
   }
 
   render() {
     return (
       <div>
         <div onClick={(e) => this.handleClickEvent(e)}><u>Click here to show your name</u></div>
-        <p><div>Hello, World! I'm </div><sub-cmp></sub-cmp></p>
+        <p><div>Hello, World! I'm </div><sub-cmp name-info={this.wholeName}></sub-cmp></p>
       </div>
     );
   }
```
```diff
// sub-component.tsx
-import { Component, State, Listen, h } from '@stencil/core';
+import { Component, Prop, h } from '@stencil/core';
 
 @Component({
   tag: 'sub-cmp',
 })
 export class SubCmp {
-  @State() fullName: string;
-
-  @Listen('nameClick', {target: 'body'})
-  onNameClick(event: CustomEvent) {
-    this.fullName = event.detail.name;
-  }
+  @Prop() nameInfo: string;
 
   render() {
-    return <input type="text" value={this.fullName}></input>
+    return <input type="text" value={this.nameInfo}></input>
   }
 }
```
which achieves the independent `input` box value population the original poster is looking for.

I'm going to close this issue as I believe this is "working as intended" - thanks for understanding!

**Closed by rwaskiewicz** 2022-01-14 14:10 UTC
Labels: Resolution: Support

**Comment by bbansalWolfPack** [comment] 2022-06-18 03:21
I am facing the same issue where I have a component I am consuming (it's a select dropdown) and it emits even whenever user selects something and i am using two of these on same page. But then if I clicked on the first one, the second even handler gets fired too.

Any solution for this? I saw comments but couldn't make out much
