### ISSUE TITLE
Stencil can not recognize wasm exports

### ISSUE THREAD

**Issue by Arseniusz** [ionic-team/stencil#2811] opened 2021-02-04 11:07 UTC
**Stencil version:**

```
@stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When use dependencies with .wasm files compiler ignore all exported functions.
Bundling Warning MISSING_EXPORT...

**Expected behavior:**

Compiler properly read wasm files

**Steps to reproduce:**

- install rollup-wasm plugin
- install any dependency with wasm (npm install @silvia-odwyer/photon)
- try to build project
**Related code:**

My stencil.config
```tsx
import { Config } from '@stencil/core';
import dotenvPlugin from 'rollup-plugin-dotenv';
import { postcss } from '@stencil/postcss';
import autoprefixer from 'autoprefixer';
import { wasm } from '@rollup/plugin-wasm';

export const config: Config = {
  namespace: 'mediaopt-widgets',
  taskQueue: 'async',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
    {
      type: 'docs-readme'
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers,
      copy: [
        { src: 'mocks' },
        { src: 'assets' },
        { src: 'favicon.ico' }
      ],
    }
  ],
  plugins: [
    dotenvPlugin(),
    wasm(),
    postcss({
      plugins: [autoprefixer()]
    })
  ],
  testing: {
    browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
};

```

**Other information:**

Looks like bug reproduced only on Rust based packages.

**Comment by alicewriteswrongs** [comment] 2023-01-27 14:57
Hi @Arseniusz, thanks for filing this issue and letting us know about your interest in using Stencil with WebAssembly modules! Sorry that it took so long for anyone on the Stencil team to reply to your message.

At present, WebAssembly interopt is not something that Stencil officially supports. Accordingly, I'm going to label this as a feature request so we can gauge community interest in.

**Comment by rwaskiewicz** [comment] 2023-05-19 19:42
Closing this as a duplicate of https://github.com/ionic-team/stencil/issues/2543

**Closed by rwaskiewicz** 2023-05-19 19:42 UTC
Labels: Feature: Want this? Upvote it!
