### ISSUE TITLE
bug: Client-side error with formAssociated web component generated with @stencil/react-output-target in Next.js leads to: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by baumgm94** [ionic-team/stencil#6038] opened 2024-10-31 09:03 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.22.2

### Current Behavior

Using a Stencil Web Component (the `formAssociated` flag set to true) wrapped by `@stencil/react-output-target` within a form in a Next.js App, leads to an client-side error `Uncaught RangeError: Maximum call stack size exceeded `

### Expected Behavior

The Stencil web component, generated as a React component via @stencil/react-output-target and used within an HTML form in a Next.js application, should function without errors. Specifically, setting formAssociated: true on the component should not result in any client-side errors, and no Uncaught RangeError: Maximum call stack size exceeded error should be thrown.

### Steps to Reproduce

1. Clone [Repository](https://github.com/baumgm94/nextjs-stenciljs-example)
2. Install dependencies: `npm ci`
3. Build web-components: `npm run build:web-components`
4. Start development server: `npm run dev:app`
5. Open browser: [http://localhost:3000](http://localhost:3000)
6. Open dev-tools and reload page, you should see: `Uncaught RangeError: Maximum call stack size exceeded`

### Code Reproduction URL

https://github.com/baumgm94/nextjs-stenciljs-example

**Comment by jdpoccorie** [comment] 2024-10-31 19:48
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by matheusviriato** [comment] 2024-11-06 14:00
This error unfortunately happens to me. I'm trying to use components with `formAssociated` in a vite+react SPA application and I'm having the same error. I've used my component with and without the `@AttachInternals()` decorator and the error still persists. It only stops when I remove the `formAssociated` property :(

It seems that the error is in this internal function `getHostRef`. I don't know if in the generation of `dist-custom-elements` there is some reference loop because of the `element internals`...

**Comment by christian-bromann** [comment] 2024-11-07 00:33
@baumgm94 thanks for reporting and providing a reproducible example. Our team is working on a lot of competing efforts and can't take a look at this immediately. Any contributions are welcome.

**Comment by dwirz** [comment] 2024-11-13 13:59
Hello @christian-bromann,

I’ve opened a PR to address the issue which is discussed here. Could you, or someone from the Ionic team, take a quick look at it? Resolving this would mean a lot to us, as it’s currently a blocker for our customer’s component library.

Thanks in advance, and a big thank you to the team for the fantastic work on Stencil! 🤗

**Comment by christian-bromann** [comment] 2024-11-21 19:20
This has been released in https://github.com/ionic-team/stencil/releases/tag/v4.22.3

**Closed by christian-bromann** 2024-11-21 19:20 UTC
Labels: Bug: Validated
