### ISSUE TITLE
Local server always refreshes and cannot visit this URL address

### ISSUE THREAD

**Issue by noberk** [ionic-team/stencil#634] opened 2018-03-19 17:48 UTC
**Stencil version:**

```
@stencil/core@0.6.1
```

**I'm submitting a:**

[x ] bug report

**Current behavior:**

 
  I run the terminal and type in  "npm start" .. later popup a browser page by chrome
  the URL displayed http://localhost:3333/ and it's always refreshing refreshing refreshing 
 , so I can't visit this address  
  but I do the same way at my work place, it worked well 

**Expected behavior:**

It should be visit http://localhost:3333/ address on browser successfully without always refreshing

**Comment by adamdbradley** [comment] 2018-03-20 18:39
Is one of them on `windows`? Do you have an example that we can use to recreate the issue? Thanks

**Comment by noberk** [comment] 2018-03-22 09:23
@adamdbradley  they all on windows

**Comment by noberk** [comment] 2018-03-22 09:23
@adamdbradley  windows 10

**Comment by adamdbradley** [comment] 2018-03-22 14:41
Would you be able to build a minimal example that recreates the issue every time? That'd help us debug and fix it.

**Comment by noberk** [comment] 2018-03-23 02:16
@adamdbradley  My project that is your official starter who I installed .. it's just minimal example...  here have some issue snapshot  ..

**Comment by jgw96** [comment] 2018-03-26 02:12
Just tried this on my windows 10 machine (a surface book) and was not able to reproduce this with the latest app starter and PWA toolkit. @noberk which starter exactly was this issue happening with? Also what version of node do you have installed?

**Comment by jgw96** [comment] 2018-03-27 18:39
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!

**Closed by jgw96** 2018-03-27 18:39 UTC
