### ISSUE TITLE
bug: CLI args of test names not propagated to Jest

### ISSUE THREAD

**Issue by duhem-s** [ionic-team/stencil#3825] opened 2022-11-16 14:49 UTC
**Stencil version:**
```
 @stencil/core@2.19.x
```

**Current behavior:**
I used to do `npm run test:unit -- mg-form` to only test my `mg-form` component but since the version 2.19.x I'm not able to do so, all my unit tests are launched.

My `test:unit` script run `stencil test --spec`.

**Expected behavior:**
Be able to run a specific test file.

**GitHub Reproduction Link:**
https://github.com/duhem-s/stencil-cli

**Other information:**

With the command: `npm run test -- second` on the GH reproduction :

With stencil@2.18.1
![image](https://user-images.githubusercontent.com/113420581/202201370-84f637b0-cb4d-4ed8-9259-055130791ed4.png)

With stencil@2.19.0
![image](https://user-images.githubusercontent.com/113420581/202202127-1646821d-f3bf-4028-97d8-c1cd1502a9c6.png)

**Comment by alicewriteswrongs** [comment] 2022-11-16 17:50
Is it possible this is a duplicate of #3785?

**Comment by alicewriteswrongs** [comment] 2022-11-16 18:21
I just confirmed that this is the same issue as #3785, I have a fix which fixes the problem in both the reproduction for that issue and this one. I'm going to open a PR for that shortly, but I'm going to close this issue for bookkeeping purposes.

**Comment by duhem-s** [comment] 2022-11-17 08:49
Hi @alicewriteswrongs 👋

I opened a new one https://github.com/ionic-team/stencil/issues/3828 do you think your PR will also fix this ?

**Comment by alicewriteswrongs** [comment] 2022-11-17 14:51
Unfortunately that does look like a separate issue - at present we have a manually-defined set of short aliases like that which we support, and `-u` is, sadly, not among them at present 😢

**Comment by alicewriteswrongs** [comment] 2022-11-18 15:44
Ok so I just realized, belatedly, that #3785 is _not_ the same issue as this one, so I'm going to re-open this issue so we can keep track of making sure that our next release fixes it.

Sorry for the noise!

**Comment by rwaskiewicz** [comment] 2022-12-05 18:05
@duhem-s 👋 

I was able to verify that as of [Stencil v2.20.0, ](https://github.com/ionic-team/stencil/releases/tag/v2.20.0) this issue has been fixed using your reproduction case:
![Screenshot 2022-12-05 at 1 02 03 PM](https://user-images.githubusercontent.com/1930213/205709252-1f0e46f3-7d33-4846-b30f-7e885c7880f1.png)

I'm going to close this as a result. Thanks again for the detailed reproduction case, it was helpful both in triaging the issue and verifying the fix worked!

Should this bug reappear, please feel free to open a new issue. Thanks!

**Closed by rwaskiewicz** 2022-12-05 18:05 UTC
Labels: Bug: Validated
