### ISSUE TITLE
Prerender flag doesn't work with Axios

### ISSUE THREAD

**Issue by cptflammin** [ionic-team/stencil#2969] opened 2021-07-19 00:38 UTC
As stated [here](https://github.com/ionic-team/stencil/issues/2575) - but wrongly closed - prerendering fails when using Axios

Problem is that some libraries like AWS AmplifyJS use Axios under the hood.

@adamdbradley  Any idea how to solve this serious issue?

**Comment by splitinfinities** [comment] 2021-08-10 18:47
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

Can you help us make a reproduction case? This would help us to identify and solve the problem sooner rather than later. 

Thank you!

**Comment by tricki** [comment] 2021-09-06 12:47
There is a repro case in the original issue: https://github.com/xvs32x/port-stencil

I'm having the same problem with Stencil 2.8.0 and axios 0.21.3

**Comment by tricki** [comment] 2021-09-06 13:10
I did some debugging and the problem seems to be that `MockAnchorElement` objects don't have a `pathname` property:

```js
var urlParsingNode = document.createElement('a');
urlParsingNode.pathname === undefined
```

**Definition of `MockAnchorElement`:**
```js
class MockAnchorElement extends MockHTMLElement {
  constructor(ownerDocument) {
    super(ownerDocument, 'a');
  }
  get href() {
    return fullUrl(this, 'href');
  }
  set href(value) {
    this.setAttribute('href', value);
  }
}
```

@splitinfinities Is there any way we can extend `MockAnchorElement`?

**Comment by splitinfinities** [comment] 2021-09-07 17:00
@tricki Awesome investigation! Since that's in the definition we can add it yes, just link how href is being modified. I can't say when we can prioritize this, but if you do happen to add a PR we can get closer to getting it in.

**Comment by tricki** [comment] 2021-10-02 11:18
I created a pull request for adding `pathname`. Not sure if it's how you meant it @splitinfinities, if not just ping me.

Unfortunately Axios will still not work during prerender because `XMLHttpRequest` doesn't seem to be mocked, but at least the build won't break anymore (Before it broke even if you only imported Axios without calling any method).

In my case I replaced the Axios call with a `fetch` during prerender. Not ideal but it works.

```
if (Build.isServer) {
  fetch('...');
} else {
  Axios.get('...');
}

**Comment by tricki** [comment] 2021-11-09 15:24
Good catch. It might be related to https://github.com/axios/axios/issues/2731

**Comment by cptflammin** [comment] 2021-11-09 21:00
How could the rollup configuration be updated then ? Could the stencil team give a hand on this?

**Comment by tricki** [comment] 2021-12-04 15:08
I just did a quick test and found a way to work around this. It's not a real solution but might help someone else debug the issue.

**What I did:**
Based on [this comment](https://github.com/axios/axios/issues/2731#issuecomment-613290988) in [the axios issue I linked to before](https://github.com/axios/axios/issues/2731) I tried simply removing that line in `node_modules/axios/package.json`. This lead to a bunch of errors, including:

```
[ ERROR ]  Node Polyfills Required
           For the import "https" to be bundled from ./node_modules/axios/lib/adapters/http.js, ensure the
           "rollup-plugin-node-polyfills" plugin is installed and added to the stencil config plugins (client). Please
           see the bundling docs for more information. Further information: https://stenciljs.com/docs/module-bundling
```

So I installed and added `rollup-plugin-node-polyfills` and the issue was fixed.

**Comment by christian-bromann** [comment] 2024-06-13 20:21
Hi @cptflammin  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!

**Closed by christian-bromann** 2024-06-13 20:21 UTC
Labels: Good First Issue, Resolution: Needs Investigation
