### ISSUE TITLE
bug: Moving slot location in stencil component causes full browser crash in certain chromium versions

### ISSUE THREAD

**Issue by paulcpederson** [ionic-team/stencil#5881] opened 2024-07-03 20:42 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7.0 (but applies to other earlier versions as well)

### Current Behavior

When you use nested components with slots and modify the location of slotted content it causes a full crash in the latest chromium versions. 

I can't reproduce this in a non-stencil environment, so I believe it to be due to how stencil is rendering the virtual dom. 

### Expected Behavior

Moving the location of a slot should not crash the entire tab. 

### System Info

```shell
We've tested this on windows and Mac, with multiple chipsets

Windows 10, Dell Precision 7560

Chromium 126.0.6478.127
- Cannot reproduce by opening page and resizing it with Web accessibility mode off
- Can reproduce by opening page with Web accessibility mode on--it crashes immediately
- Can reproduce crash by opening dev tools and resizing the window (web accessibility not enabled)
- Can reproduce crash by opening Reading mode--It crashes immediately  (web accessibility not enabled)

Mac 
Chromium 126.0.6478.127 (Official Build)
- Can reproduce by opening page with Web accessibility mode on--it crashes immediately

Mac 2.6 GHz 6-Core Intel Core i7
Chromium 126.0.6478.126 (Official Build) (x86_64)
- Can reproduce by opening up devtools and docking them on the right side of the screen

```

### Steps to Reproduce

1. Go to https://668579e1ed432047b39b1054--earnest-dango-9fe07a.netlify.app/ On certain systems, this page will crash immediately. 
2. If the page does not crash, open devtools
3. If page has still not crashed, doc devtools on the right and resize the browser window
4. If page has still not crashed turn on reader mode

### Code Reproduction URL

https://github.com/paulcpederson/chromium-bug-repro

### Additional Information

If you can pinpoint a non-stencil (ie chromium) root cause for this, we can open an issue in chromium and ask for a fix.

**Comment by tanner-reits** [comment] 2024-07-08 18:06
Hey @paulcpederson, thanks for letting us know about this! I'm gonna close this as a duplicate of #5887 just because we've done some initial triage over there already, but we are aware of this and will look into it!

**Closed by tanner-reits** 2024-07-08 18:06 UTC
Labels: triage
