### ISSUE TITLE
Loop event handler is not changed when element is removed

### ISSUE THREAD

**Issue by derkoe** [ionic-team/stencil#478] opened 2018-02-04 20:19 UTC
**Stencil version:**
```
 @stencil/core@0.2.3
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Given I display an array of items in a loop (using map in tsx) and one element in the loop has an event handler. When I remove an item in the array (with filter actually creating a new array) the element is removed from the DOM but the event handler is still called with the removed item.

**Expected behavior:**
The event handler should be called with the current item.

**Steps to reproduce:**
There is a working app showing this here: https://derkoe.github.io/stencil-loop-event-bug/
1. Click on delete button next to "Three"
2. Click on delete button next to "Four" -> item 3 is still given as a parameter to the handler

**Related code:**

Code can be found here: https://github.com/derkoe/stencil-loop-event-bug

Relevant parts:

```tsx
  @State() items: Item[];

  render() {
    return (
      <ul>
        {this.items.map(item => this.renderItem(item))}
      </ul>
    );
  }

  renderItem(item: Item) {
    return (
      <li>
        {item.label}
        <button onClick={event => this.deleteItem(item)}>Delete</button>
      </li>
    );
  }

  deleteItem(itemToDelete: Item) {
    this.items = this.items.filter(item => item.id !== itemToDelete.id);
  }
```

**Other information:**

**Comment by adamdbradley** [comment] 2018-02-14 17:25
Looks like a duplicate of: https://github.com/ionic-team/stencil/issues/500 thanks

**Closed by adamdbradley** 2018-02-14 17:25 UTC

**Comment by derkoe** [comment] 2018-02-14 18:11
Yes that is fixed - thx.
Here you have a working TodoMVC: https://derkoe.github.io/stencil-todomvc/

**Comment by derkoe** [comment] 2018-02-14 18:12
And the fixed demo: https://derkoe.github.io/stencil-loop-event-bug/
