### ISSUE TITLE
relative app.js path not retained

### ISSUE THREAD

**Issue by FelschR** [ionic-team/stencil#358] opened 2017-12-11 10:18 UTC
**Stencil version:**
```
 @stencil/core@0.0.8-10
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When setting the app.js script tag with a relative path like this:
```html
<script lang="javascript" src="./build/app.js"></script>
```
the stencil build replaces this with the following:
```html
<script src="/build/app/app.qjnotlaf.js" data-path="/build/app/" data-namespace="app"></script>
```

**Expected behavior:**
The generated script tag should look retain the relative path like:
```html
<script src="./build/app/app.qjnotlaf.js" data-path="./build/app/" data-namespace="app"></script>
```

**Steps to reproduce:**
Clone the start project and run `stencil build --prerender`.
Start an html server, open the page and look at the script tag in the HTML head.

**Other information:**
While the removed "." doesn't cause any problems on a normal website it does in some special environments like an electron app where a non relative path causes an import from C:\ on Windows..

**Comment by FelschR** [comment] 2017-12-11 10:44
I just found the `publicPath` option in the stencil configuration which defaults to "/build".
In my case (using electron) setting it to "./build" resulted in 2 script tags (the normal app.js and the hashed app.xxx.js which also was an absolute path).
Then I tried setting the config to just "build" which works now. The script tags start with "build/*" and everything loads fine.

**Comment by jgw96** [comment] 2017-12-11 17:27
So just to follow up @FelschR , this was just a config issue? Maybe something we need to make more obvious in the docs?

**Comment by aarjithn** [comment] 2017-12-12 14:56
Just ran into this. Opened the index.html in www folder after build, and got the below error.

<img width="802" alt="screen shot 2017-12-12 at 8 14 17 pm" src="https://user-images.githubusercontent.com/10304259/33890486-66fe1c96-df79-11e7-82a9-7d66a5fe5ab1.png">

This is when www is not served from a webserver. Fixed it by removing / from /build/app in index.html. 
 
I believe the js path should be set to relative by default - `build/app/` or `./build/app/`. 
This can be useful when the app is hosted in a subdirectory - eg github pages where root folder is `username.github.io/projectname`.

**Comment by hufan-akari** [comment] 2017-12-13 08:32
I agree that the js path should be set to relative by default.
https://github.com/ionic-team/stencil-site/issues/100

**Comment by adamdbradley** [comment] 2017-12-20 15:28
Would you be able to try again with the latest release? I think this is fixed now, thanks.

**Comment by jgw96** [comment] 2017-12-27 16:09
Hello all! I just double checked and I cannot reproduce this issue in the latest release. Because of this, I am going to close this issue for now. Thanks!

**Closed by jgw96** 2017-12-27 16:09 UTC
Labels: needs reply

**Comment by FelschR** [comment] 2018-01-09 09:35
@adamdbradley @jgw96 
The default is still "/build" on 0.1.0.

I'm overriding it in the `stencil.config.js` with:
`publicPath: "build"`

It seems that when the configuration is not set it will always add a preceding "/":
https://github.com/ionic-team/stencil/blob/e53d297288db798b247a29958e1a8826959bf083/src/util/validate-config.ts#L117
