### ISSUE TITLE
starter app does not build.  Error in path-to-rexexp

### ISSUE THREAD

**Issue by bbellmyers** [ionic-team/stencil#360] opened 2017-12-11 20:22 UTC
**Stencil version:**
@stencil/starter@0.0.1 C:\Users\bbellmyers\repos\FlexProto\status-timeline-stencil
+-- @stencil/core@0.0.9-0
+-- @stencil/dev-server@0.0.17
+-- @stencil/router@0.0.17
+-- @stencil/utils@0.0.4

**I'm submitting a:**

- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Follow getting started directions.  Run "npm start", get a build error:

[20:16.2]  bundle modules finished in 561 ms

[ ERROR ]  bundling: ...imeline-stencil\node_modules\@stencil\router\dist\collection\utils\match-path.js, line: 1
           'default' is not exported by
           D:\repos\FlexProto\status-timeline-stencil\node_modules\@stencil\router\node_modules\path-to-regexp\index.js

      L1:  import pathToRegexp from 'path-to-regexp';
      L2:  import { MatchOptions, MatchResults } from '../global/interfaces';

[20:16.3]  build failed, watching for changes... in 4.95 s

**Expected behavior:**
Starter app should build without errors

**Steps to reproduce:**
git clone https://github.com/ionic-team/stencil-app-starter my-app
cd my-app
git remote rm origin
npm install

**Comment by bbellmyers** [comment] 2017-12-11 22:19
More info.  I tried the same steps in git bash shell, and it worked.  So this appears to have something to do with running in a cygwin shell

**Comment by jgw96** [comment] 2017-12-27 16:10
Hey @bbellmyers are you still getting this issue? I was not able to reproduce this in either powershell, Hyper or ubuntu for windows 10 on my surface book.

**Comment by jgw96** [comment] 2018-01-04 19:59
Hello all! As it has been a while since there was any activity on this issue, I am going to close this issue for now. Thanks!

**Closed by jgw96** 2018-01-04 19:59 UTC
Labels: needs reply
