### ISSUE TITLE
IE11: Unable to get property 'cloneNode' of undefined or null reference

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#302] opened 2017-11-13 20:14 UTC
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
-- @stencil/core@0.0.8-0
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Console error in IE11: 
**"Unable to get property 'cloneNode' of undefined or null reference 8 MY-COMPONENT"**

This seems to be related to the template polyfill. It may have not been applied or does not provide a `content` property. 
https://github.com/ionic-team/stencil/blob/1904e75dbf404c7507f4e0783975e914cd0ef856/src/client/platform-client.ts#L289

No SASS styling applied.

**Expected behavior:**
Error free with styling applied.

**Steps to reproduce:**

1. Clone `stencil-component-starter`
2. Run `npm i`
3. Open the `my-component.scss` file and add some styling
4. Open page in IE11

**Related code:**
```css
:host { 
  display: block; 
  background-color: red; 
}
```

**Other information:**

I apologize for submitting IE11 issues.... I really do.

P.S. - `Array.prototype.find` is not transpiled/polyfilled for IE11 either. When used in 

https://github.com/ionic-team/stencil/blob/1904e75dbf404c7507f4e0783975e914cd0ef856/src/core/instance/proxy.ts#L174

...IE also fails miserably (man I wish there was an emote for "IE fails again")

**Comment by adamdbradley** [comment] 2017-11-13 20:26
Ha, never apologize for submitting IE11 issues, thanks for submitting them! I'll add the Array `find` polyfill and we'll look into the template issue. thanks!

**Comment by adamdbradley** [comment] 2017-11-13 20:48
https://github.com/ionic-team/stencil/commit/cd3911ae96d35e2909486be97125c368f151caaa

**Comment by jgw96** [comment] 2017-11-15 16:00
@cary-smith Hey! In the latest release I am not able to reproduce this anymore on my Surface Book running IE11. Because of this I am going to close this issue for now, but feel free to open a new issue if you see it again.

**Closed by jgw96** 2017-11-15 16:00 UTC

**Comment by cary-smith** [comment] 2017-11-15 16:13
Definitely no longer getting those issues. Thanks!

**Comment by cary-smith** [comment] 2017-11-15 16:39
Correction. 

Wiped the node_modules folder, started fresh using `"@stencil/core": "next"` and unfortunately I am still seeing the issue.

IE11 version: 11.674.15063.0

**Comment by cary-smith** [comment] 2017-11-15 20:41
Out of curiosity, is `'template.js'` supposed to be included in [this block of code](https://github.com/ionic-team/stencil/blob/6fb436ab4c3ed70cc4c8c54279ad0267d68d08d0/src/compiler/app/app-core.ts#L78)?

**Comment by adamdbradley** [comment] 2017-11-15 21:27
@cary-smith Ahh, good catch! Yeah must have been a bad merge, thanks for finding that!

**Comment by cary-smith** [comment] 2017-11-15 21:31
Thanks for the awesome library!
