### ISSUE TITLE
E2E: multiple piercing selectors ">>>" don't work

### ISSUE THREAD

**Issue by kraftwer1** [ionic-team/stencil#1530] opened 2019-05-15 12:31 UTC
**Stencil version:**

```
 @stencil/core@0.18.1
```

**I'm submitting a:**

[x] bug report

**Current behavior:**
Does not work, even though the DOM tree exists:
    
    await page.find('my-component >>> my-second-component >>> div');

**Expected behavior:**
It would be nice if n piercing selectors could be used.

**Steps to reproduce:**
Put a Stencil component into another Stencil component and try to access this using the piercing selector.

**Comment by cthos** [comment] 2019-07-30 20:28
This is a deeper problem in Puppeteer - and this is their advise:
https://github.com/GoogleChrome/puppeteer/issues/858#issuecomment-438540596

I don't personally like this solution too much, I'd rather be able to string together find statements to pierce the shadow root further.

**Comment by adamdbradley** [comment] 2020-01-15 00:36
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-15 00:36 UTC
Labels: triage

**Comment by jevenson** [comment] 2020-03-02 17:23
I'm not seeing this issue fixed in the latest version of Stencil. According to this code:
https://github.com/ionic-team/stencil/blob/master/src/testing/puppeteer/puppeteer-find.ts#L156

`getSelector`, when provided `my-component >>> my-second-component >>> div` will return
```js
{
    lightSelector: "my-component",
    shadowSelector: "my-second-component",
    text: null,
    contains: null
}
```

I can put together a reproduction repository later, but I think that the issue has not been fixed based on this function.

**Comment by MrAntix** [comment] 2022-12-01 15:05
This is not working as described in v2.19.3

**Comment by wavebeem** [comment] 2024-01-26 23:46
This is still not working in `@stencil/core 4.10.0`

**Comment by wavebeem** [comment] 2024-01-27 00:59
Wait, maybe this is being processed recursively. I think I may have misunderstood how selectors are meant to work with regard to shadow DOM. I believe the light DOM content should be queried directly, not through the slot

e.g.

```html
<x-foo>
  <x-bar>
    <div class="hello">
  </x-bar>
</x-foo>
```

If you have something like this where `x-foo` and `x-bar` use shadow DOM, it doesn't make sense to query `x-foo >>> x-bar >>> .hello`, you should query `x-foo .hello`. Even though the `.hello` element is shown in a `<slot>` inside `x-bar`, as far as the DOM is concerned it's a child of `x-foo` and in the light DOM not the shadow DOM.

**Comment by christian-bromann** [comment] 2024-03-13 00:26
@wavebeem Hey 👋  I am happy to look into this issue with you. Mind providing a little reproducible example? Keep in mind that queries like this `my-component >>> my-second-component >>> div` aren't possible due to limitations how this selector works. I recommend in this case to separate the query in two commands, e.g.:

```ts
const elem = await page.find('my-component >>> my-second-component');
const myElem = await elem.find('>>> div')
```

**Comment by wavebeem** [comment] 2024-03-13 01:12
@christian-bromann I swear I was able to get selectors with multiple `>>>` to work eventually... but maybe the tests are just poorly written that I was looking at.

I eventually figured out what I was doing wrong. I tried to document it above. If anyone else wants a bit more detail, I also wrote a blog post about it

https://www.wavebeem.com/blog/2024/01/27/querying-shadow-dom/

**Comment by christian-bromann** [comment] 2024-03-13 01:48
That's awesome, thanks for sharing!
