### ISSUE TITLE
Configuration: Copy Tasks are not executed for dev builds with target 'dist'

### ISSUE THREAD

**Issue by joelricci** [ionic-team/stencil#2499] opened 2020-06-09 16:06 UTC
**Stencil version:**
```
@stencil/core@1.14.0 
```

**I'm submitting a:**
[x] bug report

**Current behavior:**
Copy Tasks (outputTargets) are not run for development builds with target 'dist'.

**Expected behavior:**
Copy Tasks should be executed for development builds with target 'dist'. If this is not the intended behaviour, it should be clearly documented under `copy-tasks`. 

**Steps to reproduce:**

1. Create a `stencil.config.ts` similar to this:
```
export const config: Config = {
    outputTargets: [{
        type: 'dist',  // make sure target is set to 'dist'
        copy: [{ src: '../somefile.json' }],
    }],
    ...
};
```
2. Make a 'full' build:
```
npx stencil build
```
Check the `dist/` folder for `somefile.json` - it's there.
Note that the file is being copied according to the build log!

3. Now run a development build:
```
npx stencil build --dev
```
Check the `dist/` folder again - the file is gone!
Note that the file is **not** being copied according to the build log!

**Other information:**
Doesn't seem to affect `www` targets, only `dist` ?

I believe this behaviour has changed a while back and is probably related to this code which seems to silently return before executing the copy tasks.

https://github.com/ionic-team/stencil/blob/65006a1c0484c7048b30e26814cddc73cfc8afba/src/compiler/build/build.ts#L37

**Comment by joelricci** [comment] 2020-06-18 08:17
The above mentioned changes were part of the v1.11.0 release on March 20. I have verified that the problem does **not** exist in v1.10.3.

**Comment by nedredmond** [comment] 2020-06-24 13:02
I can confirm that this issue exists in v1.11.3 and v1.14.0 as well.

**Comment by joelricci** [comment] 2020-06-24 13:50
> I can confirm that this issue still exists in v1.11.3 and v1.14.0 as well for the `dist` output target. `www` copies just fine.

This is my experience as well.

Updated **Other information:**
> Doesn't seem to affect www targets, only dist ?

**Comment by Jagget** [comment] 2020-06-25 16:55
On 1.14 `dist` copy task works fine. The trick in the relativity of the folders
```copy: [{src: 'assets', dest: '../mylib/assets'}],```
This will copy `/src/assets` into `/dist/mylib/assets`. So for `dist` task try to use `dest` setting

**Comment by joelricci** [comment] 2020-07-07 12:34
> I can confirm that this issue still exists in v1.11.3 and v1.14.0 as well for the `dist` output target. `www` copies just fine.

@nedredmond : Just out of curiosity, do you copy anything from above the "current working directory" level? 

I.e: `copy: [{ src: '../foo.bar' }]`

**Comment by pranav-js** [comment] 2022-01-03 10:33
ah I am facing this too. angularOutputTarget folder not generated for dev mode either strange

**Comment by squeral** [comment] 2022-05-13 10:48
> On 1.14 `dist` copy task works fine. The trick in the relativity of the folders `copy: [{src: 'assets', dest: '../mylib/assets'}],` This will copy `/src/assets` into `/dist/mylib/assets`. So for `dist` task try to use `dest` setting

Thank you @Jagget. This was the issue for me.

**Comment by christian-bromann** [comment] 2024-06-13 20:07
Hi @joelricci  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!

**Closed by christian-bromann** 2024-06-13 20:07 UTC
Labels: triage
