### ISSUE TITLE
bug:  hydratedFlag is not reflected in dist-custom-elements build

### ISSUE THREAD

**Issue by krivaten** [ionic-team/stencil#4297] opened 2023-04-21 18:06 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

3.2.1

### Current Behavior

In my `stencil.config.ts`, I have defined the following:

```
hydratedFlag: {
    selector: 'attribute',
    name: 'stencil-hydrated'
},
```

This works as expected in the standard `dist` build (i.e., it adds an attribute called `stencil-hydrated` to every component upon hydration). However, when using the `dist-custom-elements` build, it does not add this attribute.

### Expected Behavior

If a `hydratedFlag` is present in the `stencil.config.ts` file, it should be reflected in the `dist-custom-elements` build. In my case, by adding the `stencil-hydrated` attribute on hydrated components.

### System Info

```shell
System: node 18.12.1
Platform: darwin (21.6.0)
CPU Model: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 cpus)
Compiler: /Users/kvanhouten/Documents/Code/work/stencil-hydrated-flag-bug/node_modules/@stencil/core/compiler/stencil.js
Build: 1681148889
Stencil: 3.2.1 🎙
TypeScript: 4.9.5
Rollup: 2.42.3
Parse5: 7.1.2
Sizzle: 2.42.3
Terser: 5.16.8

---

Browser: Brave version 1.48.158
NPM: 8.19.2
```

### Steps to Reproduce

I have created a repository that easily reproduces the issue:

1. `git clone git@github.com:krivaten/stencil-hydrated-flag-bug.git`
2. Run `yarn`
3. Run `yarn demo`
4. Navigate to http://localhost:8000/
5. Notice the lack of the `stencil-hydrated` attribute on the `<my-component>` element.that

### Code Reproduction URL

https://github.com/krivaten/stencil-hydrated-flag-bug

### Additional Information

This is similar to the issue reported in #3606 with the `dist-hydrate-script`.

If you can help point me in a direction, I can try to open a PR to address the change.

**Comment by tanner-reits** [comment] 2023-04-24 15:46
Closing as a duplicate of #3437

**Closed by tanner-reits** 2023-04-24 15:46 UTC
Labels: triage
