### ISSUE TITLE
Issue when adding component to a disconnected document fragment

### ISSUE THREAD

**Issue by brandonseydel** [ionic-team/stencil#2417] opened 2020-05-06 01:57 UTC
**Stencil version:**

```
 @stencil/core@1.12.7
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

The component renders without getting styled.

**Expected behavior:**

Component is styled appropriately

**Steps to reproduce:**

Create a document fragment in code.
Add the web component to the frag.
Add the fragment to the DOM.

**Related code:**

```html
<html>
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <ion-chip color="success" id="chip">chip</ion-chip>
    <script
      type="module"
      src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"
    ></script>
    <script
      nomodule
      src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"
    ></script>
    <script>
      setTimeout(() => {
        const template = document.createElement("template");
        const chip = document.getElementById("chip");
        template.content.appendChild(chip);
        document.body.appendChild(chip);
      }, 500);
    </script>
  </body>
</html>
```

**Other information:**

**Comment by brandonseydel** [comment] 2020-05-11 16:04
any thoughts?

**Comment by tricki** [comment] 2020-06-03 14:36
Seems the problem is with using a `template`, if you add it to a `document.createDocumentFragment()` it works correctly.

**Comment by brandonseydel** [comment] 2020-06-03 15:52
@tricki is there anyway you can fix the underlying issue?

**Comment by tricki** [comment] 2020-06-03 16:33
I'm afraid not, I don't have any idea what it might be. But do you actually need a `template` element or could you use something else? What are you trying to achieve?

**Comment by brandonseydel** [comment] 2020-08-10 15:41
FYI - https://bugs.chromium.org/p/chromium/issues/detail?id=1111864#c2

**Comment by brandonseydel** [comment] 2020-08-20 04:10
Looks like the chromium team put this ball back in your court.  Msft fast has a noted issue as well with thoughts on how to solve.

**Comment by rwaskiewicz** [comment] 2023-11-28 14:16
👋 

I apologize it took so long for someone on the team to acknowledge this issue. Per [this comment in the Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1111864#c25), this was fixed in Chrome v88.  I pulled down the reproduction case, and it appears that the `ion-chip` is correctly styled on:
- Chrome 119.0.6045.159 (Official Build) (arm64)
- Microsoft Edge Version 119.0.2151.72 (Official build) (arm64)

For good measure, I also tested/verified the styling on: 
- Firefox 119.0.1 (64-bit)
- Safari Version 17.1 (19616.2.9.11.7)

As a result, I'm going to close this out. Please feel free to open a new issue should this bug reappear!

**Closed by rwaskiewicz** 2023-11-28 14:16 UTC
Labels: triage
