### ISSUE TITLE
Elements querySelector'ed otherwise than by their name are not recognized by the compiler

### ISSUE THREAD

**Issue by kael** [ionic-team/stencil#614] opened 2018-03-09 09:14 UTC
**Stencil version:**

```
    "@ionic/core": "0.0.2-65",
    "@stencil/core": "0.6.1",
```

**I'm submitting a:**

[x] bug report
[ ] feature request

**Current behavior:**

When accessing an element by id or class (alone or combined), the element is not recognized by the compiler:

```tsx
/* OK */
document.querySelector('slides').slideTo(1);

/* Property 'slideTo' does not exist on type 'Element'. */
document.querySelector('ion-slides#slide-id').slideTo(index);
document.querySelector('.ion-slides-nav').slideTo(index);
document.querySelector('ion-slides.ion-slides-nav').slideTo(index);
document.querySelector('ion-slides').querySelector('.ion-slides-nav').slideTo(index);
```

**Comment by jgw96** [comment] 2018-03-14 14:56
Hey! Unfortunately, I am not able to reproduce this issue. Mind posting a repo we could use to reproduce this?

**Comment by jgw96** [comment] 2018-03-29 17:27
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Stencil!

**Closed by jgw96** 2018-03-29 17:27 UTC
Labels: needs reply
