### ISSUE TITLE
bug: child input element is receiving un-wanted props

### ISSUE THREAD

**Issue by mad-raccoon** [ionic-team/stencil#5707] opened 2024-04-26 11:36 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.17.1

### Current Behavior

Whenever the user interacts with an input element inside the component, that input element inherits un-wanted props from the stencil component element.

I am using the component like this:

`<my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>`

That is defined like this:

<img width="522" alt="image" src="https://github.com/ionic-team/stencil/assets/57071299/c6316c00-b06b-4ec4-a764-2dd79e777185">

### Problem

Whenever I interact with the input, the props `first="Stencil" last="'Don't call me a framework' JS"` are getting passed to the input element:

<img width="600" alt="image" src="https://github.com/ionic-team/stencil/assets/57071299/2cb7e400-2d94-4973-906b-ad124f33b91e">

Here is a sandbox with the issue: [Sandbox](https://codesandbox.io/p/devbox/crimson-breeze-kd5g4r?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvgkimok00073b6q5znuvqxq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvgkimok00023b6qijh57yjk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvgkimok00043b6qlai19bph%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvgkimok00063b6q2q3c8qal%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B90%252C10%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvgkimok00023b6qijh57yjk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00013b6qsidebo4f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvgkkeu0004p3b6q3g1x4td5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252Fmy-component%252Fmy-component.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvgl748i00023b6j2dan8n71%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00023b6qijh57yjk%2522%252C%2522activeTabId%2522%253A%2522clvgl748i00023b6j2dan8n71%2522%257D%252C%2522clvgkimok00063b6q2q3c8qal%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00053b6qdbz3vikl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3333%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00063b6q2q3c8qal%2522%252C%2522activeTabId%2522%253A%2522clvgkimok00053b6qdbz3vikl%2522%257D%252C%2522clvgkimok00043b6qlai19bph%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00033b6q5qm0s7xt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00043b6qlai19bph%2522%252C%2522activeTabId%2522%253A%2522clvgkimok00033b6q5qm0s7xt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A28.908701854493586%257D)

### Expected Behavior

Not pass the properties to the input element

### Steps to Reproduce

Click on the input element.

### Code Reproduction URL

https://codesandbox.io/p/devbox/crimson-breeze-kd5g4r?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvgkimok00073b6q5znuvqxq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvgkimok00023b6qijh57yjk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvgkimok00043b6qlai19bph%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvgkimok00063b6q2q3c8qal%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B90%252C10%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvgkimok00023b6qijh57yjk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00013b6qsidebo4f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvgkkeu0004p3b6q3g1x4td5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252Fmy-component%252Fmy-component.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvgl748i00023b6j2dan8n71%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00023b6qijh57yjk%2522%252C%2522activeTabId%2522%253A%2522clvgl748i00023b6j2dan8n71%2522%257D%252C%2522clvgkimok00063b6q2q3c8qal%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00053b6qdbz3vikl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3333%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00063b6q2q3c8qal%2522%252C%2522activeTabId%2522%253A%2522clvgkimok00053b6qdbz3vikl%2522%257D%252C%2522clvgkimok00043b6qlai19bph%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgkimok00033b6q5qm0s7xt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clvgkimok00043b6qlai19bph%2522%252C%2522activeTabId%2522%253A%2522clvgkimok00033b6q5qm0s7xt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A28.908701854493586%257D

**Comment by tanner-reits** [comment] 2024-04-26 14:16
@mad-raccoon I wasn't able to reproduce what you're describing either locally or in the provided sandbox. Are there specific steps that cause this behavior?

**Comment by mad-raccoon** [comment] 2024-04-28 17:56
@tanner-reits I updated the sandbox.

Here is a screen recording of the behavior I described. Notice that at the beginning the input element has no props, and after I click on it, it gets the properties `first` and `last`


https://github.com/ionic-team/stencil/assets/57071299/5aa048bf-d3dc-4da8-955d-6360f16a2726

**Comment by mad-raccoon** [comment] 2024-04-29 09:57
@tanner-reits after some investigation, i discovered that this only happens with google chrome

**Comment by tanner-reits** [comment] 2024-05-02 15:18
@mad-raccoon Yeah I'm not able to get that to happen on my end. Looks like you have chrome update in the video you sent, does it still happen if you update to the latest version?

**Comment by tanner-reits** [comment] 2024-05-06 20:36
@mad-raccoon Both myself and @rwaskiewicz are unable to reproduce this issue. Do you have any browser extensions installed that might be playing a role? I'm on the same Chrome version you reported, so, it seems this is an issue specific to your machine.

**Comment by mad-raccoon** [comment] 2024-05-06 21:28
@tanner-reits how are you trying to replicate this issue? Local or via the playground I shared ?

Also, are you using Mac or Windows ? I am on Mac

**Comment by tanner-reits** [comment] 2024-05-07 14:12
@mad-raccoon I'm on a mac. I've tried to reproduce both locally and in the playground.

**Comment by christian-bromann** [comment] 2024-05-07 15:23
@mad-raccoon maybe one way to create a reproducible example is to adjust Stencils [e2e tests](https://github.com/ionic-team/stencil/blob/b3886aa928c1025e636aee1466f26f15fc4dd3eb/test/end-to-end) and make them fail based on your observations. Please raise a PR for this and we can take a look.

**Comment by mhoritani** [comment] 2024-05-11 11:53
Hi @mad-raccoon! This might be a long shot, but is there a chance you are using LastPass, specifically its browser extension? We recently had a similar case and found that this extension happens to do exactly that causing issues with our components.

You could try to see if this still happens using Chrome's Incognito mode where extensions are disabled.

**Comment by mad-raccoon** [comment] 2024-06-03 15:42
hey @mhoritani. sorry for the late reply...  i can confirm . this is related to LastPass extension.

Do you have any workaround to avoid this ? I created a function that cleans the extra props, but it has some flaws.

**Comment by christian-bromann** [comment] 2024-06-24 18:10
I will go ahead and close this since this doesn't seem to be related to Stencil directly. Thanks you @mhoritani for this excellent guess 🎉

**Closed by christian-bromann** 2024-06-24 18:10 UTC
Labels: ionitron: needs reproduction

**Comment by mad-raccoon** [comment] 2024-06-26 08:01
@christian-bromann @mhoritani 

is there any workaround to avoid this behavior with lastpass ?
