### ISSUE TITLE
bug: ignores tailwind plugin styles (daisyui)

### ISSUE THREAD

**Issue by 7flash** [ionic-team/stencil#3410] opened 2022-06-07 10:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0

### Current Behavior

![image](https://user-images.githubusercontent.com/4569866/172355592-93e79314-3744-4852-8142-0fa6ff8b17e7.png)

Currently TailwindCSS styles are applied.. but daisy plugin styles are ignored..

### Expected Behavior

![image](https://user-images.githubusercontent.com/4569866/172356530-7c835cb4-3358-437d-af24-0b8e1ba11976.png)

Expected DaisyUI styles are applied and page looks like that

### Steps to Reproduce

[gitpod](https://gitpod.io/#https://github.com/7flash/stencil-one)

### Code Reproduction URL

https://github.com/7flash/stencil-one

### Additional Information

https://github.com/saadeghi/daisyui/issues/840

**Comment by rwaskiewicz** [comment] 2022-06-07 12:51
Hey @7flash 👋 

At this time, Stencil does not officially support Tailwind (and as a result, DaisyUI).  

There is a community driven project, [stencil-tailwind-plugin](https://www.npmjs.com/package/stencil-tailwind-plugin), that may be of interest to you if you have not had the opportunity to take a look at it.

It may be possible to get it to work with the `@stencil/postcss` plugin (although I can't guarantee it will work).  However, in order to see if there's a bug in `@stencil/postcss`, can you please do me a favor and try to remove as much as possible from the `plugins` section of the `stencil.config.ts` in your reproduction as possible? This will help us investigate further by eliminating any potential conflicts/side effects that other plugins may be introducing.
```typescript
  plugins: [
    postcss({
      plugins: [
        require("postcss-import"),
        require("tailwindcss")("./tailwind.config.js"),
        autoprefixer(),
        ...(process.env.NODE_ENV === "production" ? [purgecss, require("cssnano")] : [])
      ],
    })
  ],
```

**Comment by 7flash** [comment] 2022-06-07 14:27
Would be a dream combo because couldn't find any other way of HMR for tailwind with Vanilla JS.. Also seems like possibility to completely separate representation layer with Stencil from Application Logic in Vanilla/React..

**Comment by rwaskiewicz** [comment] 2022-06-07 21:21
> What are the steps I can make to debug.. My hopes there is a way to figure out.. would be a dream combo..

Since the Stencil team/Ionic didn't create this tutorial, we don't know the exact conditions in which it worked. If you can get this demo to  a workable state by changing the version numbers of the dependencies, that might be a good start. I don't see a github repo in the Medium article or any mention of specific versions in the article (if I missed those, those would be the ones to use). Without either of those, the best bet would be to look up what the latest of each dependency was when the article was published as a first attempt.

From there, once everything is working I'd save that as a commit in git. Then, I'd try to remove as many of those plugins as possible to create the smallest reproduction case as possible.  Our goal here would be to determine if there's a bug in Stencil or the PostCSS plugin, and minimizing the number of influencing libraries here is our best bet.

**Comment by 7flash** [comment] 2022-06-07 23:08
> > What are the steps I can make to debug.. My hopes there is a way to figure out.. would be a dream combo..
> 
> Since the Stencil team/Ionic didn't create this tutorial, we don't know the exact conditions in which it worked. If you can get this demo to a workable state by changing the version numbers of the dependencies, that might be a good start. I don't see a github repo in the Medium article or any mention of specific versions in the article (if I missed those, those would be the ones to use). Without either of those, the best bet would be to look up what the latest of each dependency was when the article was published as a first attempt.
> 
> From there, once everything is working I'd save that as a commit in git. Then, I'd try to remove as many of those plugins as possible to create the smallest reproduction case as possible. Our goal here would be to determine if there's a bug in Stencil or the PostCSS plugin, and minimizing the number of influencing libraries here is our best bet.

I used tutorial as example but installed all fresh dependencies..

autoprefixer plugin always goes together with tailwind..

purgecss and cssnano are ignored here since I setup env==dev above in file..

**Comment by rwaskiewicz** [comment] 2022-06-08 12:18
> I used tutorial as example but installed all fresh dependencies..

Depending on how we interpret the word 'fresh' might be important here. It is possible that in newer versions of dependencies, there was a breaking change (accidental or not), which is why I had suggested trying to find what the newest version of the dependency was when the blog was written and install those versions as a first step.

 > purgecss and cssnano are ignored here since I setup env==dev above in file..

Perfect! That means we can remove them from the minimal reproduction case to make it more minimal 🙂

**Comment by rwaskiewicz** [comment] 2022-06-22 17:58
I'm going to close this issue due to lack of reproduction case.  If this is still an issue, please feel free to create a new issue with a more minimal reproduction URL for the team to pull down and take a look at.  Thanks!

**Closed by rwaskiewicz** 2022-06-22 17:58 UTC
Labels: ionitron: needs reproduction
