### ISSUE TITLE
Error setting "shadow" property of @Component from CONST

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil#458] opened 2018-01-30 14:11 UTC
Hey, digger deeper into Stencil - great work guys!

**Stencil version:**
```
└── @stencil/core@0.2.3
```

**I'm submitting a:**

- [ x ] bug report

**Current behavior:**
When trying to set the ```shadow```property of the ```@Component```decorator from a imported const I get this error:

```terminal
[ ERROR ]  ReferenceError: GLOBAL_SETTINGS is not defined at eval (eval at evalText
           (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:12785:12),
           <anonymous>:5:11) at evalText (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:12785:31) at
           decorator.expression.arguments.map (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:12792:16) at Array.map
           (<anonymous>) at getDeclarationParameters (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:12791:43) at
           getComponentDecoratorMeta (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:12835:32) at visitClass
           (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:13343:19) at visit
           (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:13331:29) at
           ts.forEachChild (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/@stencil/core/dist/compiler/index.js:13323:13) at visitNodes
           (/Users/matthias/Documents/Projekte/bitflower/Case
           OS/Prototype/v0.2/caseos-ui-kit/node_modules/typescript/lib/typescript.js:12699:30)

[02:16.4]  rebuild failed, watching for changes... in 350 ms
```

**Related code:**

This is my code (combined from many TS-files):

´´´tsx
export interface IGlobalSettings {
  useShadowDOM: boolean;
}

import { IGlobalSettings } from "../interfaces/IGlobalSettings";
export const GLOBAL_SETTINGS: IGlobalSettings = {
  useShadowDOM: true
};

import { GLOBAL_SETTINGS, NLS_ENGLISH } from "../../config";
@Component({
  tag: "co-textbox",
  styleUrl: "co-textbox.scss",
  shadow: GLOBAL_SETTINGS.useShadowDOM
}) 

```

**Comment by jgw96** [comment] 2018-01-30 20:36
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/ionic-team/stencil/issues/398. Thanks for using Stencil!

**Closed by jgw96** 2018-01-30 20:36 UTC

**Comment by bitflower** [comment] 2018-01-31 06:16
ok! Sorry for not checking....
