### ISSUE TITLE
1.0.0-alpha.8 shadow:false not producing proper dom tree

### ISSUE THREAD

**Issue by s-tyler-smith** [ionic-team/stencil#1454] opened 2019-04-11 17:39 UTC
**Stencil version:**

```
 @stencil/core@1.0.0-alpha.8
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When ```shadow: false``` the slotted content renders at root of stencil component instead of in proper location as dictated by ```<slot/>```
**Expected behavior:**

When ```shadow: false``` the slot should render in proper position inside the component as dictated by ```<slot/>```
**Steps to reproduce:**

1) npm init stencil - choose component starter app
2) add shadow: false and tsx with slot
3) npm start  - confirmed working 
4) Upgrade to alpha: npm install @stencil/core@one --save-dev
5) Add import h to my-component.tsx, keep shadow: false, and update src/index.html to include .mjs file.
6) npm start 
**Related code:**
```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: false
})
export class MyComponent {
  render() {
    return (<div><slot/></div>);
  }
}
```
Inside html
```html
<my-component>
    <div>Inside</div>
 </my-component>
```
Expected generated html:
```html
<my-component class="hydrated">
  <div>
      <div>Inside</div>
   </div>
</my-component>
```
Actual generated html:
```html
<my-component class="hydrated">
  <div>Inside</div>
  <div>
    <slot></slot>
  </div>
</my-component>
```
**Other information:**
This feature works within ```@stencil/core@latest``` but not the alpha

**Comment by nilssonja** [comment] 2019-04-11 19:37
Can confirm I am seeing the same thing when setting `shadow: false`. Seems to happen regardless if I am passing in text or an element as described in the issue.

**Comment by kevinmpowell** [comment] 2019-04-26 12:25
@manucorporat @adamdbradley or @jthoms1 any update on this one? We're developing against `0.x.x` until this is resolved.

**Comment by romulocintra** [comment] 2019-05-15 07:26
Same here !!!

**Comment by kevinmpowell** [comment] 2019-05-22 13:29
@manucorporat any update on this? Has this been fixed in the latest Beta release?

**Comment by s-tyler-smith** [comment] 2019-05-22 14:07
@kevinmpowell @romulocintra @mlynch @nilssonja @manucorporat this seems to be resolved in beta

**Comment by maltemuth** [comment] 2019-09-13 10:19
The issue persists in 1.3.2

**Comment by maltemuth** [comment] 2019-09-19 07:16
To be more precise: The pre-rendered HTML is fine, but after loading JS files, the DOM gets mangled as described here.

**Comment by pfecht** [comment] 2019-09-26 14:48
I think we could have a similar issue. Changing the value of a default slot (`<slot></slot>`) renders the new element as having only the new slot's value as child (entirely neglects the actual rendering logic). Works fine with `shadow:true`.

**Comment by patrickalima98** [comment] 2019-11-23 19:16
The issue persists in 1.8.1 and 1.8.2

**Comment by kodmunki** [comment] 2019-12-10 15:05
Is anyone working on this issue? Any insights as to where in the code they think might be the root cause? -- I will start looking, but thought that maybe others have some thoughts they might share so as to not start from ground zero.

**Comment by juanmiguelbesada** [comment] 2020-01-15 06:41
I can't reproduce this issue anymore in 1.8.4

**Comment by manucorporat** [comment] 2020-05-06 17:06
Seems like we fixed this issue, if there are other problems, please feel free to open a new issue!

**Closed** 2020-05-06 17:05 UTC
Labels: triage
