### ISSUE TITLE
Discussion: Including assets with component library and consuming them when used in application

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/stencil#1543] opened 2019-05-17 21:02 UTC
**Stencil version:**
Testing was performed with both 1.0.0-beta.1 and with 

**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
This comes out of some investigation that Josh and I were doing this morning.

Currently, you can use the copy command to copy the asset files to your `dist` folder where it is put under the `collection`, something like this:

```
  copy: [
    { src: 'assets' }
  ],
```

There are also mechanisms to get either the `publicPath` (in 0.18.1) or the URL for an asset (in 1.0.0-beta.1), but that does not seem to translate well to the case where you are building a component library that will then be used in other applications.

The missing piece is how to get those assets to the correct and expected location in the build of the consuming application.

**Expected behavior:**
We need one of the following:

A better mechanism for embedding PNG files and such in a component library such that they can be used within the components in the library and easily included in the build process of the consuming application.

OR

A documented strategy on how to best accomplish this if tooling cannot be reasonably put in place to handle it in a more automatic fashion.

**Other information:**
What I have been doing in my own applications is that the application owns the assets and then a path mapping is bound to the components so they know where to find the assets. This works ok, and solves the problem of different applications potentially putting the assets in different locations in the build.

But, I would really like to have my images be part of the component library and not have to have the consuming application concerned with them at all (ideally) since my component library display's weather conditions and can use a standard set of images.

In the design systems case, we will have situations where customers would want to embed logos, specialized fonts, etc. in their components and not have to have the consuming applications worry about it.

**Comment by Snapu** [comment] 2019-08-22 09:42
I picked up stencil because I wanted to build microfrontends and it seemed like stencil is the best tool for building native web components. If I cannot integrate my component anywhere else IMHO you cannot call it a 'A Web Component compiler for building fast, reusable UI components'...

I hope this issue finds more attention than the other related issues that are already closed.

**Comment by josros** [comment] 2019-09-13 14:52
+1

**Comment by AnonymousArthur** [comment] 2019-10-22 06:35
+1
I'm facing the same issue. My current solution is to embed images by using base64 encoding and save them into js files. The outcome is obvious that goal is achieved but we can't take advantage of CDN or any other caching mechanism.

**Comment by splitinfinities** [comment] 2021-08-10 19:47
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

This is a duplicate of #1868

**Closed by splitinfinities** 2021-08-10 19:47 UTC
Labels: triage
