### ISSUE TITLE
Windows Path Issues StencilJS

### ISSUE THREAD

**Issue by schempp** [ionic-team/stencil#344] opened 2017-12-04 04:38 UTC
**Stencil version:**

```
 @stencil/core@<version>
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Compiler mixes up path and breaks when importing local file.ts...
for example the components.ts refers to the files with a mixed (from './components\app-home\app-home';)
**Expected behavior:**

Using stenciljs on Linux Ubuntu this works with no problem.
**Steps to reproduce:**

 Windows 10
create typescript module
import module into my-component
... this will reproduce the error...

**Related code:**
```tsx
from './components\app-home\app-home';


[ ERROR ]  typescript: D:/Workspace/git/spa-proj2/src/components.d.ts, line: 15
          Cannot find module './componentsapp-homeapp-home'.

     L14:  var HTMLAppHomeElement: {
     L15:    prototype: HTMLAppHomeElement;
     L16:    new (): HTMLAppHomeElement;

[ ERROR ]  typescript: D:/Workspace/git/spa-proj2/src/components.d.ts, line: 45
          Cannot find module './componentsapp-profileapp-profile'.

     L44:  var HTMLAppProfileElement: {
     L45:    prototype: HTMLAppProfileElement;
     L46:    new (): HTMLAppProfileElement;

[ ERROR ]  typescript: D:/Workspace/git/spa-proj2/src/components.d.ts, line: 75
          Cannot find module './componentsmy-appmy-app'.

     L74:  var HTMLMyAppElement: {
     L75:    prototype: HTMLMyAppElement;
     L76:    new (): HTMLMyAppElement;
```

**Other information:**

**Comment by cantsdmr** [comment] 2017-12-04 12:31
mentioned before in #341

**Comment by jgw96** [comment] 2017-12-04 16:29
So just to be clear, this only happens when importing a typescript module into a component right?

**Comment by jgw96** [comment] 2017-12-04 16:29
Hello! I am closing this as a duplicate of https://github.com/ionic-team/stencil/issues/341

**Closed by jgw96** 2017-12-04 16:29 UTC
