### ISSUE TITLE
bug: @Watch() doesn't detect prop change when it (array) is emptied

### ISSUE THREAD

**Issue by RoboVij** [ionic-team/stencil#3373] opened 2022-05-20 10:21 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.11.0

### Current Behavior

I'm passing down an array of objects as prop into a stencil built component.

```javascript
        <parent-items
            ...
            :collection.prop="[{ },..., { }]"
        ></parent-items>
```
When I change the `collection` array the @Watch() decorator is detecting the prop, even if the array has 1000 to 10000 objects in it. But it's not detecting when I make the array empty from whatever no. of objects in it. Is thi sexpected behaviour or what am I doing wrong?

Inside the `parent-items.tsx` file in stencil:

```javascript
  @Prop() collection!: ItemsCollectionDescriptor;
```

```javascript
@Watch('collection')
  onCollectionChanged(items: ItemsCollectionDescriptor): void {
    console.log(items);
    const parsed = typeof items === 'string' ? items.trim() ? JSON.parse(items) : [] : items;
    const source = Array.isArray(parsed) ? parsed : parsed ? [parsed] : [];
    ...
   }
```

Type definition:
```javascript
export interface ItemDescriptor {
  x: number;
  y: number;
  draggable?: boolean;
}

export type ItemsCollectionDescriptor = string | ItemDescriptor[];
```

### Expected Behavior

@Watch() decorator should detect the empty array.

### Steps to Reproduce

Check the code samples.

### Code Reproduction URL

--

**Comment by MarkChrisLevy** [comment] 2022-05-20 11:16
In order to rerender or fire watch method you must pass new array or new object, so what you wrote is working as expected as clearing an array (e.g. with splice) modifies original array. Read more in docs https://stenciljs.com/docs/reactive-data

**Comment by rwaskiewicz** [comment] 2022-05-20 12:30
@MarkChrisLevy is correct here. A new array must be returned:

> Instead, non-mutable array operators should be used as they return a copy of a new array. These include map() and filter(), and the ES6 spread operator syntax.

([source](https://github.com/ionic-team/stencil-site/blob/master/src/docs/components/reactive-data.md#updating-arrays))

The reason for this is in the name of efficiency.  It's a much easier/faster check to see if a variable points to a different array entirely, than to see of the array itself has changed.  That page of our docs could use some work though - I'm going to put an item in our backlog to try to clarify some things/update the contents.

@RoboVij Does that answer your question? If not, could you please post full reproduction to github the team could pull down? Thanks!

**Comment by RoboVij** [comment] 2022-05-21 08:02
A small update. This is how my actual code looks like. It's in vue. So when the array is updated with elements i.e. when showItems1 or/and showItems2 is/are true, the @Watch() is being rerendered. When both showItems1 and showItems2 are false, my array has no elements in it so no rerendering. 

> For arrays, the standard mutable array operations such as push() and unshift() won't trigger a component update.

But I am using push() and it is working. Is it working because of the spread operator `...this.items1`? If yes, how do I make it work for the emptied array case? I can't use the spread operator then.

```javascript
        <parent-items
            ...
            :collection.prop="items"
        ></parent-items>
```

```javascript
computed: {
    items() {
      let list = [];
      if (this.showItems1) {
        list.push(...this.items1);
      }
      if (this.showItems2) {
        list.push(...this.items2);
      }
      return list;
    },
}
```

**Comment by rwaskiewicz** [comment] 2022-05-23 12:04
Hey @RoboVij, 

To be able for us to really determine if this is a bug or not, can you please upload a minimal reproduction case for the team to pull down? While code snippets help provide some context, building out a reproduction case can help us answer questions like:
- Does the same issue occur without Vue? Or are the bindings needed to reproduce the error?
- What output targets is the project using? How is the project built? 
-  Is there anything else triggering a (re)render? 

Thanks!

**Comment by RoboVij** [comment] 2022-05-24 09:28
@rwaskiewicz  How do I reproduce this? Because, first I need to create the plugin project with Stencil and store it somewhere. Then, I need to install this plugin in a Vue project. So do I need to create two projects and where do I store the plugin built by Stencil to be able to install it in Vue? (Currently we're storing it in our private npm, so I can't share that)

My main question is what I wrote in the previous code snippet supposed to work i.e. rerender @Watch() by emptying array like that? Is the code in `computed` providing a new array or modifying the original array? (I guess it's more of a Vue question than Stencil's. But maybe you've an idea)

**Comment by rwaskiewicz** [comment] 2022-05-24 17:39
Hey @RoboVij,

> My main question is what I wrote in the previous code snippet supposed to work i.e. rerender @watch() by emptying array like that?

I'm not sure - that's the reason we ask for a code reproduction case. It allows us to see the whole picture, rather than trying to piece together bits of code snippets when trying to determine if this is a bug or not.

> How do I reproduce this? Because, first I need to create the plugin project with Stencil and store it somewhere. Then, I need to install this plugin in a Vue project. So do I need to create two projects and where do I store the plugin built by Stencil to be able to install it in Vue? 

That sounds like a good process! I would start with recreating a new Stencil project with `npm init stencil@latest component my-library` and trying to see if you see the same behavior in the sample project.  If it's reproducible, that can be pushed up to GitHub/Stackblitz/etc. for someone on the team to take a look.

If that doesn't reproduce it, then yes, you'd need to wrap your components using the Vue wrapper and create a demo that uses it and upload that as well.  Because that does entail extra work, it's beneficial to see if you can replicate this in just Stencil first.

> Currently we're storing it in our private npm, so I can't share that

Totally understandable! We don't want to encourage that anyone share private code

**Comment by RoboVij** [comment] 2022-05-31 09:30
@rwaskiewicz  It works properly within the Stencil project, the @Watch() rerenders in the empty array case. So I tried publishing to npm to test it in the Vue project. This is my first time publishing to npm. So I'm not sure what I'm doing wrong, but I couldn't test it because of this error:
`[Vue warn]: Unknown custom element: <my-component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Stencil project: https://github.com/RoboVij/stencil-tester-watch
npm package: https://www.npmjs.com/package/stencil-tester-watch
Vue Project: https://github.com/RoboVij/stencil-test

I'm importing like [this](https://github.com/RoboVij/stencil-test/blob/master/src/components/HelloWorld.vue#L20)
And using the component like [this](https://github.com/RoboVij/stencil-test/blob/master/src/components/HelloWorld.vue#L15)

**Comment by rwaskiewicz** [comment] 2022-06-22 17:59
I'm going to close this issue due to lack of reproduction case.  If this is still an issue, please feel free to create a new issue with a minimal reproduction URL for the team to pull down and take a look at.  Thanks!

**Closed by rwaskiewicz** 2022-06-22 17:59 UTC
Labels: ionitron: needs reproduction
