### ISSUE TITLE
bug: Rollup: Parse Error: ./node_modules/@stencil/core/compiler/stencil.js:36248:26 unrelated to code change

### ISSUE THREAD

**Issue by goulu** [ionic-team/stencil#3875] opened 2022-12-06 14:59 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.20.0

### Current Behavior

after apparently unrelated changes in a large custom library of components, I get this error when building : 
```
> npx stencil build --verbose

[53:39.2]  @stencil/core
[53:39.4]  v2.20.0
[53:39.4]  node 19.2.0  MEM: 67.2MB
[53:39.4]  windows, Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz  MEM: 67.2MB
[53:39.4]  cpus: 6, freemem: 2200MB, totalmem: 17090MB  MEM: 67.2MB
[53:39.4]  compiler: C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js
           MEM: 67.3MB
[53:39.4]  build: 20221205164801  MEM: 67.3MB
[53:39.6]  cache enabled, cacheDir: C:/Users/Philippe/Develop/BOBST/sphere-stencil/.stencil  MEM: 82.0MB
[53:39.7]  create workers, maxWorkers: 5  MEM: 82.3MB
[53:39.7]  Starting compilation in watch mode...  MEM: 82.4MB
[53:41.7]  build, sphere, prod mode, started ...
[53:41.7]  start build, 2022-12-06T13:53:41  MEM: 256.1MB
[53:41.7]  cleaning 6 dirs ...  MEM: 258.0MB
[53:41.7]  cleaning dirs finished in 3 ms  MEM: 260.2MB
[53:41.7]  transpile started ...
[53:43.2]  load collection: @ionic/core, ./node_modules/@ionic/core/dist/collection/collection-manifest.json  MEM:
           395.4MB
[53:43.6]  load collection: ionicons, ./node_modules/ionicons/dist/collection/collection-manifest.json  MEM:
           433.5MB
[53:45.6]  Transpiled modules: [(removed)
[53:45.6]  generated app types started ...  MEM: 529.7MB
[53:45.6]  generated app types finished: ./src/components.d.ts in 7 ms  MEM: 529.8MB
[53:46.3]  transpile finished in 4.56 s
[53:46.3]  generate outputs started ...  MEM: 574.8MB
[53:46.3]  getComponentAssetsCopyTasks: 14  MEM: 574.8MB
[53:46.3]  getComponentAssetsCopyTasks: 14  MEM: 574.8MB
[53:46.3]  getComponentAssetsCopyTasks: 12  MEM: 574.8MB
[53:46.3]  copy started ...
[53:46.3]  generate collections started ...  MEM: 574.9MB
[53:46.7]  generate custom elements started ...
[53:46.7]  generate lazy started ...
[53:46.7]  generateEntryModules, 106 entryModules  MEM: 594.2MB
[53:46.7]  generate www started ...  MEM: 594.2MB
[53:46.8]  generate collections finished in 484 ms  MEM: 594.1MB
[53:46.9]  generateIndexHtml, write: ./www/index.html  MEM: 606.0MB
[53:46.9]  generate www finished in 145 ms  MEM: 606.0MB
[53:48.3]  copy finished (2771 files) in 2.03 s
[54:13.4]  generate lazy finished in 26.67 s
[54:24.0]  generate custom elements finished in 37.27 s
[54:24.6]  updated readme docs: (removed)
[54:24.7]  generate types started ...  MEM: 2643.0MB
[54:24.7]  generate types finished in less than 1 ms  MEM: 2643.0MB
[54:24.7]  generate outputs finished in 38.38 s  MEM: 2643.0MB
[54:24.7]  aborted build, 42966ms  MEM: 2643.0MB

[ ERROR ]  Rollup: Parse Error: ./node_modules/@stencil/core/compiler/stencil.js:36248:26
           Unexpected token at error
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:37591:26) at
           Module.error
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:42000:12) at
           Module.tryParse
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:42406:19) at
           Module.setSource
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:42307:18) at
           ModuleLoader.addModuleSource
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:50641:14) at
           async ModuleLoader.fetchModule
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:50697:5) at
           async Promise.all (index 4) at async ModuleLoader.fetchStaticDependencies
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:50722:30) at
           async Promise.all (index 0) at async ModuleLoader.fetchModule
           (C:\Users\Philippe\Develop\BOBST\sphere-stencil\node_modules\@stencil\core\compiler\stencil.js:50699:5)

  L36247:  SVGTextPathElement: C,
  L36248:  SVGTextPositioningElement: C,
  L36249:  SVGTitleElement: C,

[54:24.7]  build failed in 42.97 s

[54:28.6]  Telemetry:
           {"arguments":["--verbose"],"build":"20221205164801","component_count":0,"config":{"namespace":"omitted","outputTargets":[{"type":"dist-types","dir":"omitted","typesDir":"omitted"},{"type":"dist-custom-elements","generateTypeDeclarations":true,"dir":"omitted","empty":true,"externalRuntime":true,"copy":[]},{"type":"www","serviceWorker":null,"baseUrl":"omitted","dir":"omitted","appDir":"omitted","buildDir":"omitted","indexHtml":"omitted","empty":true,"polyfills":true},{"type":"dist-lazy","dir":"omitted","esmDir":"omitted","polyfills":true,"isBrowserBuild":true},{"type":"copy","dir":"omitted","copyAssets":"omitted"},{"type":"copy","dir":"omitted","copy":[{"src":"omitted","warn":false},{"src":"omitted","warn":false}]},{"type":"dist-global-styles","file":"omitted"},{"type":"dist","esmLoaderPath":"omitted","copy":[{"src":"omitted","dest":"omitted"},{"src":"omitted","dest":"omitted"}],"dir":"omitted","buildDir":"omitted","collectionDir":"omitted","typesDir":"omitted","empty":true,"transformAliasedImportPathsInCollection":false},{"type":"dist-lazy","esmDir":"omitted","legacyLoaderFile":"omitted","polyfills":true,"isBrowserBuild":true,"empty":true},{"type":"copy","dir":"omitted","copyAssets":"omitted","copy":[{"src":"omitted","dest":"omitted"},{"src":"omitted","dest":"omitted"}]},{"type":"dist-global-styles","file":"omitted"},{"type":"dist-types","dir":"omitted","typesDir":"omitted"},{"type":"dist-collection","dir":"omitted","collectionDir":"omitted","empty":true,"transformAliasedImportPaths":false},{"type":"copy","dir":"omitted","copyAssets":"omitted","copy":[{"src":"omitted","dest":"omitted"},{"src":"omitted","dest":"omitted"},{"src":"omitted"},{"src":"omitted"}]},{"type":"dist-lazy","esmDir":"omitted","cjsDir":"omitted","cjsIndexFile":"omitted","esmIndexFile":"omitted","polyfills":true,"empty":true},{"type":"dist-lazy-loader","dir":"omitted","esmDir":"omitted","cjsDir":"omitted","componentDts":"omitted","empty":true},{"type":"docs-readme","footer":"omitted","dir":"omitted","strict":false}],"globalStyle":"C:/Users/Philippe/Develop/BOBST/sphere-stencil/src/global/sphere.scss","plugins":[{"name":"sass","pluginType":"css"}],"rollupPlugins":{"before":[],"after":[]},"configPath":"omitted","flags":{"task":"build","args":["--verbose"],"knownArgs":["--verbose"],"unknownArgs":[],"verbose":true},"rootDir":"omitted","devMode":false,"extras":{"appendChildSlotFix":false,"cloneNodeFix":false,"cssVarsShim":false,"dynamicImportShim":false,"lifecycleDOMEvents":false,"safari10":false,"scriptDataOpts":false,"shadowDomShim":false,"slotChildNodesFix":false,"initializeNextTick":false,"tagNameTransform":false},"buildEs5":false,"minifyCss":true,"minifyJs":true,"sourceMap":false,"watch":false,"buildDocs":true,"buildDist":true,"profile":false,"writeLog":false,"buildAppCore":true,"autoprefixCss":false,"validateTypes":true,"allowInlineScripts":true,"taskQueue":"async","hashFileNames":true,"hashedFileNameLength":8,"fsNamespace":"omitted","srcDir":"omitted","cacheDir":"omitted","srcIndexHtml":"omitted","packageJsonFilePath":"omitted","hydratedFlag":{"name":"hydrated","selector":"class","property":"visibility","initialValue":"hidden","hydratedValue":"inherit"},"bundles":[],"maxConcurrentWorkers":8,"devInspector":false,"enableCache":true,"watchIgnoredRegex":[],"logLevel":"debug","tsconfig":"omitted"},"cpu_model":"Intel(R)
           Core(TM) i5-9600K CPU @
           3.70GHz","duration_ms":42966,"has_app_pwa_config":false,"is_browser_env":false,"os_name":"windows","os_version":"10.0.19044","packages":["@stencil/core@2.20.0","@stencil/sass@2.0.1","@stencil/store@2.0.1","@ionic/core@6.3.9"],"packages_no_versions":["@stencil/core","@stencil/sass","@stencil/store","@ionic/core"],"rollup":"2.42.3","stencil":"2.20.0","system":"node
           19.2.0","system_major":"node
           19","targets":["dist-types","dist-custom-elements","www","dist-lazy","copy","dist-global-styles","dist","dist-collection","dist-lazy-loader","docs-readme"],"task":"build","typescript":"4.8.4","yarn":false}
            MEM: 2193.4MB
```

### Expected Behavior

Compiled fine before, but after 2 days of serching (!!!) I'm unable to find what changes (in code, in stencil version, in dependencies ???) cause this...

So I'd say the main problem is that the error message doesn't help in finding the cause of the problem ...

### System Info

```shell
Windows 10, Node 19.2, npm 8.16
```

### Steps to Reproduce

Sorry, it's part of a large project, I couldn't find the actual change which caused the problem to appear

### Code Reproduction URL

https://sorry.unable.to.reproduce.simply

### Additional Information

sometimes it even cause a deeper crash :
```
[51:07.7]  copy finished (2736 files) in 5.30 s

<--- Last few GCs --->

[3892:000001B4A7609820]   441665 ms: Mark-Compact 4045.7 (4146.6) -> 4042.5 (4143.4) MB, 1738.9 / 0.0 ms  (average mu = 0.126, current mu = 0.006) allocation failure; scavenge might not succeed
[3892:000001B4A7609820]   443378 ms: Mark-Compact 4049.7 (4150.7) -> 4044.9 (4145.8) MB, 1704.7 / 0.0 ms  (average mu = 0.069, current mu = 0.005) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF791A08AFF node_api_throw_syntax_error+176047
 2: 00007FF79198F576 v8::internal::wasm::WasmCode::safepoint_table_offset+67686
 3: 00007FF791990933 v8::internal::wasm::WasmCode::safepoint_table_offset+72739
 4: 00007FF7924BE521 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF7924A9176 v8::internal::V8::FatalProcessOutOfMemory+662
 6: 00007FF79230F870 v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+144
 7: 00007FF79230C88D v8::internal::Heap::CollectGarbage+4749
 8: 00007FF7923224B6 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2150
 9: 00007FF792322DEF v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+95
10: 00007FF792332010 v8::internal::Factory::NewFillerObject+448
11: 00007FF791FE7AA5 v8::internal::Runtime::SetObjectProperty+20997
12: 00007FF792567C71 v8::internal::SetupIsolateDelegate::SetupHeap+606705
13: 00007FF7925853DB v8::internal::SetupIsolateDelegate::SetupHeap+727387
14: 00007FF71380425D

 *  The terminal process "C:\WINDOWS\System32\cmd.exe /d /c npm run debug" terminated with exit code: 134. 
 ```

**Comment by rwaskiewicz** [comment] 2022-12-06 15:47
Hey @goulu 👋 

Without a reproduction case, there's a very limited amount of things we can do to investigate. Can you please try to create a minimal reproduction app for us? Without one, it's very likely we won't be able to determine what's causing this issue.

In addition to that, can you please let us know what changed that may be causing the issue? For example:
- Did the application compile (without any code changes) just fine with Stencil 2.19.3, but fail on 2.20.0?
- If the answer is it fails on both versions, does it fail on a previous version of Stencil (again, without any code changes)?
- If the answer is it fails only with code changes applied, what type of file is changing? Can you give us an example that resembles the type of change you're making? (Looking to see if there's some syntax that's not supported)
- Has anything else changed? Node/npm version? OS? etc?

Thanks!

**Comment by goulu** [comment] 2022-12-06 16:18
(I just added a stack dump of the "deeper crash" that occurs sometimes)
I'm aware a reproductible code would greatly help, but there are simply too many things that changed that I couldn't spot which one hurts.

And that's exactly the real problem : even with --verbose, Stencil doesn't give enough information after "generate custom elements finished "  

Stencil says it generated everything fine before the " aborted build" (but it was not : there are just 2 or 3 components .tsx files in dist/ and www/ where there should be 50, so what does it do after this ???

I'll put some console.log in stencil.js to figure out what happens ... what else can I do ?

**Comment by rwaskiewicz** [comment] 2022-12-06 16:32
>  I'm aware a reproductible code would greatly help, but there are simply too many things that changed that I couldn't spot which one hurts.

Are they all code changes? I.E. no dependency updates, no changes to npm/node, etc? I'd like to verify if this exists in Stencil 2.20.0 only or has existed prior to that release.

> Stencil says it generated everything fine before the " aborted build" (but it was not : there are just 2 or 3 components .tsx files in dist/ and www/ where there should be 50, so what does it do after this ???

The error messaging isn't great in Stencil at this particular point in the pipeline. It's a catch-all for an unforeseen error case, which is in part why it's so vague.

> I'll put some console.log in stencil.js to figure out what happens ... what else can I do ?

The questions I listed in https://github.com/ionic-team/stencil/issues/3875#issuecomment-1339580246 can probably get us on the right path

Thanks!

**Comment by goulu** [comment] 2022-12-07 09:07
Found ! (but not understood, and I couldn't reproduce it in a simple project after trying 1 hour...)

In fact I noticed something strange in the `components.d.ts` file : 
```
import { Navigation } from "./utils/navigation";
import { Navigation as Navigation1 } from "./utils";
```
and indeed in the code we `import {Notification}` sometimes from `utils/navigation.ts` where it is defined, and sometimes from `utils/` since we created an `index.ts` file that re-exports everything from the various utils files ...

once I imported `Navigation` (an interface) from "./utils/navigation" everywhere, the error disappeared.

The problem is solved on my side, but still the error message is totally unrelated to the cause. 
IMHO Stencil should imho a warning such as "same `interface Notification` is imported from different paths" in such cases

Many thanks for your patience and help.

**Comment by rwaskiewicz** [comment] 2022-12-07 14:27
> IMHO Stencil should imho a warning such as "same interface Notification is imported from different paths" in such cases

Completely agreed. Do you mind sharing your reproduction case? That'd be super helpful for us to use to work on a fix!

**Comment by tanner-reits** [comment] 2023-08-30 20:22
Hey @goulu 👋 

Looks like this has been open for a while with no reproduction case. As such, I'm going to close this. If you're still experiencing this problem, feel free to open a new issue with a reproduction case running the latest version of Stencil. Thanks!

**Closed by tanner-reits** 2023-08-30 20:22 UTC
Labels: ionitron: needs reproduction
