### ISSUE TITLE
`stencil generate` output changed format with the new compiler

### ISSUE THREAD

**Issue by alexandertrefz** [ionic-team/stencil#2303] opened 2020-03-24 07:22 UTC
Ever since the legacy compiler got removed, in [this commit](https://github.com/ionic-team/stencil/commit/63595bc540db9aa85295f5a8dc8738beb2a37611), `stencil generate` outputs a considerably different format of folders & files.
My primary concern lies in the changed naming conventions of the folder and files (and the name of the class) that get generated - perviously they had their prefix and dash stripped, now they don't anymore. That takes most of the utility of `stencil generate` away for any existing codebase, unless it fully adapts the new scheme. This change wasn't mentioned in any changelog, so I wonder wether this was accidental?

**I'm submitting a:**
[x] bug report
[ ] feature request

**Current behavior:**
`stencil generate` creates folders and files and the class with their dash-prefix

**Expected behavior:**
`stencil generate` should strip the dash-prefix like in previous versions.

**Steps to reproduce:**
Run `stencil generate`.

**Comment by manucorporat** [comment] 2020-05-06 17:31
Duplicate of https://github.com/ionic-team/stencil/issues/2347#issuecomment-624779936

**Closed by manucorporat** 2020-05-06 17:31 UTC
Labels: triage
