### ISSUE TITLE
Service worker does not include app.css in manifest

### ISSUE THREAD

**Issue by ficoos** [ionic-team/stencil#1631] opened 2019-06-12 10:43 UTC
**Stencil version:**

```
@stencil/core@1.0.0 
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When using service workers in development mode `app.css` is not included in the sw precache manifest.

**Expected behavior:**
`app.css` is included

**Steps to reproduce:**
`stencil build --dev --watch --serve --serviceWorker`

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

When building in development you can see the the generate style and generate service worker stages happen concurrently. There might be a race between the sw globber and the style generation code

**Comment by manucorporat** [comment] 2019-06-12 14:30
why do you expect it included?

**Comment by ficoos** [comment] 2019-06-13 09:27
It's needed for the site to be available offline. Without it you don't have the global css available when you are offline. This makes testing the site's offline behavior on a dev server impossible.

**Comment by manucorporat** [comment] 2019-06-13 23:40
can you share your index.html?

**Comment by michael42** [comment] 2020-06-03 20:56
It seems that @stencil/core 1.14.0 explicitly ignores the main css and js files via `globIgnores`, which makes the resulting service worker rather pointless. It caches the HTML file, but then everything that file references is missing.

**Comment by michael42** [comment] 2020-06-06 09:47
I'll retract my statement. When using `href="/build/app.css"` and `src="/build/app.esm.js"`, these references will be rewritten into the `p-...` files that *are* cached by the ServiceWorker. I used relative references (`build/app.esm.js`), which are neither rewritten (in the `index.html`) nor cached by the ServiceWorker.

**Comment by MrAntix** [comment] 2020-11-22 17:11
removing the following lines from the built index.html file made it work for me

```
  <link href="/build/app.css" rel="stylesheet">
  <script type="module" src="/build/app.esm.js"></script>
  <script nomodule src="/build/app.js"></script>
```

**Comment by splitinfinities** [comment] 2021-08-03 20:17
Hey everyone, thank you for the patience. Would anyone happen to know if this behavior exists within v2? If we could update the repro case for these, I would appreciate it, and it would help us diagnose and solve this problem sooner than later.

**Comment by rwaskiewicz** [comment] 2021-09-03 12:17
Hey ionitron-bot, we didn't mean to close this. Bad bot!

**Comment by rwaskiewicz** [comment] 2022-04-18 13:12
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!

**Closed by rwaskiewicz** 2022-04-18 13:12 UTC
Labels: ionitron: needs reproduction
