### ISSUE TITLE
bug: Using the same EventEmitter name in child component leads to additional emission from parent component.

### ISSUE THREAD

**Issue by gikey** [ionic-team/stencil#3501] opened 2022-08-01 03:18 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

"@stencil/core": "^2.13.0"

### Current Behavior

Using the same EventEmitter name in child component leads to additional emission from parent component.  I try to set bubbles: false, but still doesn't work. 

### Expected Behavior

Child component events emitters should always be treated as separate ones as naming conflict in those can occur.

### Steps to Reproduce

- Have parent component with an event emitter, lets call it `valuechange`
- Have child component with the same event emitter name`valuechange`
- Use child component in parent 
- Use parent component after compilation and attach even listener using addEventListener function for `valuechange` event
- Emit`valuechange` event from child component.

### Code Reproduction URL

https://github.com/gikey/stencil-demo

**Comment by rwaskiewicz** [comment] 2022-08-01 14:09
Hey @gikey 👋 

Thanks for the reproduction case! Can you do me a favor and add what you're seeing in the reproduction case that demonstrates this issue? Specifically, can you add the following for me:

- Steps to run the reproduction case (I used `npm start`, but want to make sure we're on the same page here)
- How to interact with the reproduction case to recreate the bug
- What someone should see in the console/application/component that demonstrates what the bug is

Thanks!

**Comment by rwaskiewicz** [comment] 2022-08-22 12:03
I'm going to close this issue due to lack of reproduction case. If this is still an issue, please feel free to create a new issue with a minimal reproduction URL for the team to pull down and take a look at. Thanks!

**Closed by rwaskiewicz** 2022-08-22 12:03 UTC
Labels: ionitron: needs reproduction
