### ISSUE TITLE
beep is not defined

### ISSUE THREAD

**Issue by oliverjanik** [ionic-team/stencil#1067] opened 2018-09-06 05:50 UTC
```
? Pick a starter » - Use arrow-keys. Return to submit.

>  ionic-pwa     Everything you need to build fast, production ready PWAs
   app           Minimal starter for building a Stencil app or website
   component     Collection of web components that can be used anywherereadline.js:1020
            throw err;
            ^

ReferenceError: beep is not defined
    at SelectPrompt.bell (C:\Users\Oliver\AppData\Roaming\npm-cache\_npx\9024\node_modules\create-stencil\dist\index.js:2:30265)
    at SelectPrompt.up (C:\Users\Oliver\AppData\Roaming\npm-cache\_npx\9024\node_modules\create-stencil\dist\index.js:2:31832)
    at ReadStream.n (C:\Users\Oliver\AppData\Roaming\npm-cache\_npx\9024\node_modules\create-stencil\dist\index.js:2:29953)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1010:36)
    at emitOne (events.js:121:20)
    at ReadStream.emit (events.js:211:7)
```

**Comment by jthoms1** [comment] 2018-09-06 18:56
Closing as a duplicate of https://github.com/ionic-team/create-stencil/issues/13

**Closed by jthoms1** 2018-09-06 18:56 UTC
Labels: triage
