### ISSUE TITLE
bug: transformTagName and generateCustomElementType

### ISSUE THREAD

**Issue by benjamin-t-frost** [ionic-team/stencil#3393] opened 2022-05-30 15:25 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.15.2

### Current Behavior

When using `transformTagName` to isolate multiple version of web components built with Stencil, the types generated from both `custom-elements-bundle-types` [generateCustomElementType](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/dist-custom-elements-bundle/custom-elements-bundle-types.ts#L89-L101) and `custom-elements-types` [generateCustomElementsType](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/dist-custom-elements/custom-elements-types.ts#L108-L126) do not get assigned to their respective web components.

Thus, all custom elements instances are of type `HTMLElement`.

### Expected Behavior

All exported web components should have types reflective of their definitions when using `transformTagName`.

### Steps to Reproduce

1. Generate web component library with output target type of either `dist-custom-elements-bundle` or `dist-custom-elements` with `extras.tagNameTransform: true`.
2. Define custom elements
```typescript
import { defineCustomElements } from 'custom-component-libary/loader';

defineCustomElements(window, {
  transformTagName: (tagName: string) => `v1-${tagName}`,
});
```
3. Attempt to assign a web component instance to a variable assigned a corresponding type
```typescript
import type { Components } from 'custom-component-libary';

let myComponent: Components.MyComponent;

// ... 

myComponent = myComponentInstance;
```

Sample Error:
```bash
Error: Type 'HTMLElement' is missing the following properties from type 'MyComponent': {listOfCustomProperties}, and {n} more. (ts)
```

**Comment by rwaskiewicz** [comment] 2022-06-06 12:27
Hey @benjamin-t-frost 👋 

I do believe that this may be a valid bug, can you do me a favor and bundle the reproduction steps into a repo that the team could pull down and run? Thanks!

**Comment by rwaskiewicz** [comment] 2022-06-22 17:58
I'm going to close this issue due to lack of reproduction case.  If this is still an issue, please feel free to create a new issue with a minimal reproduction URL for the team to pull down and take a look at.  Thanks!

**Closed by rwaskiewicz** 2022-06-22 17:58 UTC
Labels: ionitron: needs reproduction
