### ISSUE TITLE
Comments in array of children renders as undefined

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#506] opened 2018-02-08 16:12 UTC
I have a JSX comment in an array of children, and when rendering, it outputs as an `<undefined></undefined>` tag:

Source:

<img width="1011" alt="screenshot 2018-02-08 10 11 51" src="https://user-images.githubusercontent.com/11214/35983798-7f5b5fb2-0cb8-11e8-8ac0-5cba0cb21513.png">

DOM:

<img width="531" alt="screenshot 2018-02-08 10 10 58" src="https://user-images.githubusercontent.com/11214/35983809-854e8bf6-0cb8-11e8-8035-6f01857a7d4a.png">

**Comment by dkundel** [comment] 2018-02-08 16:35
I had the same thing. It happens when you have an `undefined` object in your array which you have due to the `{ }`. I definitely think that this isn't the intended behavior though.

**Comment by adamdbradley** [comment] 2018-03-17 06:18
Closing for now since this is currently typescript to jsx. Looks like they have it on track to be fixed.

**Closed by adamdbradley** 2018-03-17 06:18 UTC
Labels: bug
