### ISSUE TITLE
Components like ion-fab don't allow (placement) attributes

### ISSUE THREAD

**Issue by TamoMaez** [ionic-team/stencil#521] opened 2018-02-11 12:50 UTC
Ionic components like ion-fab don't allow attributes (props). E.g. 'top', 'right', ...

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels:

**Current behavior:**
<img width="572" alt="screen shot 2018-02-11 at 13 38 57" src="https://user-images.githubusercontent.com/9150806/36073476-91eb3884-0f31-11e8-939e-edf4c833dd2a.png">

**Expected behavior:**
Make use of components like the docs describe (https://github.com/ionic-team/ionic/tree/core/packages/core/src/components/fab)

**Steps to reproduce:**
Paste this code in your app
`<ion-fab top right slot="fixed">
<ion-fab-button>
<ion-icon name="add"></ion-icon>
</ion-fab-button>
</ion-fab>`

**Comment by jgw96** [comment] 2018-02-12 16:28
Hey, thanks for opening an issue with us! I am going to close this as a duplicate of https://github.com/ionic-team/ionic/issues/13596.

**Closed by jgw96** 2018-02-12 16:28 UTC
