### ISSUE TITLE
[BUG][1.0.0] Prerender build fails with commented HTML

### ISSUE THREAD

**Issue by ihadeed** [ionic-team/stencil#1592] opened 2019-06-04 17:07 UTC
Not sure if this is a bug or a new JSX standard.

I upgraded one of the websites I created with Stencil that had some commented HTML. Dev/Dist builds without pre-render worked fine. But when I ran `npx stencil build --prerender` it broke and gave me this error (XXX = path to project):
```
[ ERROR ]  Hydrate Error: /
           The tag name provided (undefined) is not a valid name. at createElement
           (/XXX/node_modules/@stencil/core/dist/mock-doc/index.js:2154:15) at
           MockDocument.createElement
           (/XXX/node_modules/@stencil/core/dist/mock-doc/index.js:3127:16) at
           MockDocument.patchedCreateElement [as createElement]
           (/XXX/dist/hydrate/app.js:1636:50) at createElm
           (/XXX/dist/hydrate/app.js:389:19) at addVnodes
           (/XXX/dist/hydrate/app.js:470:25) at patch
           (/XXX/dist/hydrate/app.js:658:13) at renderVdom
           (/XXX/dist/hydrate/app.js:806:5) at updateComponent
           (/XXX/dist/hydrate/app.js:920:17) at writeTask
           (/XXX/dist/hydrate/app.js:895:25) at process.nextTick
           (/XXX/dist/hydrate/app.js:1781:13)
```

The commented code looked like this:
```jsx
render() {
  return [
    <div>some uncommented stuff</div>,
    {/*<section class="home-screenshots section"><div class="container"></div></section>,*/},
    <div>some more uncommented stuff</div>
  ];
}
```

**Comment by wslaghekke** [comment] 2019-10-02 20:09
I cant reproduce this problem with the latest stencil version.
Does this bug still occur for you on the lastest version?

**Comment by adamdbradley** [comment] 2020-01-15 00:37
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-15 00:37 UTC
Labels: triage
