### ISSUE TITLE
ion-content fullscreen freezes the prerender process

### ISSUE THREAD

**Issue by HaythemSahbani** [ionic-team/stencil#2429] opened 2020-05-11 13:42 UTC
**Stencil version:**

```
 @stencil/core@1.12.7
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Hi I am trying to prerender the ionic-stencil starter app. However when adding `fullscreen` to the `ion-content` element the prerender process becomes inresponsive and I have to manually kill the process.
**Expected behavior:**

The prerendering process doesn't freez
**Steps to reproduce:**

1. Run _npm init stencil_, (choose the ionic pwa)
2. in the generated home.tsx file add `fullscreen={true}` or `fullscreen` to the `ion-content`
3. Build with prerender, _npm run build -- --prerender_
**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by corysmc** [comment] 2020-05-21 18:49
+1 I just ran into this issue myself! - repro steps outlined above

**Comment by tricki** [comment] 2020-06-28 17:41
Same here.
After some debugging I discovered  what seems to be an infinite loop that keeps rendering the ion-content indefinitely. Confirmed by logging calls to [`updateComponent`](https://github.com/ionic-team/stencil/blob/54ee75f6cb8130276a00af6fff479ea8e0741833/src/runtime/update-component.ts#L69).

**Comment by cptflammin** [comment] 2021-09-08 13:12
Same here. Really problematic as a pretty important property in an app design ! Any update ?

**Comment by splitinfinities** [comment] 2021-09-08 13:28
Could folks update to the latest versions of Stencil and Framework and help me understand if this still exists? It would be super helpful as well if we could get a GitHub repo with the recreation steps so we can quickly identify and resolve the issue.

**Comment by tricki** [comment] 2021-09-08 14:20
I just created a new project (`npm init stencil`), added `fullscreen={true}` and configured a base URL and can reproduce the bug. Here's the repo (with VS Code prerender launch configured): https://github.com/tricki/stencil-fullscreen-prerender-bug 
Just run `npm run build --prerender` to reproduce it.


I still see [`updateComponent`](https://github.com/ionic-team/stencil/blob/bf5f197910daab7f822a6e4c56f4f40a81c2ce7e/src/runtime/update-component.ts#L69) being called in an endless loop for `ion-content`. Here's the call stack (note `updateComponent` at the top and bottom):

![image](https://user-images.githubusercontent.com/523154/132523365-2607075a-df0a-4403-8d89-8665a492abb0.png)

**Comment by rwaskiewicz** [comment] 2023-05-15 14:23
Hey folks. A fix for this issue was released as a part of [Ionic Framework v7.0.6](https://github.com/ionic-team/stencil/issues/2429). As a result, I'm going to close out this issue. If this issue should reappear, please feel free to open a new issue. Thanks!

**Closed by rwaskiewicz** 2023-05-15 14:23 UTC
Labels: Resolution: Needs Investigation
