### ISSUE TITLE
bug: unable to do a crypto dApp node-polyfills and commonjs issue

### ISSUE THREAD

**Issue by mburger81** [ionic-team/stencil#3504] opened 2022-08-01 17:31 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.17.1

### Current Behavior

Sorry @rwaskiewicz but I think my bug reports It's really not a support request

there are several issues I show you up, where I write you some workarounds but honestly this workarounds are just needed due al this issues, and at the end you run into a last issue which I can not find a workaround and which we can not resolve for this plugin issues.

But the problem is IMO, the rollup plugins are not working as expected, so there are many issues.

I invested really a lot of my time to show you up all this issues and some workarounds for this issues to go a step further, and to provide you a valid project you can easy reproduce this steps.

Honestly I think its not fair closing my bug report :(

https://github.com/ionic-team/stencil/issues/3499

### Expected Behavior

 would like that the plugins work to get work the node polyfills like they should work

### Steps to Reproduce

Clone https://github.com/mburger81/stencil-dapp and try, maybe you should start commenting all the plugins

### Code Reproduction URL

https://github.com/mburger81/stencil-dapp

**Comment by rwaskiewicz** [comment] 2022-08-03 18:07
Hey @mburger81,

I'm sorry you feel that way. Closing the issue was not personal in any way.

The reason the issue was closed is that it was unclear the problem(s) being described were. Specifically, it was difficult to differentiate between what was an issue you were reporting with Stencil, and issues that you found while attempting workarounds.  This made the issue read like a support ticket, rather than a bug report.

For an issue to be actionable for us, we ask that there is a single issue per report, with the details to reproduce the issue.  This allows us to understand what's going on more easily. If you'd like, I would suggest you use this issue (#3504) or open a new one, that explains the problem, with any workaround attempts moved to the 'Additional Information' section.  If you can update the reproduction to match the updated problem explanation, and provide us a step-by-step way to reproduce (e.g. what commands should we run?) we can take another shot at triaging this.  If not, I completely understand.

**Closed** 2022-08-26 13:47 UTC
Labels: Awaiting Reply
