### ISSUE TITLE
Component tag is defined in a bundle but no matching component was found within this app or its collections

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#396] opened 2018-01-06 16:39 UTC
**Stencil version:**

master branch / 0.1.1-0

**I'm submitting a:**
- [X] bug report

**Current behavior:**

I followed the "Getting Started" displayed on the StencilJS website respectively

    git clone https://github.com/ionic-team/stencil-app-starter my-app
    cd my-app
    git remote rm origin
    npm install

after, still following, I tried

    npm start

which end with errors

> [ ERROR ]  Component tag "app-home" is defined in a bundle but no matching component was found within this app or its 
>            collections. 
> 
> [ ERROR ]  Component tag "my-app" is defined in a bundle but no matching component was found within this app or its 
>            collections. 
> 
> [ ERROR ]  Component tag "app-profile" is defined in a bundle but no matching component was found within this app or its 
>            collections. 
> 
> [34:18.8]  build failed, watching for changes... in 260 ms 

running `npm run build` produce same errors

**Other information:**

During `npm install` I faced following error/warning but I don't think it's related...so just in case https://forum.ionicframework.com/t/stencil-npm-install-fsevents-404-not-found/117428

node v9.3.0
npm 5.6.0

**Comment by adamdbradley** [comment] 2018-01-09 03:16
Can you try this again in `0.1.1`? Thanks

**Comment by jgw96** [comment] 2018-01-09 16:10
Hey @peterpeterparker , I can no longer reproduce this issue with the latest release so I am going to close this issue for now. Thanks for using Stencil!

**Closed by jgw96** 2018-01-09 16:10 UTC

**Comment by peterpeterparker** [comment] 2018-01-09 19:56
@jgw96 @adamdbradley I could still reproduce the problem because the problem isn't linked with stencil itself but linked with the **stencil-app-starter**

My bad I should have open an issue in https://github.com/ionic-team/stencil-app-starter

Should I or could you have a look?

**Comment by jgw96** [comment] 2018-01-09 20:21
Hey! I was not able to reproduce with the stencil-app-starter either. Could you do a fresh clone and see if you still have the issue?

**Comment by peterpeterparker** [comment] 2018-01-09 20:28
@jgw96 it's what I did a couple of minutes ago, twice actually 

most precisely

    git clone https://github.com/ionic-team/stencil-app-starter my-app
    cd my-app
    git remote rm origin
    npm install
    npm start

**Comment by jgw96** [comment] 2018-01-09 20:28
Thanks, alright let me try this

**Comment by jgw96** [comment] 2018-01-09 20:39
@peterpeterparker just copy pasted your commands exactly and for some reason still can't repro. Builds perfectly fine for me. Can you double check the version of Stencil you are running by checking the package.json in `node_modules/@stencil/core/` ? Also, this is just with a completely vanilla starter correct? No code added?

**Comment by jgw96** [comment] 2018-01-09 20:41
Im running @stencil/core@0.1.1-0

**Comment by peterpeterparker** [comment] 2018-01-09 20:41
@jgw96 yep I could confirm nothin added. Nothing more that the cmd I listed above

node 9.3.0
npm 5.6.0

package.json:

> "dependencies": {
>     "@stencil/core": "next",
>     "@stencil/router": "latest"
>   },
>   "devDependencies": {
>     "@stencil/dev-server": "latest",
>     "@stencil/utils": "latest",
>     "@types/jest": "^21.1.1",
>     "jest": "^21.2.1"
>   },
>   "repository": {
>     "type": "git",
>     "url": "git+https://github.com/ionic-team/stencil-app-starter.git"
>   }

**Comment by jgw96** [comment] 2018-01-09 20:44
Could you zip up your project and email it to me at justin at ionic.io please ?

**Comment by peterpeterparker** [comment] 2018-01-09 20:49
@jgw96 I'll, asap. Thx for your time!

**Comment by jgw96** [comment] 2018-01-09 20:50
No problem at all! Thank you for using Stencil!

**Comment by jgw96** [comment] 2018-01-09 21:34
@peterpeterparker hmm, just downloaded your project, did nothing to it besides run npm run dev, and its building and running fine on my machine. I'm running node 9.3.0. That's the only thing I can think that's different. Are you on the stencil slack by chance? Might be easier for us to debug that way.

**Comment by peterpeterparker** [comment] 2018-01-09 21:43
@jgw96 so weird...I'm not on slack. Could join the channel to try to find a solution, but only tomorrow 

Thx for the effort!

**Comment by jgw96** [comment] 2018-01-09 21:45
No problem at all, thanks for your patience, this is definitely the weirdest issue yet. Feel free to join the Stencil slack here https://stencil-worldwide.herokuapp.com/ and ping me tomorrow if you want. Im @Justin Willis on that Slack.

**Comment by Tonyhliu** [comment] 2018-08-03 18:25
Running into a similar problem. Is there a solution to this?

**Comment by bburch** [comment] 2019-02-19 00:48
I, too, am running to the same issue. Please advise as soon as possible.

Thanks,
brandon
