### ISSUE TITLE
Stencil builds error importing files that exist

### ISSUE THREAD

**Issue by morewry** [ionic-team/stencil#1496] opened 2019-05-02 21:41 UTC
I work on a design system in a [Lerna monorepo](https://github.com/lerna/lerna) that contains about 50 packages, a couple of which are Stencil packages; we've been evaluating fully investing it in to build our web components. But we're rethinking that because of several issues we've encountered in builds (this issue and some previous ones with TypeScript). The last few days Stencil builds are failing for apparently spurious reasons and blocking our ability to continue work. The failures occur on imports of CSS files from other node modules (symlinked within the monorepo). Stencil claims that the files cannot be located.

```
> npx lerna --scope @collectivehealth/dls-falcor-pages run build
lerna notice cli v3.13.2
lerna info versioning independent
lerna info filter [ '@collectivehealth/dls-falcor-pages' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 1 in '@collectivehealth/dls-falcor-pages'
lerna ERR! npm run build stdout:

> @collectivehealth/dls-falcor-pages@0.6.0 build /Users/rachael.moore/Projects/dls/components/falcor/dls-falcor-pages
> stencil build

[16:15.4]  @stencil/core v0.12.4 🏋
[16:15.4]  build, dls-falcor-pages, prod mode, started ...
[16:15.5]  transpile started ...
[16:16.8]  transpile finished in 1.32 s
[16:16.9]  module map started ...
[16:16.9]  generate styles started ...
[16:17.4]  generate styles finished in 488 ms
[16:17.7]  module map finished in 822 ms

[ ERROR ]  src/components/fa-nav-dropdown/fa-nav-dropdown.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-small.class-definitions.css';

[ ERROR ]  src/components/fa-sidebar/fa-sidebar.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-uppercase-med-medium.class-definitions.css';

[ ERROR ]  src/components/fa-nav-sidebar-item/fa-nav-sidebar-item.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-small.class-definitions.css';

[ ERROR ]  src/components/fa-nav-sidebar-item/fa-nav-sidebar-item.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-reg-medium.class-definitions.css';

[ ERROR ]  src/components/fa-nav-sidebar-item/fa-nav-sidebar-item.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-bold-medium.class-definitions.css';

[ ERROR ]  src/components/fa-nav-sidebar-item/fa-nav-sidebar-item.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-reg-small.class-definitions.css';

[ ERROR ]  src/components/fa-nav-tab/fa-nav-tab.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-small.class-definitions.css';

[ ERROR ]  src/components/fa-nav-tab/fa-nav-tab.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-bold-medium.class-definitions.css';

[ ERROR ]  src/components/fa-option/fa-option.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-reg-medium.class-definitions.css';

[ ERROR ]  src/components/fa-option/fa-option.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-bold-medium.class-definitions.css';

[ ERROR ]  src/components/fa-option/fa-option.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-reg-small.class-definitions.css';

[ ERROR ]  src/components/fa-page/fa-page.css
           Unable to read css import: @import
           '~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-large.class-definitions.css';

[ ERROR ]  Minify CSS
           Ignoring local @import of
           "src/components/fa-page/~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-large.class-definitions.css"
           as resource is missing.

[ ERROR ]  Minify CSS
           Ignoring local @import of
           "src/components/fa-option/~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-reg-medium.class-definitions.css"
           as resource is missing.

[ ERROR ]  Minify CSS
           Ignoring local @import of
           "src/components/fa-option/~@collectivehealth/dls-typography/dist/dls-typography-falcor-body-bold-medium.class-definitions.css"
           as resource is missing.
```

We have about a dozen CSS files imported this way. Most of them work. These very imports worked previously and stopped working when we updated our type ramp and therefore needed to update the filenames that we were importing. Only Stencil is complaining about the new files. Vanilla, SkateJS, and Angular builds with Rollup, Webpack, Sass, and PostCSS employed in half a dozen various ways are all working fine. These files unambiguously exist as requested at the paths as they should. I've dug into this far enough to see that the error is thrown via `config.sys.resolveModule` and `module._resolveFilename`. 

```
> ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-title-med-small.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-uppercase-med-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-title-med-small.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-reg-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-bold-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-reg-small.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-title-med-small.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-bold-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-reg-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-bold-medium.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-body-reg-small.class-definitions.css && ls components/falcor/dls-falcor-pages/node_modules/@collectivehealth/dls-typography/dist | grep dls-typography-falcor-title-med-large.class-definitions.css

dls-typography-falcor-title-med-small.class-definitions.css
dls-typography-falcor-uppercase-med-medium.class-definitions.css
dls-typography-falcor-title-med-small.class-definitions.css
dls-typography-falcor-body-reg-medium.class-definitions.css
dls-typography-falcor-body-bold-medium.class-definitions.css
dls-typography-falcor-body-reg-small.class-definitions.css
dls-typography-falcor-title-med-small.class-definitions.css
dls-typography-falcor-body-bold-medium.class-definitions.css
dls-typography-falcor-body-reg-medium.class-definitions.css
dls-typography-falcor-body-bold-medium.class-definitions.css
dls-typography-falcor-body-reg-small.class-definitions.css
dls-typography-falcor-title-med-large.class-definitions.css
```

Why?

**Comment by morewry** [comment] 2019-05-06 20:44
I copied `node_modules/@collectivehealth/dls-typography/dist` to `src/typography` and updated the paths from `~@collectivehealth/dls-typography/dist/` to `../../typography/` and ran a build. Most of the errors went away, except for one:

```
[ ERROR ]  src/components/fa-nav-dropdown/fa-nav-dropdown.css
           Unable to resolve node module for CSS @import:
           ~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-small.class-definitions.css
[ ERROR ]  Minify CSS
           Ignoring local @import of
           "src/components/fa-nav-dropdown/~@collectivehealth/dls-typography/dist/dls-typography-falcor-title-med-small.class-definitions.css"
           as resource is missing.
```

I did another find in the codebase to verify I hadn't missed any. I hadn't. So I ran the build again without making _any_ further changes.

```
[39:27.4]  build finished in 13.46 s
```

Huh?

**Comment by morewry** [comment] 2019-05-06 22:38
One of my teammates has helped illuminate why this is happening. If there is no `main` file in the `package.json`, or the `main` file doesn't exist, Stencil can't resolve _any_ files distributed in that package.

**Comment by adrm** [comment] 2020-02-18 11:28
I am having this same problem but only on stencil 1.9 prerelease. If I roll back to 1.8.9 (latest) everything works fine again so it seems like a regression, and maybe is not the same problem as in this issue.

**Comment by bitflower** [comment] 2020-09-05 05:16
@morewry Are you still following the `lerna` approach? I'm trying to join forces on all open issues regarding this.

#1877 
#2587 
#2648
#1379

**Comment by morewry** [comment] 2020-09-07 20:33
@bitflower I am, but we haven't invested further in Stencil. Just continued maintenance; haven't even updated Stencil dependencies  since last year.

**Comment by splitinfinities** [comment] 2021-08-10 19:31
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

We do not support Stencil versions less than v2, and you seem to be using an older version of Stencil. If you can upgrade to the latest version and let me know if this issue still exists, I would appreciate it.

**Comment by splitinfinities** [comment] 2021-08-10 20:02
Duplicate of #2648

If folks can share all their learnings in that issue, I would appreciate it.

**Closed by splitinfinities** 2021-08-10 20:02 UTC
Labels: Feature: Bundling, Feature: Compiler, Repro: No, Integration: Monorepo

**Comment by morewry** [comment] 2021-08-24 18:55
FWIW it's an easy fix to add a `main` entry point when, like for me, that's the cause. Stencil isn't the only thing that struggles to resolve packages if there isn't one. Even if it's a noop file.
