### ISSUE TITLE
bug: Can't execute a custom decorator after @Prop decorator

### ISSUE THREAD

**Issue by luenmuvel** [ionic-team/stencil#4629] opened 2023-07-27 20:33 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.0.0

### Current Behavior

It is not possible to add a custom decorator after the @Prop decorator. Calling to "Custom Decorator" is cancelled for some reason. When I use the same Custom Decorator without the @Prop decorator it does run:

```typescript
@Prop() CustomDecorator() myProp;
```
This doesn't work. But this one does:

```typescript
CustomDecorator()
Another()
Other()
myProp;
```

### Expected Behavior

I would like to be able to work with custom decorators that allow me to perform certain actions before assigning the value to the property, like so:

```typescript
@Prop() ParsingData() MyProperty;
```

In this way, it could execute actions depending on the type of information it receives, before assigning the value to the property "MyProperty"

### System Info

```shell
System: node 16.19.0
    Platform: windows (10.0.19045)
   CPU Model: 12th Gen Intel(R) Core(TM) i7-1265U (12 cpus)
    Compiler: C:\Users\T05656\Pruebas\pruebas\testcomponents\node_modules\@stencil\core\compiler\stencil.js
       Build: 1690208707
     Stencil: 4.0.2
  TypeScript: 5.0.4
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.19.1
```

### Steps to Reproduce

You just need to create a property decorator and add it as the second decorator of your property in your Stencil component.

### Code Reproduction URL

git@github.com:luenmuvel/stencil-decorators.git

**Comment by alicewriteswrongs** [comment] 2023-07-27 20:48
Hey @luenmuvel, sorry you're running into this issue. I believe this is a duplicate of #3831 which is already on our radar - we have plans to fix this and to enable Stencil users to write with custom decorators. Accordingly I'm going to close this, but not because I don't think it's important!

Thanks for filing 🙂

**Closed by alicewriteswrongs** 2023-07-27 20:48 UTC
Labels: triage
