### ISSUE TITLE
component created with stencil not working in IE 11

### ISSUE THREAD

**Issue by rahulgupta-dev** [ionic-team/stencil#3201] opened 2022-01-03 15:36 UTC
I have created a web component using a stencil, but that is not working in IE,, I have added extra config for legacy browser support but still no luck. Below is the error I am getting.
![image](https://user-images.githubusercontent.com/27885144/147949587-6320a3b3-8258-49f8-b350-2b2e6f096694.png)

below is my stencil config

```
import { Config } from '@stencil/core'
import { sass } from '@stencil/sass'
export const config: Config = {
  namespace: 'mep-components',
  srcDir: 'src',
  buildEs5: true,
  extras: {
    cssVarsShim: true,
    dynamicImportShim: true,
    shadowDomShim: true,
    safari10: true,
    scriptDataOpts: true,
    appendChildSlotFix: false,
    cloneNodeFix: false,
    slotChildNodesFix: true,
  },
  outputTargets: [
    {
      type: 'dist'
    },
    {
      type: 'www'
    }
  ],
  devServer: {
    reloadStrategy: 'pageReload',
    port: 4444
  },
  plugins: [sass()]
}
```

**package.json**

```
{
  "name": "web-components",
  "module": "./dist/index.js",
  "collection": "./dist/collection/collection-manifest.json",
  "types": "./dist/types/components.d.ts",
  "version": "1.0.0",
  "description": "",
  "main": "./dist/index.cjs.js",
  "scripts": {
    "start": "stencil build --dev --watch --serve",
    "build": "stencil build --prod && node ./src/tasks/after.build.js",
    "server": "json-server --watch db.json",
    "task": "node ./src/tasks/someTask.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@stencil/core": "^2.6.0",
    "moment-timezone": "^0.5.33",
    "stencil-click-outside": "^1.7.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@stencil/sass": "^1.4.1",
    "@types/jquery": "^3.5.6",
    "chalk": "^4.1.2",
    "workbox-build": "^4.3.1"
  }
}
```

**Comment by rwaskiewicz** [comment] 2022-01-07 16:51
@rahulgupta-dev, I moved this issue to the stencil core repository from the stencil site one (the stencil site is the code for stenciljs.com).

Can you please provide us with a minimal reproduction case? Unfortunately there is not enough information here to fully understand what is occurring.  If you could please create a new stencil project `npm init stencil` and add only the minimum changes required to reproduce this issue, it would greatly be appreciated. Thanks!

**Comment by rwaskiewicz** [comment] 2023-06-28 17:46
I'm going to close this issue due to a lack of reproduction case.

**Closed by rwaskiewicz** 2023-06-28 17:46 UTC
Labels: Awaiting Reply, Resolution: Needs Investigation, deprecated_browser_support
