### ISSUE TITLE
bug: Unable to run Jest spec files from subdirectory or absolute path

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/stencil#3785] opened 2022-11-01 17:40 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

v2.19.2

### Current Behavior

When running `stencil test --spec` in Ionic Framework (`main`), we are only able to run tests for the entire `src/utils` directory with the following command:

```
stencil test --spec --max-workers=2 src/utils/
```

If we provide an additional sub directory or absolute path to our spec file, we receive the following error:

```
  ● Test suite failed to run

    TypeError: virtualMocks.get is not a function

      at Resolver._getVirtualMockPath (node_modules/@jest/core/node_modules/jest-resolve/build/resolver.js:468:25)
```

This occurs with any of the following:

```
stencil test --spec --max-workers=2 src/utils/keyboard/

stencil test --spec --max-workers=2 src/utils/keyboard/test/keyboard.spec.ts
```

The test runs and passes correctly if we run from `src/utils`. 

### Expected Behavior

Developers should be able to run the `stencil test --spec` command with any valid directory or absolute path and the spec files should execute consistently; regardless of if ran exclusively or as part of a larger directory.

### Steps to Reproduce

1. Clone Ionic Framework
2. Checkout `main` branch
3. Run `npm run test.spec src/utils`
4. Observe: Tests run successfully
5. Run `npm run test.spec src/utils/keyboard`
6. Observe: Tests fail with the error mentioned above

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

**Comment by rwaskiewicz** [comment] 2022-11-01 17:42
`npx stencil test --spec --max-workers=2 src/utils/keyboard` works, but `npm run test.spec -- src/utils/keyboard` and `npm run test.spec src/utils/keyboard` do not 🤔

**Comment by alicewriteswrongs** [comment] 2022-11-18 15:53
found a few issues which might be related: https://github.com/playwright-community/jest-playwright/issues/665 and https://github.com/facebook/jest/pull/11267#issuecomment-834101929

Unfortunately upgrading Jest in framework doesn't fix it :/

**Comment by alicewriteswrongs** [comment] 2022-11-18 15:56
also I've found that in addition to the commands @rwaskiewicz mentioned above, the following works:

```
npx stencil test --spec --max-workers=2 src/utils/keyboard/test
```

while the following does not

```
npx stencil test --spec --max-workers=2 src/utils/keyboard/test/
```

the only difference being the trailing slash. So something odd is going on here!

**Comment by alicewriteswrongs** [comment] 2022-11-18 16:08
Ok so this is actually some sort of caching thing, I think on Jest’s side of things but I’m not sure.

Basically if you run a command like this one multiple times in a row:

```
npx stencil test --spec --max-workers=2 src/utils/keyboard
```

it will alternate between running correctly and failing. The same applies for doing npm run tsc.spec , passing other sub-directories, etc.

**Comment by alicewriteswrongs** [comment] 2022-11-18 16:24
Aaaallright so the issue was caused by having different versions of `@jest/core`, on the one hand, and `jest` and `jest-cli` on the other. I updated `jest` and `jest-cli` in a branch in Framework to match the version of `@jest/core` (`27.5.1`) and can no longer reproduce the issue.

**Comment by rwaskiewicz** [comment] 2022-11-29 16:30
Closing, as we received feedback from the Framework team that https://github.com/ionic-team/ionic-framework/pull/26320 resolved the issue

**Closed by rwaskiewicz** 2022-11-29 16:30 UTC
Labels: Bug: Validated
