### ISSUE TITLE
bug: index.js from custom-elements not working standalone

### ISSUE THREAD

**Issue by moren812** [ionic-team/stencil#3207] opened 2022-01-18 13:51 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.12.1

### Current Behavior

The index.js file located in dist/custom-elements doesn't seem to work when used standalone.
Importing the script into a plain HTML file and trying to use a custom element results in a blank space.
The javascript is loaded properly without any errors. Checking the DOM, i can see that the custom-element doesn't get initialized.

### Expected Behavior

After importing the bundled javascript file, we can use the custom-elements normally.

### Steps to Reproduce

stenicl.config.json:
```
    {
      type: 'dist-custom-elements-bundle',
      externalRuntime: false,
    }
```

Compile and import index.js from dist/custom-elements into a plain HTML file.
    
  

### Code Reproduction URL

..

**Comment by rwaskiewicz** [comment] 2022-01-19 13:17
Hey @moren812 👋 

Would you mind adding a reproduction case and updating the GitHub summary for me please? It makes it super easy for the team to be able to dive in and investigate issues when we're able to see the whole picture. Thanks in advance!

**Comment by rwaskiewicz** [comment] 2023-06-28 17:44
I'm going to close this issue due to a lack of reproduction case. Should this reappear in the latest version of Stencil, please feel free to open a new issue. Thanks!

**Closed by rwaskiewicz** 2023-06-28 17:44 UTC
Labels: Awaiting Reply, Resolution: Needs Investigation
