### ISSUE TITLE
Feature request: Configure builds to include source maps

### ISSUE THREAD

**Issue by petermikitsh** [ionic-team/stencil#1486] opened 2019-04-30 03:58 UTC
**Stencil version:**

```
 @stencil/core@0.18.0
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Components built with stencil produce minified, sourcemap-less code.

**Expected behavior:**

Builds are configurable to output source maps. In the case that #1485 is rejected, providing source maps for builds would enhance the developer experience of consuming stencil components. Currently, when errors are thrown, it is difficult to trace their origin from minified code with no source maps.

**Comment by jthoms1** [comment] 2019-04-30 13:31
Duplicate of #1255

**Closed by jthoms1** 2019-04-30 13:31 UTC
Labels: triage
