### ISSUE TITLE
Button form attribute does not render/missing after compiled in DOM

### ISSUE THREAD

**Issue by liho98** [ionic-team/stencil#2703] opened 2020-10-14 16:51 UTC
**Stencil version:**

```
 @stencil/core@ <^1.17.3>
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
![image](https://user-images.githubusercontent.com/44250267/96020028-06f11e00-0e80-11eb-9887-c8e9be6a9d28.png)
![image](https://user-images.githubusercontent.com/44250267/96020101-1d977500-0e80-11eb-92c9-576cb26f08fa.png)
you can see the form attribute is missing after compile in DOM.

**Expected behavior:**

I want the form attribute to work, so i can handle multiple form submission.

**Steps to reproduce:**
just add form attribute in <button> tag

**Related code:**

```tsx
      <Host style={{ all: "unset" }}>
        <button
          type={this.type}
          style={this.buttonStyle}
          class={`rm-button--button ${this.class}`}
          value="Submit"
          form="form1"
        >
          <slot></slot>
        </button>
      </Host>
```

**Other information:**

**Comment by claviska** [comment] 2020-11-17 15:56
Confirmed with a minimal component:

```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'my-button',
  shadow: true,
})
export class AppHome {
  render() {
    return <button form="form-id-here">Submit</button>;
  }
}
```

The resulting markup looks like this:

<img width="369" alt="CleanShot 2020-11-17 at 10 55 21@2x" src="https://user-images.githubusercontent.com/55639/99413093-69946a00-28c3-11eb-85ed-99a780e162b3.png">

**Comment by claviska** [comment] 2020-11-17 16:22
@adamdbradley any idea what might be causing this? I'm happy to take a stab at it if you can point me in the right direction.

**Comment by thccorni** [comment] 2022-02-25 15:18
As a workaround I managed to use `ref` to get it to work:
```tsx
<button
  ref={(btn) => btn?.setAttribute('form', 'form-id-here')}
>
  Submit
</button>
```
But it is a little ugly, I know.

**Comment by KevinCarnaille2** [comment] 2022-08-19 12:39
FYI, still having the issue in Stencil `2.17.3` :) 

@thccorni workaround is working ;)

**Comment by DavideMininni-Fincons** [comment] 2022-08-24 07:47
Hello guys! 
Yesterday I found this issue while having some trouble setting the form attribute on [this component](https://github.com/lyne-design-system/lyne-components/tree/master/src/components/sbb-link), based on Stencil.

The walkaround from @thccorni seems to work (thank you!)

If it could help, I debugged a bit the @stencil/core/internal/client/index.js;
at line 398 you could see that all params looks good and the set should be done.. but if I move one line ahead, and check for elm[memberName], it's null. I'm adding two screenshots.

<img width="574" alt="form-button-bug" src="https://user-images.githubusercontent.com/101575400/186361096-913fa11e-ec5d-411f-94c3-21479879baad.png">

<img width="577" alt="form-button-bug2" src="https://user-images.githubusercontent.com/101575400/186361102-003cb8d0-b86d-4769-af81-704fbef62d18.png">

**Comment by rwaskiewicz** [comment] 2022-08-25 13:04
Thanks all! I've confirmed this is an issue with the minimal reproduction case above. I'm going to label this for the team to look into further

**Comment by timsnadden** [comment] 2023-01-19 02:29
This also applied to inputs

**Comment by Adamkillander96** [comment] 2023-12-15 10:06
This issue is still present in @stencil/core@^4.7.2

We worked around it by checking after render and adding 'form' with `setAttribute` function.

```
componentDidRender() {
  if (this.form) {
    this.hostElement.querySelector('button').setAttribute('form', this.form);
  }
}
```

**Comment by christian-bromann** [comment] 2024-08-26 18:55
A fix for this bug has been published in Stencil [`v4.21.0`](https://github.com/ionic-team/stencil/releases/tag/v4.21.0)!

**Closed by christian-bromann** 2024-08-26 18:55 UTC
Labels: Bug: Validated

**Comment by lucafoscili** [comment] 2024-11-26 10:53
Hi @christian-bromann,

I'm writing to ask for clarification regarding a change introduced in [PR #5947](https://github.com/ionic-team/stencil/pull/5947) ("Only use setter if existing"). It seems that this fix is causing the serialization of objects and functions assigned to HTML elements through JSX in our project.

Previously, we could assign functions or objects directly to properties on HTML elements via JSX without them being serialized. For example:

```typescript
<div
  kup-get-cell-props={() => {
    return props;
  }}
  /* other props */
>
  {/* children */}
</div>
```

After updating to Stencil version 4.21.0 and above, these properties are being serialized and added as attributes with stringified values, resulting in:

```html
<div kup-get-cell-props="[object Object]" /* other attributes */>
  <!-- children -->
</div>
```

This change causes the functions and objects to become unusable, as they are no longer accessible as properties on the element.

I tried setting the properties directly on the HTMLElement using ref, but observed similar behavior:

```typescript
ref={(el: any) => { 
  if (el) {
    this.#thRefs.push(el);
    el.dataCell = column;  // Results in datacell="[object Object]"
    el.dataColumn = column.name; // Results in datacolumn="Actual name of the column"
  }
}}
```

Even when setting properties via ref, the properties are converted to attributes with stringified values, which isn't the desired behavior.

Questions:

- Is this change in behavior intentional due to stricter property handling in Stencil's runtime?

- If so, is there a recommended approach to attach complex data (like objects or functions) to HTML elements without them being serialized as attributes?

- Are there any workarounds or configurations that can help restore or simulate the previous behavior?


This change significantly affects our codebase, as we rely on attaching data to elements in this manner. Refactoring our code to accommodate this new behavior would require considerable effort.
If this change is intended and there's no feasible workaround, we may need to remain on Stencil version 4.20.0, where our code continues to work as expected.
I appreciate the continuous improvements to Stencil and understand the importance of adhering to web standards. I'm looking forward to your guidance on how best to tackle this issue!

Thank you for your time!

**Comment by christian-bromann** [comment] 2024-12-10 19:04
@lucafoscili thanks for your feedback, mind raising a new issue with these information?
