### ISSUE TITLE
Can't add external librarry

### ISSUE THREAD

**Issue by vovikdrg** [ionic-team/stencil#424] opened 2018-01-17 03:58 UTC
**Stencil version:**
-- @stencil/core@0.1.5

**I'm submitting a:**

- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
And i am getting an error 

[ ERROR ]  Error parsing: ...../dist/collection/components/my-app/my-app.js, line: 2, column: 9

[ ERROR ]  rollup died at ......\node_modules\@stencil\core\dist\compiler\index.js:1781:19 at
           Generator.throw (<anonymous>) at rejected
           (.......\node_modules\@stencil\core\dist\compiler\index.js:1748:65) at <anonymous>

**Expected behavior:**
I should be able to use external librarries

**Steps to reproduce:**
`npm install oidc-client`
then in component
`import { UserManager, UserManagerSettings, User } from 'oidc-client';`

```
componentDidLoad() {
     var config = {
      authority: "http://localhost:5000",
      client_id: "js",
      redirect_uri: "http://localhost:5003/callback.html",
      response_type: "id_token token",
      scope: "openid profile api1",
      post_logout_redirect_uri: "http://localhost:5003/index.html",
    };
    var mgr = new UserManager(config);
    mgr.getUser().then(function (user) {
      if (user) {
        console.log("User logged in", user.profile);
      }
      else {
        mgr.signinRedirect();
      }
    });
}

```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by jgw96** [comment] 2018-01-17 16:57
Hello, thanks for opening an issue with us! Could you post a repo we could use to reproduce this issue? Also, for the team, linking this issue https://github.com/ionic-team/stencil/issues/162

**Comment by vovikdrg** [comment] 2018-01-17 23:20
@jgw96  hey, I've cloned your github PWA project and just installed **oidc-client** npm package 
Then in my-app.tsx i've changed code 

Added import

`import { UserManager, UserManagerSettings, User } from 'oidc-client';`

replaced componentDidLoad method

```
componentDidLoad() {
     var config = {
      authority: "http://localhost:5000",
      client_id: "js",
      redirect_uri: "http://localhost:5003/callback.html",
      response_type: "id_token token",
      scope: "openid profile api1",
      post_logout_redirect_uri: "http://localhost:5003/index.html",
    };
    var mgr = new UserManager(config);
    mgr.getUser().then(function (user) {
      if (user) {
        console.log("User logged in", user.profile);
      }
      else {
        mgr.signinRedirect();
      }
    });
}
```

If you still need repo then i will do.

**Comment by vovikdrg** [comment] 2018-01-18 23:08
Hey @jgw96  can you reproduce this one?

**Comment by jthoms1** [comment] 2018-01-23 21:00
I am working on some things in this space right now.  Hopefully I will be able to test and reproduce tomorrow. Thanks!

**Comment by jgw96** [comment] 2018-01-29 16:35
Note to self, test this today with the new code splitting implementation.

**Comment by jgw96** [comment] 2018-02-09 17:25
@jthoms1 update on this issue. I was able to get an app to build succesfully with this library by using this import ``` import User from 'oidc-client';``` but i then get this runtime error ``` TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined``` . @vovikdrg have you seen this issue before with this library?

**Comment by vovikdrg** [comment] 2018-02-12 11:56
@jgw96 sorry for long response. I am able to use this vue.js and i dont have any issues.

**Comment by jthoms1** [comment] 2018-02-21 14:28
I have the same results as @jgw96. I am able to get it imported but I receive a runtime error.

**Comment by jgw96** [comment] 2018-02-21 22:01
Hello all! At this point, it looks like this is a runtime issue with that library and not specific to Stencil. Because of this, I am going to close this issue for now. Thanks for using Stencil!

**Closed by jgw96** 2018-02-21 22:01 UTC
Labels: bug
