### ISSUE TITLE
One or more of the Workbox libraries could not be copied over to the destination directory

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil#409] opened 2018-01-12 21:37 UTC
<img width="935" alt="screenshot 2018-01-12 15 37 46" src="https://user-images.githubusercontent.com/11214/34896220-8cb98180-f7ae-11e7-9f4b-1d104957a918.png">

**Comment by jgw96** [comment] 2018-01-12 21:42
Note to self, check workbox repo issues

**Comment by mlynch** [comment] 2018-01-12 21:43
Happens only if the workbox stuff was previously copied over. To reproduce: `npm run build` twice from a fresh stencil app

**Comment by jgw96** [comment] 2018-01-12 22:08
Talking to the workbox team about this to see if this is expected behavior from workbox

**Comment by jgw96** [comment] 2018-01-17 17:01
Note to self. Discussed with adam, probably just change this to a warning for now since this is 99% a workbox thing.

**Comment by jgw96** [comment] 2018-01-17 20:11
Implemented a workaround for this issue which will be in the next release. Thanks for using Stencil!

**Closed by jgw96** 2018-01-17 20:11 UTC
