### ISSUE TITLE
Stencil + Lerna integration

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil#2648] opened 2020-08-24 19:03 UTC
**Stencil version:**

```
 @stencil/core@2.0.0-6
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
I have two branches on [this repo](https://github.com/splitinfinities/stencil-lerna-bugs) that try to document Lerna integration issues: 
 - [NPM](https://github.com/splitinfinities/stencil-lerna-bugs/tree/npm)
 - [Yarn Workspaces](https://github.com/splitinfinities/stencil-lerna-bugs/tree/yarn)

Within this repo, I have a small tree: a `fake-app` component that includes the `dependent-component` and `another-dependent` packages, and uses those element in it's render function. The `another-dependent` has a `deep-dependent` in it's render function.

Each of these components were made with `npm init stencil component component-name`, and brought up to spec from 1.17.3 to what 2.0.0-6 asks for. 

with the NPM flow right out the gate, it seems the package references the collection, but collection isn't available:
`GET http://localhost:3333/another-dependent/dist/collection/components/another-dependent/another-dependent.js net::ERR_ABORTED 404 (Not Found)`

**Expected behavior:**

Through this I found a few issues:
- [ ] The collection entries in package.json will need the same validation treatment that Stencil outputs when `main` or `module` are incorrectly set. 
- [ ] I looked into the dist folder and only had 3 folders - the component's name, custom-elements, and types. There was no collection folder. 
- [ ] ...incoming

I'm going to keep this open for other issues I may find and note my edits. 

**Steps to reproduce:**
For the NPM branch:
 - Check out [NPM](https://github.com/splitinfinities/stencil-lerna-bugs/tree/npm)
 - Do `npm run bootstrap && npm run build`
 - Run `npm start` to get the server started. 
 - Make edits to any given component, and test changes.  

For the Yarn branch:
 - Check out [Yarn Workspaces](https://github.com/splitinfinities/stencil-lerna-bugs/tree/yarn)
 - Do `yarn bootstrap && yarn build`
 - Run `yarn start` to get the server started. 
 - Make edits to any given component, and test changes.  

**Other information:**
You'll notice that only the app pops open in your browser. Look in the stencil.config.ts files for the ports for each individual component, if needed. The packages are imported in the src/index.ts file.

**Comment by splitinfinities** [comment] 2020-08-24 19:08
Edit: fixed "another-component" to be "another-dependent"

**Comment by bitflower** [comment] 2020-08-24 20:53
Thanks for putting together this issue!

The same behaviour of dependent packages' changes not being recognized can also be reproduced here:*https://github.com/bitflower/stencil-lerna

**Comment by rwaskiewicz** [comment] 2022-02-07 13:07
Reopening, I don't think we want Ionitron closing issues like this.  Going to give it some thought as to the best way to implement this

**Comment by bitflower** [comment] 2022-02-07 15:18
Also I think one should probably check for all alternatives or partial solutions like `turborepo`, `yarn workspaces`, `npm i file:` etc.. Maybe more a todo on my aside - anyway a set of example repos showcasing this could help Stencil adoption.

**Comment by sardapv** [comment] 2022-02-07 18:47
era of lerna is gone. That package has no maintainer since 8 months. Nx has great support with stencil.

**Comment by rwaskiewicz** [comment] 2023-09-07 13:08
Hey folks 👋 

I'm going to be closing this in favor of https://github.com/ionic-team/stencil/issues/1877 to try to consolidate things a bit - please upvote/follow https://github.com/ionic-team/stencil/issues/1877 in lieu of this issue. Thanks!

**Closed by rwaskiewicz** 2023-09-07 13:08 UTC
Labels: Feature: Want this? Upvote it!
