### ISSUE TITLE
How to use multiple styleUrls? Constructor for "*#undefined" was not found at initializeComponent

### ISSUE THREAD

**Issue by JilReg** [ionic-team/stencil#1626] opened 2019-06-12 05:10 UTC
**Stencil version:**

```
@stencil/core@1.0.0-beta.8
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm trying to use multiple styleUrls an get the error:

<img width="1155" alt="Bildschirmfoto 2019-06-11 um 13 29 40" src="https://user-images.githubusercontent.com/33420668/59324486-644eeb00-8cdf-11e9-80e8-07a24bafb0f7.png">

**Expected behavior:**

Not getting the error ; ) and using one or another styleUrl

**Steps to reproduce:**

```
npm init stencil
✔ Pick a starter › component
```
- add two style files (`my-component.ios.css` and `my-component.md.css`) in `src/components/my-component` 

- in `src/components/my-component/my-component.tsx` change `styleUrl: 'my-component.css'` to   
```
styleUrls: {
    ios: 'my-component.ios.css',
    md: 'my-component.md.css',
  },
```
and add  
```
@Prop() mode: string;

  hostData(){
    return {
      class: {
        [`${this.mode}`]: true
      }
    }
  }
```

Try to use the component with one of the styleUrls in `src/index.html` via `<my-component mode="ios" first="Stencil" last="'Don't call me a framework' JS"></my-component>`

**Related code:**

```tsx
// insert any relevant code here
```

**Comment by stanley85** [comment] 2019-08-01 10:45
I dont think this is possible at the moment.  I guess you wrote this as feature request, because its not a bug. Some build in method to flip css would be nice.

**Comment by felipesousa** [comment] 2019-08-12 21:31
I'm having the same one.

When a component is using just `styleUrl`, everything works fine, but when I use `styleUrls` instead, I'm receiving a message error `*#undefined" was not found at initializeComponent`.

**Comment by stanley85** [comment] 2019-09-11 07:03
Where did you read that this is an option?

**Comment by adamdbradley** [comment] 2020-01-15 00:38
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-15 00:38 UTC
Labels: triage
