### ISSUE TITLE
baseUrl broke since 0.18.1

### ISSUE THREAD

**Issue by riovir** [ionic-team/stencil#1589] opened 2019-06-04 11:40 UTC
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
The output is now placed inside a directory derived from `baseUrl`, while the script (and possibly style) imports not starting with the `baseUrl`.

**Expected behavior:**
Pretty much the exact opposite.

**Steps to reproduce:**
Using the provided config with both `@stencil/core@0.18.1` and `@stencil/core@1.0.0`:

The `0.18.1` build correctly puts files directly in the `www/` directory. Where `index.html` requests scripts from URLs starting with `/my-component-pack`. This makes GitLab pages happy.

The `1.0.0` build puts files inside `www/my-component-pack/` with `my-component-pack` nowhere to be mentioned in the `index.html`. Now I'm staring at a 404 page on GitLab pages.

**Related code:**

```ts
import { Config } from '@stencil/core';

export const config: Config = {
  // ...
  outputTargets:[
    { type: 'www', baseUrl: '/my-component-pack' }
  ]
};
```

**Other information:**

**Comment by thegecko** [comment] 2019-06-21 11:45
I can confirm the same issue.
The `dir` option is used to specify where to put the files, it shouldn't have the `baseUrl` option appended to the path.

e.g.
```json
outputTargets: [
    {
        type: 'www',
        dir: 'output',
        baseUrl: '/my-web'
    }
]
```

Should generate the site in the `output` folder with source links pre-pended with `/my-web`.

However, the site is put in the folder `output\my-web`, so the source links don't match where the site lives.

**Comment by thegecko** [comment] 2019-06-21 12:03
The issue is here:

https://github.com/ionic-team/stencil/blob/master/src/compiler/config/validate-outputs-www.ts#L50

And was introduced in this commit:

https://github.com/ionic-team/stencil/commit/893747af1232bdc1c954d447e2de311ff1ed99cb#diff-a0d77f1423c9e419af5ba951e368d43eR48

**Comment by riovir** [comment] 2019-07-01 12:50
Just checked the latest `@stencil/core@1.1.3` version. Unfortunately still broken.

**Comment by adamdbradley** [comment] 2020-01-02 02:25
This should be fixed in the latest version. If it's still a problem, would you be able to create an issue with a thorough description on how to replicate this? Thanks

**Closed by adamdbradley** 2020-01-02 02:25 UTC
Labels: triage
