### ISSUE TITLE
Debug Failure. Literal kind 'undefined' not accounted for

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/stencil#201] opened 2017-10-02 22:54 UTC
**Stencil version:**

```
@stencil/core@0.0.6-4
```

**I'm submitting a ...**
[x] bug report

**Current behavior:**
If you implement a `toString()` method in a component then the component fails to build.

**Expected behavior:**
It should be possible to define a `toString()` method.

**Steps to reproduce:**
1. Start with the stencil-app-starter
2. Add a `toString()` method like in the following sample
3. `npm start`

**Related code:**

```typescript

// my-name.tsx
// from stencil-app-starter
@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss'
})
export class MyName {

  @Prop() first: string;

  @Prop() last: string;

  toString() {
    return this.first;
  }

  render() {
    return (
      <div>
        Hello, my name is {this.first} {this.last}
      </div>
    );
  }
}
```

If you run `nom start` then you get the following message:

```
[38:17.6]  changed file: my-name.tsx
[38:17.6]  rebuild, dev mode, started ...
[38:17.6]  compile started ...
[38:18.7]  compile finished in 1.15 s

[ ERROR ]  Debug Failure. Literal kind 'undefined' not accounted for. at Object.getLiteralText
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:7196:18) at
           getLiteralTextOfNode
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:69039:23) at
           getLiteralTextOfNode
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:69036:28) at
           emitLiteral (/Users/cjorasch/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:67373:24)
           at pipelineEmitExpression
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:67271:28) at
           pipelineEmitWithHint
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:67014:49) at
           emitNodeWithSourceMap
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:64399:24) at
           pipelineEmitWithSourceMap
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:67004:17) at
           emitNodeWithNestedComments
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:64714:17) at
           emitNodeWithSynthesizedComments
           (/Users/x/Projects/stencil-app-starter/node_modules/typescript/lib/typescript.js:64664:13)

```
**Other information:**

If I change the method name from `toString()` to 'toString2()' then the build works again.

If I change the method to a lambda instance then the build works again.  E.g. `public toString = () => { ... }`.

Note: this also happens for classes that are not even components.  I had another class in the same project folder that had a `toString` method and this caused the problem even when the class was not being used anywhere in the Stencil application.  This made it very difficult to track down the error (since the message does not reference a source) but seems like maybe it is something the Stencil compiler is doing with any class it finds.

**Comment by jthoms1** [comment] 2017-10-12 19:53
Looks like toString is reserved for HTMLElements.  We are looking into a way to prevent this from occuring. I get why it would cause an error for Stencil Components but not sure about other classes you might have.

**Comment by cjorasch** [comment] 2017-10-12 21:22
I think only methods marked with `@Method()` are proxied in the derived HTMLElement.

**Comment by jthoms1** [comment] 2017-10-12 22:57
You are correct sorry wrong conclusion! This looks like a Typescript error to me. I will do some more digging and open an issue with them. Not sure why they are treating toString as special in this case but I am able to reproduce.

**Comment by jgw96** [comment] 2017-10-30 20:35
Gonna label this one as blocked for now since it is an issue in typescript itself.

**Comment by jthoms1** [comment] 2017-11-21 16:41
It looks like this is a won't fix from Typescript so I am going to close this issue. https://github.com/Microsoft/TypeScript/issues/1415

**Closed by jthoms1** 2017-11-21 16:41 UTC
Labels: blocked, bug

**Comment by cjorasch** [comment] 2017-11-21 17:11
You might want to add a note somewhere in the docs about the issue.  It took me forever to find the source of the problem since it was so unexpected.  Most of Stencil is pretty straightforward but there still seem to be lots of strange quirks that are very hard to diagnose.

If you implement a `toString` method in any class (not just components) the build will fail.  I think this would also include any imports so it might not be something that you can't completely control.

I am still not sure how this relates to the typescript issue you mentioned.  That discusses why an index signature must be a string or number vs. any with an object that implements toString but that doesn't seem to be happening here.  The code compiles fine with `tsc`.
