### ISSUE TITLE
NodeJS Standard Lib Calls within Prerenders

### ISSUE THREAD

**Issue by harrysolovay** [ionic-team/stencil#1857] opened 2019-09-09 22:33 UTC
**Stencil version:**

```
 @stencil/core@1.3.0
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I have a function which makes use of the NodeJS standard lib to gather and process markdown into a simple JS object. I'd love to be able to use this function from within my component's prerendered scope:

```ts
import {Component, h, Build} from '@stencil/core';
import getMarkdownNodes from '../../api';

@Component({tag: 'app-home'})
export class AppHome {
  async componentWillRender() {
    if (!Build.isBrowser) {
      const api = getMarkdownNodes();
      console.log(api);
    }
  }

  render() {
    return (
      <div class='app-home'>Hi!</div>
    );
  }
}

```

**Expected behavior:**

I hoped that––because the prerendering process is a node process––that I'd be able to make use of the NodeJS standard lib from within the `getMarkdownNodes` function... but this isn't the case :/

**Other information:**

Can we enable this usage?

If so, I owe you all coffee & pastries!

**Comment by stanley85** [comment] 2019-09-10 14:10
Just by reading this I am not sure if you can setup componentWillRender to be async by writing async infront. By the docs the lifecycle methods need to return a promise to be waited on. For your example this should be tomething like this i guess:

`import {Component, h, Build} from '@stencil/core';
import getMarkdownNodes from '../../api';

@Component({tag: 'app-home'})
export class AppHome {

  componentWillRender() {
    if (!Build.isBrowser) {
      return getMarkdownNodes()
        .then(response => response.json())
        .then(api=> {
          console.log(api);
      });      
    }
  }

  render() {
    return (
      <div class='app-home'>Hi!</div>
    );
  }
}`

getMarkdownNodes() need to return a promise for this to be working.
See https://stenciljs.com/docs/component-lifecycle#async-lifecycle-methods

**Comment by harrysolovay** [comment] 2019-09-10 15:24
@stanley85 true, there’s no need for it to be async in this case... but it shouldn’t have any bearing on whether the ‘fs’-using function is successfully run, should it?

**Comment by stanley85** [comment] 2019-09-11 07:00
Ah now i get it, the fn is called but the environment is unaware of the node lib? You like to enhance the prerendered state with some dynamic data, fetched from the api? You need to fetch the data from the api - not importing the serverside code to your component. What is the benefit? First draw with differen data for each route?

**Comment by alicewriteswrongs** [comment] 2023-01-19 16:40
@harrysolovay thanks for filing this feature request, and sorry that it took a while for someone from the Stencil team to get back to you. I've labeled it as a feature request so we can get a sense of the demand from the community for this kind of feature. When adding features to Stencil we have a balance a number of different considerations, but community demand and interest is an important factor.

That said, at present we don't have an intention as a team to support using node.js code within Stencil components.

Thanks for filing, and sorry again about the wait!

**Comment by christian-bromann** [comment] 2024-06-14 22:57
Hi [Issue Author] 👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Furthermore there is no reproducible example we could use to investigate this further. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!

**Closed by christian-bromann** 2024-06-14 22:57 UTC
Labels: Feature: Want this? Upvote it!
