### ISSUE TITLE
Build fails for test but not for normal build

### ISSUE THREAD

**Issue by gtranter** [ionic-team/stencil#2094] opened 2019-12-20 20:07 UTC
**Stencil version:**
```
 @stencil/core@1.8.1
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If the package.json "types" property is set to "dist/types/index.d.ts" (instead of components.d.ts), when working from clean (not yet built), test will not run because the build process fails even though build works fine by itself.

**Expected behavior:**
It should build and run test just fine.

**Steps to reproduce:**
In package.json set `"types": "dist/types/index.d.ts"` then run `npx stencil test --spec --e2e`.

**Other information:**
Note that `npx stencil build --dev` by itself does not fail. This only happens when test does the build.

***Stack trace:***
```
$ npx stencil test --spec --e2e
[59:01.4]  @stencil/core v1.8.1
[59:01.8]  testing e2e and spec files
[59:01.8]  build, ui-components, dev mode, started ...
[59:03.9]  transpile started ...
[59:12.4]  transpile finished in 8.54 s
[59:12.6]  copy started ...
[59:12.6]  generate styles started ...
[59:12.7]  bundling components started ...
[59:14.4]  copy finished (210 files) in 1.73 s
[59:16.8]  generate styles finished in 4.12 s
[59:17.7]  bundling components finished in 5.00 s

[ ERROR ]  Package Json: ./package.json:37:3
           package.json "types" property is set to "dist/types/index.d.ts" but
           cannot be found. It's recommended to set the "types" property to:
           dist/types/components.d.ts

     L37:    "types": "dist/types/index.d.ts",

[59:18.3]  build failed in 16.49 s
```

**Comment by rwaskiewicz** [comment] 2022-08-29 16:32
Hey @gtranter 👋 

I apologize that it took so long for someone on the team to get back to you regarding this issue.

It appears that as of Stencil 2.17, this issue has been resolved - or at the least I'm unable to reproduce it following the steps you provided. The `types` field appears to be set to `"dist/types/index.d.ts"` by default now. When the `types` field is set to a non-existent file, the build and test scripts both fail in the same regard:
```
➜  ts-inst git:(main) ✗ npm t

> ts-inst@0.0.1 test
> stencil test --spec --e2e

[29:49.6]  @stencil/core
[29:49.7]  v2.17.4 🐞
[29:49.8]  testing e2e and spec files
[29:50.5]  build, ts-inst, dev mode, started ...
[29:50.6]  transpile started ...
[29:51.6]  transpile finished in 1.03 s
[29:51.6]  copy started ...
[29:51.6]  generate custom elements started ...
[29:51.6]  generate lazy started ...
[29:51.7]  copy finished (0 files) in 93 ms
[29:51.8]  generate custom elements finished in 181 ms
[29:51.9]  generate lazy finished in 279 ms

[ ERROR ]  Package Json: package.json:9:3
           package.json "types" property is set to "dist/types/infdex.d.ts" but cannot be found. It's recommended to
           set the "types" property to: ./dist/types/components.d.ts

      L8:  "es2017": "dist/esm/index.mjs",
      L9:  "types": "dist/types/infdex.d.ts",
     L10:  "collection": "dist/collection/collection-manifest.json",

[29:51.9]  build failed in 1.37 s

➜  ts-inst git:(main) ✗ npm run build

> ts-inst@0.0.1 build
> stencil build --docs

[30:00.6]  @stencil/core
[30:00.7]  v2.17.4 🐞
[30:01.5]  build, ts-inst, prod mode, started ...
[30:01.5]  transpile started ...
[30:02.5]  transpile finished in 1.09 s
[30:02.5]  copy started ...
[30:02.5]  generate custom elements started ...
[30:02.6]  generate lazy started ...
[30:02.6]  copy finished (0 files) in 88 ms
[30:02.8]  generate custom elements finished in 284 ms
[30:03.0]  generate lazy finished in 450 ms

[ ERROR ]  Package Json: package.json:9:3
           package.json "types" property is set to "dist/types/infdex.d.ts" but cannot be found. It's recommended to
           set the "types" property to: ./dist/types/components.d.ts

      L8:  "es2017": "dist/esm/index.mjs",
      L9:  "types": "dist/types/infdex.d.ts",
     L10:  "collection": "dist/collection/collection-manifest.json",

[30:03.0]  build failed in 1.56 s
``` 

I'm going to close this ticket as a result. If you feel this is still a problem, please feel free to open a new issue! Thanks!

**Closed by rwaskiewicz** 2022-08-29 16:32 UTC
Labels: triage
