### ISSUE TITLE
Broken Redux package in 0.1.1

### ISSUE THREAD

**Issue by bfmatei** [ionic-team/stencil#400] opened 2018-01-09 11:10 UTC
**Stencil version:**
```
 @stencil/core@0.1.1
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**
After updating from 0.1.1-0 to 0.1.1 version of Stencil, the built app is not working anymore. The error is pretty simple: 
```
ReferenceError: process is not defined. 
```

Also, sometimes the CLI is showing the following warning. It does not appear at first build (given the --watch flag), but after 3-4 recompiles.
```
[ WARN  ]  app-header, app-menu, app-private-module: 'default' is not exported by 'node_modules/redux/es/index.js' 
```

I guess this is cased by the migration to esmodules.

**Steps to reproduce:**
1. Clone the following repo: https://github.com/bfmatei/stencil-boilerplate
   ```bash
   git clone https://github.com/bfmatei/stencil-boilerplate
   ```
2. Install dependencies: 
   ```bash
   npm i
   ```
3. Run the project in development mode:
   ```bash
   npm run dev
   ```
4. Observe the main issue: process is not defined
5. Add some whitespaces in the JS files a couple of times so the project gets recompiled. Observe the secondary issue.
6. Add the following piece of code in index.html:
   ```html
   <script>
     process = {
       env: {
         NODE_ENV: 'development'
       }
     };
   </script>
   ```
7. Refresh the browser :)

**Comment by adamdbradley** [comment] 2018-01-09 12:29
I tried to replicate the issue above, but running through the same steps I wasn't able to get any errors. Is there anything else that's different? What node version are you using?

**Comment by bfmatei** [comment] 2018-01-09 12:45
I am using node v8.9.1 and it is reproducing in with v9.3.0 also (both installed on macOS 10.13.2). The above steps were right, but I left the process definition in index.html file (as a temporary workaround). Please do a pull and try again.

**Comment by jgw96** [comment] 2018-01-09 16:35
Hey @bfmatei , thanks for the update. I was just able to reproduce this issue in the latest release of stencil with your provided instructions. We will get it fixed up.

**Comment by jgw96** [comment] 2018-01-09 16:36
Update for team: just talked to Josh about this on slack and assigned it to him.

**Comment by akserg** [comment] 2018-01-12 08:00
Hi

Changes in Stencil version 1.2 and up, are not compatible with Redux. After migration to latest Stencil the Redux doesn't work because of the following issue:
```
app.core.js:1672 ReferenceError: process is not defined
    at my-app.js:744
then.catch.err @ app.core.js:1672
```

Redux implementation contains conditional compilation based on the value in `process.env.NODE_ENV`:
```
/*
* This is a dummy function to check if the function name has been altered by minification.
* If the function has been minified and NODE_ENV !== 'production', warn the user.
*/
function isCrushed() {}

if (process.env.NODE_ENV !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
  warning('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
} 
```

The Stencil before 1.2 replaced the `process.env.NODE_ENV` at build time ([2b55142](https://github.com/ionic-team/stencil/commit/2b55142)):

```
export function buildExpressionReplacer(config: BuildConfig, input: string) {
    return input
        .replace(
            /process.env.NODE_ENV(\s*)(===|==)(\s*)['"`]production['"`]/g,
            (!config.devMode).toString()
        )
        .replace(
            /process.env.NODE_ENV(\s*)(!==|!=)(\s*)['"`]development['"`]/g,
            (!config.devMode).toString()
        )
        .replace(
            /process.env.NODE_ENV(\s*)(===|==)(\s*)['"`]development['"`]/g,
            (config.devMode).toString()
        )
        .replace(
            /process.env.NODE_ENV(\s*)(!==|!=)(\s*)['"`]production['"`]/g,
            (config.devMode).toString()
        );
}
```
Now, that piece of functionality is gone.

**Comment by jthoms1** [comment] 2018-01-12 19:11
Yep it appears this was removed.  It is a valid bug and we will be fixing very soon.

**Comment by jthoms1** [comment] 2018-01-12 19:30
This issue is fixed with commit 688fc88b23686b0adf13016cf8bff9db2f24394b.  I also just released 0.1.4 which includes this fix.  Thanks

**Closed by jthoms1** 2018-01-12 19:30 UTC
Labels: bug

**Comment by akserg** [comment] 2018-01-13 09:29
Thanks.

**Comment by bfmatei** [comment] 2018-01-13 09:35
Thanks! I can confirm that the issue is solved in the latest build.
