### ISSUE TITLE
Not able to use 3rd javascript party library in stencil web component

### ISSUE THREAD

**Issue by ArunSiddu** [ionic-team/stencil#2073] opened 2019-12-10 12:22 UTC
**Stencil version:**

```
 @stencil/core@1.1.6
```

**I'm submitting a:**

[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

In my angular js application, we are using stencil web components recently.
where in the existing angular js app, we used dropzone for file upload.

Now, I'm trying to use a javascript file upload library dropzone (https://gitlab.com/meno/dropzone) in one of my web component render() {}, but it is not working.
Its is working fine in normal javascript page. 

**Expected behavior:**

Need to use dropzone library, in the stencil web component as similar to js and angular js.

**Steps to reproduce:**

Create a normal web component and need to include the dropzone js library (https://gitlab.com/meno/dropzone) 

**Related code:**

`  render() {
    return (
      <div>
        <form action="/file-upload123" class="dropzone">
          <div class="fallback">
            <input name="file" type="file" multiple />
          </div>
        </form>
      </div>
    );
  }`

**Other information:**

Is there any stencil web component already available for file uploading, similar to dropzone?

**Comment by MatheusBordin** [comment] 2020-01-10 13:32
Hi @ArunSiddu , your component is created with `shadow: true`? Maybe the dropzone can't find element because that is encapsulated in the Shadow DOM. Try disable this option or use the programmatic way (Get element by reference and pass as first argument of Dropzone class).

**Comment by rwaskiewicz** [comment] 2023-07-27 14:09
Hey there 👋 

I apologize it took so long for someone on the team to acknowledge this issue. At this time, Stencil v1 and lower is no longer supported.  As a result, I'm going to close this issue.

If this issue is still occurring in Stencil v4, can you please create a new issue for us with a minimal reproduction case? Thanks!

**Closed by rwaskiewicz** 2023-07-27 14:09 UTC
Labels: triage
