### ISSUE TITLE
Renaming custom elements

### ISSUE THREAD

**Issue by SheepFromHeaven** [ionic-team/stencil#2862] opened 2021-03-22 15:10 UTC
**Stencil version:**
```
 @stencil/core@2.4.0
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Building one component library as the custom-elements-bundle output and importing it to define it with ANOTHER tag name than defined in the decorator is not working.
It is just rendering the styles but no inner html

**Expected behavior:**
I can redefine the custom element output to another tag name

**Steps to reproduce:**
- Build one component library with the custom elements bundle
- Import it in another project as custom element constructor
- Define on the custom elements registry with another tag than in the original component decorator

**Comment by splitinfinities** [comment] 2021-12-02 23:57
Duplicate of https://github.com/ionic-team/stencil/issues/3138

**Closed by splitinfinities** 2021-12-02 23:57 UTC
Labels: triage
