### ISSUE TITLE
bug: slotted contents not always ending up in Accessibility Tree

### ISSUE THREAD

**Issue by tomherni** [ionic-team/stencil#5077] opened 2023-11-16 15:41 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7.2

### Current Behavior

In specific cases, slotted contents do not end up in the Accessibility Tree anymore. We first started getting reports from users on the latest iOS. But now it can also be reproduced on macOS. Possibly other platforms are affected as well.

_In this bug report I will focus on a single, specific scenario that can be reproduced consistently. Although the issue is likely not limited to this scenario._

When I have a Stencil component that renders a `<button>`, and the button contains a `<slot>` and another Stencil component (e.g. an icon), then the slotted text does not end up in the Accessibility Tree. This results in screen readers being unable to determine the label of the button. The button will simply be read as `button` instead of, for example, `Place order, button`.

The issue does not occur when using custom elements directly. Therefore, it appears to be an issue with Stencil.

### Expected Behavior

I expect the slotted text to end up as the button's "contents" in the Accessibility Tree, so that screen readers will read the label of the button.

### System Info

```shell
System: node 18.18.2
    Platform: darwin (23.1.0)
   CPU Model: Apple M2 Max (12 cpus)
    Compiler: /stencil-a11y-bug/node_modules/@stencil/core/compiler/stencil.js
       Build: 1699889895
     Stencil: 4.7.2 🐄
  TypeScript: 5.2.2
      Rollup: 2.42.3
      Parse5: 7.1.2
      Sizzle: 2.42.3
      Terser: 5.24.0
```

### Steps to Reproduce

Create 2 Stencil components:

```tsx
// stencil-button.tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'stencil-button',
  shadow: true,
})
export class StencilButton {
  render() {
    return (
      <button>
        <stencil-icon />
        <slot />
      </button>
    )
  }
}
```
```tsx
// stencil-icon.tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'stencil-icon',
  shadow: true,
})
export class StencilIcon {
  render() {
    return <span></span>
  }
}
```

Implement the button component so that it appears on screen:

```html
<stencil-button>Place order</stencil-button>
```

Using Chrome 119 Dev Tools on macOS 14.1, enter the "Accessibility Tree View" and inspect/highlight the `<button>`. In the "Accessibility" tab, the button will not have a name, and mentions for `Contents` the value `Not specified` (which should be "Place order").

VoiceOver will also read "button". This should be "Place order, button".

### Code Reproduction URL

https://github.com/tomherni/stencil-a11y-bug

### Additional Information

This issue has been happening since recent updates in either Chrome, or in macOS & iOS. I do not suspect it to be a Stencil regression.

I have currently identified 2 ways to bypass the issue. Hopefully this helps in finding a proper solution.

* Setting `invisiblePrehydration: false` in `stencil.config.ts`.
* Wrapping slotted text with an additional element. For example, a span: 

```html
<stencil-button><span>Place order</span></stencil-button>
```

**Comment by rwaskiewicz** [comment] 2023-11-16 19:27
Hey @tomherni 👋 

Thanks for the issue!

I did some testing on various browsers using your reproduction case (which was perfect in terms of size & complexity, thank you for that). 

I tested this with four versions of Chrome, and from what I can best tell, this is a regression in Chromium. Below is a screenshot comparing the behavior of Chrome v118.0.5993.70 (the most recent v118 release) for arm64 and 119.0.6045.159 for arm64 (latest at the time of this writing):
![Screenshot 2023-11-16 at 2 05 21 PM](https://github.com/ionic-team/stencil/assets/1930213/6516e935-4448-4e3e-886f-0766c15e6ecb)
 
There you can see in v118.0.5993.70 (top window), the `Contents` computed properties field received the text "Place order (Stencil)" and the button has a `StaticText` child in the Accessibility Tree field has the same value. In the bottom window (119.0.6045.159) `StaticText` is missing and `Contents` is 'Not Specified'.

I tested this in v116.0.5793.0 and saw the same behavior as v118.0.5993.70.
I also tested this in v119.0.5997.0 (the first v119 release that is publicly available) and saw the same behavior as v119.0.6045.159.

I also see the same behavior in MS Edge v119.0.2151.58, but _didn't_ see this in a previous version (I've truthfully forgot to grab the version number).

I'm going to close this out with the recommendation of opening an issue with the Chromium team. Please feel free to ask any questions you may have though!

**Closed by rwaskiewicz** 2023-11-16 19:27 UTC
Labels: triage

**Comment by tomherni** [comment] 2023-11-17 10:35
Hi @rwaskiewicz 

Thanks for your fast reply!

Isn't this _first_ a Stencil issue until we find the root cause?

Currently, Stencil is making my buttons inaccessible in production. I can only replicate the issue with Stencil components; custom elements and other libraries (Lit) seem unaffected. If I bring my Stencil reproduction code to the Chromium team, they will surely send me back to you to find the root cause first.

What if the root cause is a browser behavior that is here to stay? And what if it rolls out to other browsers? Even if this is ultimately a Chromium regression, it now makes Stencil's (pre)hydration bugged in major browsers. And considering my product's accessibility is compromised, I would appreciate your team's help to find out _why_.

**Comment by danivn** [comment] 2023-11-17 12:21
Hello! We've noticed this same bug as well in our Button component (which is basically a shadow component `<button><slot/></button>` with styles on top) although with JAWS 2023 and NVDA 2023. If it helps, for reference, we are using STENCIL v2.17.4.  though but we have the same issue as reported since the Accessibility Tree doesn't always picks up the slotted content.

**Comment by rwaskiewicz** [comment] 2023-11-20 21:32
👋 Hey folks,

I was able to reproduce this with vanilla web components and have opened an issue with the Chromium team - https://bugs.chromium.org/p/chromium/issues/detail?id=1503977
