### ISSUE TITLE
@PropDidChange @PropWillChange not called

### ISSUE THREAD

**Issue by riovir** [ionic-team/stencil#287] opened 2017-11-08 20:24 UTC
**Stencil version:**

```
 @stencil/core@0.0.7
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Methods decorated with ```PropWillChange``` and ```PropDidChange``` don't get called on updating the prop in the DOM.

**Expected behavior:**
When I edit the attribute of a Stencil element, I expect that the a handler function will fire as explained in the docs.

**Steps to reproduce:**
1. Clone the stencil-app-starter and then add the decorators to ```/src/components/my-name/my-name.tsx```
2. ```npm start``` the app
3. In the browser using inspect element, change the ```first``` attribute
4. Notice how there is nothing logged to the console

**Related code:**

```tsx
import { Component, Prop, PropDidChange, PropWillChange } from '@stencil/core';

@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss'
})
export class MyName {

  @Prop() first: string;

  @PropWillChange('first')
  willChangeHandler(newValue: string) {
   console.log('This will be the new first', newValue);
 }

 @PropDidChange('first')
 didChangeHandler(newValue: string) {
   console.log('This is the new first', newValue);
 }

  render() {
    return (<div>Hello, my name is {this.first}</div>);
  }
}
```

**Other information:**
This report seems to be a duplicate of #167.

**Comment by riovir** [comment] 2017-11-08 20:32
The bug first appeared in 0.0.7-2. 0.0.7-1 was working just fine.

**Comment by riovir** [comment] 2017-11-08 20:39
The last working version was 0.0.7-0.

**Comment by nowzig** [comment] 2017-11-09 10:00
I can confirm this problem.

**Comment by adamdbradley** [comment] 2017-11-15 15:03
Should be fixed since this commit, thanks: https://github.com/ionic-team/stencil/commit/fbdc6f1873261f1105a5006e71414108cb2594fc

**Closed by adamdbradley** 2017-11-15 15:03 UTC
