### ISSUE TITLE
exclude from tsconfig.json is potentially ignored

### ISSUE THREAD

**Issue by kirkhoff** [ionic-team/stencil#434] opened 2018-01-19 23:45 UTC
**Stencil version:**

```
 @stencil/core@0.1.6
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

After including a module which depends on `@types/react/index.d.ts`, the stencil build fails due to something found in the `node_modules` directory, even though `node_modules` is excluded in tsconfig.json.

![image](https://user-images.githubusercontent.com/1478680/35176566-ed85dea2-fd47-11e7-8f1a-61a84f484dd8.png)

**Expected behavior:**

Including another dependency should not cause the build to fail.
More importantly, the build should not fail due to a file that is excluded in tsconfig.json.

**Steps to reproduce:**

1. `git clone https://github.com/ionic-team/stencil-component-starter`
2. `cd stencil-component-starter`
3. `npm i @storybook/polymer --save-dev`
4. `npm run build`
5. Voila...errors!

**Related code:**
I pushed up my branch and put up a pr here to show the diff: https://github.com/kirkhoff/stencil-component-starter/pull/1

the tsconfig:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "moduleResolution": "node",
    "module": "es2015",
    "target": "es2015",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h"
  },
  "include": [
    "src",
    "types/jsx.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Other information:**

**Comment by manucorporat** [comment] 2018-01-20 00:51
I also experiment this problem too frequently. In my case:

My workaround:
```
rm -rf node_modules
npm i
```

**Comment by jgw96** [comment] 2018-01-23 21:02
@jthoms1 do we read the users stencil-config yet?

**Comment by adamdbradley** [comment] 2018-01-24 02:03
Looks like the issue is a duplicate of: https://github.com/ionic-team/stencil/issues/338#issuecomment-353988038

We'll get it fixed up, thanks for submitting the issue

**Closed by adamdbradley** 2018-01-24 02:03 UTC
Labels: needs info
