### ISSUE TITLE
feat: preserve jsdoc comments on class

### ISSUE THREAD

**Issue by ysulyma** [ionic-team/stencil#3798] opened 2022-11-07 00:50 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

JSDoc comments on classes (rather than on their props) are not included in `components.d.ts`. I would like them to be. I will submit a PR for this.

### Describe the Use Case

More information in type annotations.

### Related Code

The following code
```ts
/**
 * Example component
 */
@Component({
  tag: 'my-component',
  shadow: true,
})
export class MyComponent {
  /**
   * Example property
   */
  @Prop() prop: string;
}
```
produces the following `components.d.ts`:
```ts
interface MyComponent {
  /**
   * Example property
   */
  prop: string;
}
```
I would like it to produce
```ts
/**
 * Example component
 */
interface MyComponent {
  /**
   * Example property
   */
  prop: string;
}
```

**Comment by rwaskiewicz** [comment] 2022-11-08 15:25
Thanks @ysulyma!

I appreciate the PR! I'm going to close the issue (not the PR) as a duplicate of https://github.com/ionic-team/stencil/issues/3524. The team will be looking into the PR during our next sprint. Thanks again!

**Closed by rwaskiewicz** 2022-11-08 15:25 UTC
Labels: triage
