### ISSUE TITLE
Rehydration of prerendered page results in flashing of some components

### ISSUE THREAD

**Issue by realityfilter** [ionic-team/stencil#2245] opened 2020-03-06 14:16 UTC
**Stencil version:**
```
 @stencil/core@1.9.0-19
```

This affects also the current 1.8.x version of stencil.

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
We prerender our site and have noticed flashing of parts of the site during rehydration.
For instance all `stencil-route-link` components toggle their visibility because of the
hydrated class getting removed and added again. We tried the new feature of specifying a `hydratedFlag` of `null` but this leads to even more flashing. One promising workaround is to remove the `hydrated` class from the final prerendered html. No flashing. But the first initial paint is now slower because the site is now visible after all components are loaded and rehydrated.

**Expected behavior:**
No flashing of components because of their visibility change during rehydration.
At least it would be nice to have an option for the prerender step to remove the hydrated flag from the final html output.

**Comment by harrysolovay** [comment] 2020-04-09 02:36
I'm also having this issue.

**Comment by harrysolovay** [comment] 2020-04-16 19:05
@realityfilter I believe this issue is often caused by how the prerendered assets are served. If you're always serving the www/index.html, this is expected, as the first paint occurs before hydration, at which point the router/other dynamic components get to work. How are you serving your web pages? Are you by chance running a local `serve -s www`? That was the culprit in my case.

**Comment by realityfilter** [comment] 2020-06-25 09:20
Sorry for the late reply. The problem still exists with current stencil version 1.15.0.

@harrysolovay I checked the static site files the following way:

- stencil build --perender
- all pages are assets are now available in www folder
- serving via
    - docker run --rm -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
    - python -m SimpleHTTPServer

So the correct html file for that specific page gets served and no fallback root index.html.

The flickering is even visible when reloading the dev server.

**Comment by eriklharper** [comment] 2020-09-15 18:35
I'm also having this issue and I'm running the latest stencil `2.0.3`.  I'm using the `hydratedFlag` config option and I see a flash of default styling.  We're using this config option so that when our components are used, the consuming apps can set `className`s on our elements without conflicting with the `hydrated` class.

**Comment by paulcpederson** [comment] 2020-09-16 16:48
Currently, the visibility hidden functionality works with either a class or an attribute. This is configured via the `hydratedFlag` stencil config option. Either way, Stencil generates a set of styles for you and adds them to a `<style>` tag in the head of the document. Until this style tag is added, the content will be visible. So there will be a flash of content.

If possible, a great enhancement to stencil would be the ability to configure stencil to put these styles _in your global CSS file_. This would enable you to hide things prior to all the javascript running. 

As for the content in the style tag, it would be much better to use a `:not` selector here so that you're not fighting these rules for components that should be hidden even when hydrated (ie. modals, tooltips, dropdown menus). Here is a proposed API + CSS set:


```js
hydratedFlag: {
  selector: "attribute",
  name: "hydrated",
  property: "visibility",
  initialValue: "hidden",
  hydratedValue: "inherit",
  output: "inline" | "global"  // this is the new option that allows configuring where hydrated CSS lands
},
```

New option `"global"` would let devs add these styles to the configured `globalStyle` file. This file would then receive the following CSS:

```css
component-1:not([hydrated]), component-2:not([hydrated]) {
  visibility: hidden
}
```

**Comment by antongavrilenkov** [comment] 2020-10-26 21:41
My solution based on @realityfilter workaround to remove "hydrated" class from "html" tag:
prerender.config.ts
`
import { PrerenderConfig } from '@stencil/core';

export const config: PrerenderConfig = { 
  afterHydrate(document, url) { 
    document.getElementsByTagName('html')[0].classList.remove('hydrated'); 
  } 
};
`

**Comment by driskull** [comment] 2020-12-07 21:56
Although the [above solution](https://github.com/ionic-team/stencil/issues/2245#issuecomment-716839669) works. Its not very elegant to have to remove the class or attribute after it's already been added to the node. Some components could be visible until that code has been executed.

It would be much more preferable if a component were able to not be automatically hydrated in the first place.

Currently, every component is expected to have `visibility: visible` by default. We have some components (alerts, tooltips, modals) that should not be visible by default.

**Comment by splitinfinities** [comment] 2021-08-11 15:31
Hey there, thank you for the patience getting back to you. The new team is getting started and we're working through the backlog now.

This should be addressed by PR https://github.com/ionic-team/stencil/pull/2989 once merged, allowing you to opt-out of the injected prehydrated style tag.

**Comment by rwaskiewicz** [comment] 2021-09-01 19:26
The fix for this issue has landed in the main codebase and is a part of the Stencil v2.8 release. Thanks for you patience!

**Closed by rwaskiewicz** 2021-09-01 19:26 UTC
Labels: Feature: CSS, Feature: Compiler, Feature: Prerendering/SSG, Repro: Yes
