### ISSUE TITLE
Unexpected token export on Firebase after Stencil core update

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/stencil#736] opened 2018-04-16 10:41 UTC
**Stencil version:**
stencil/core@0.7.24

**I'm submitting a:**
[X ] bug report

**Current behavior:**
After update of the stencil/core, when I deploy the project to Firebase, I get the following exception in the console while accessing the website

    Uncaught (in promise) SyntaxError: Unexpected token export
        at Object.<anonymous> (workbox-core.prod.js:1)
        at Generator.next (<anonymous>)
        at n (workbox-core.prod.js:1)
        at workbox-core.prod.js:1

**Expected behavior:**
No javascript error

**Steps to reproduce:**

Website:

    https://web-photo-filter.firebaseapp.com/
    Open Chrome debugger console

How I build/deployed it:

    git clone https://github.com/peterpeterparker/web-photo-filter
    npm run build
    firebase deploy    

p.s.: same error if I build it with `--es5` as parameter

p.p.s.: I'm building a new lib and noticed that I face the exact same problem there too

**Related code:**

https://github.com/peterpeterparker/web-photo-filter

**Other information:**
Didn't noticed if with prior v0.7.x version I was facing the problem but I wasn't definitely facing that problem with v0.6.18

**Comment by jgw96** [comment] 2018-04-16 15:31
Hello, thanks for opening an issue with us! I am going to close this issue as a duplicate of https://github.com/ionic-team/ionic-pwa-toolkit/issues/54

**Closed by jgw96** 2018-04-16 15:31 UTC
Labels: triage

**Comment by peterpeterparker** [comment] 2018-04-16 15:58
@jgw96 thx for the feedback
