### ISSUE TITLE
One word attributes are not picked up

### ISSUE THREAD

**Issue by scarhand** [ionic-team/stencil#2824] opened 2021-02-12 09:10 UTC
**Stencil version:**

```
@stencil/core@2.4.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using the `attribute` option in PropOptions to override a property name with a one word attribute, as shown in the [docs](https://stenciljs.com/docs/properties#attribute-name), a compile error is shown.

Example component:
```tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'st-foo',
  shadow: true
})
export class Foo {
  @Prop({ attribute: 'valid' }) isValid: boolean;

  render() {
    return this.isValid ? "true" :  "false";
  }
}
```

When used as `<st-foo valid />` results in:

```
[16:16.3]  @stencil/core
[16:16.5]  v2.4.0 📷
[16:18.0]  build, app, dev mode, started ...
[16:18.0]  transpile started ...
[16:19.1]  transpile finished in 1.12 s

[ ERROR ]  TypeScript: ./src/components/app-home/app-home.tsx:17:19
           Type '{ valid: true; }' is not assignable to type 'StFoo & HTMLAttributes<HTMLStFooElement>'.Property
           'valid' does not exist on type 'StFoo & HTMLAttributes<HTMLStFooElement>'.

     L16:  <p>
     L17:    <st-foo valid />
     L18:  </p>

[16:19.1]  build failed, watching for changes... in 1.13 s
```
In a similar vein,
```
@Prop({ attribute: 'thisisacustomname' }) forSomeKindOfProperty: string;
```
does not allow you to set `thisisacustomname` as an attribute. However,
```
@Prop({ attribute: 'this-is-a-custom-name' }) forSomeKindOfProperty: string;
```
runs just fine when setting `this-is-a-custom-name` as an attribute.

**Expected behavior:**

The way I interpret the docs, it should be possible to override property names, and use single word attributes. If there is a limitation that only prefixed/dashed properties are supported, the documentation should reflect that.

**Steps to reproduce:**

Example project: https://github.com/scarhand/st-attribute-test

**Comment by scarhand** [comment] 2021-02-19 09:09
I did some digging in the code, and I think I have found a way to make it work. I'm not familiar enough with the rest of the code  and/or compile process to determine if this has any other implications.

Proposed changes here: https://github.com/ionic-team/stencil/compare/master...scarhand:issue_2824, if this suffices I'd be happy to make a PR.

**Comment by splitinfinities** [comment] 2021-11-14 00:47
Hey there! This is by design, actually. A Property and an HTML Attribute are technically different and can have different names. I am working on documentation so I will note this for updates when I reach these pages.

**Comment by Incomming336** [comment] 2021-12-08 14:41
That's quite inconvenient. What would be the best practice then? Maybe like this?
`@Prop({ attribute: 'valid-' }) isValid: boolean;`

**Comment by tanner-reits** [comment] 2023-12-07 19:47
This no longer appears to be an issue with the latest version of Stencil (v4.8.1 at the time of this response). Going to close this out, but please open a new issue with a reproduction if this is still happening on the latest version. Thanks!

**Closed by tanner-reits** 2023-12-07 19:47 UTC
Labels: Resolution: Needs Investigation
