### ISSUE TITLE
bug: responding to #1707 - rollup context is not defined

### ISSUE THREAD

**Issue by DesignByOnyx** [ionic-team/stencil#3303] opened 2022-03-25 19:34 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

&gt;=1.0.2

### Current Behavior

Everything is described in the open/locked issue #1707 

### Expected Behavior

Everything is described in the open/locked issue  #1707 

### Steps to Reproduce

See the linked fork:  https://github.com/ionic-team/stencil-sass/compare/master...DesignByOnyx:rwheale/1707-rollup-context-bug?expand=1

To get you there quicker:
```bash
git clone https://github.com/DesignByOnyx/stencil-sass.git
cd stencil-sass
npm i
npm run build
npm test
```

### Code Reproduction URL

 https://github.com/ionic-team/stencil-sass/compare/master...DesignByOnyx:rwheale/1707-rollup-context-bug?expand=1

### Additional Information

This issue can be closed in favor of unlocking the referenced issue #1707.

**Comment by DesignByOnyx** [comment] 2022-03-25 19:39
NOTE: this is not a bug in `stencil-sass` - it's a bug in stencil core not providing the correct context to plugins. I'm simply using stencil-sass because it's a working plugin which exhibits the problem.

**Comment by rwaskiewicz** [comment] 2022-04-04 12:27
Thanks @DesignByOnyx, I've pulled down your repro and can verify this is erroring.  I've transferred the new information over to #1707, unlocked conversation on 1707, labeled it so that it doesn't get closed accidentally by our automation, and marked it to be looked at closer by the team.  I'm going to close this issue out as a duplicate of #1707, as there's more context there. Thanks so much!

**Closed by rwaskiewicz** 2022-04-04 12:27 UTC
Labels: triage
