### ISSUE TITLE
Typescript Build Issues When Combining With tw-in-js/twind

### ISSUE THREAD

**Issue by nrawji** [ionic-team/stencil#2798] opened 2021-01-13 14:47 UTC
**Stencil version:**

```
test-app@0.0.1 /Users/nrawji/Coveo/test-app
└── @stencil/core@2.3.0
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When importing `{tw} from 'twind'` in any file you get typescript errors on build. If you run `tsc` manually however no typescript errors are thrown so it does not appear to be a typescript issue (I also tried using [twind](https://github.com/tw-in-js/twind) in React and it worked fine). 

**Expected behavior:**

It should compile and build correctly without any typescript errors.

**Steps to reproduce:**

`npm i twind`
In any file `{tw} from 'twind'

**Related code:**
```
[12:00.6]  @stencil/core
[12:00.7]  v2.3.0 ⛵️
[12:01.8]  build, test-app, dev mode, started ...
[12:01.9]  transpile started ...
[12:01.9]  transpile finished in 6 ms

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:13:44
           Type expected.

     L12:  <Section extends keyof Theme>(section: Section): Record<string, ThemeSectionType<Theme[Section]>>;
     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:13:66
           ';' expected.

     L12:  <Section extends keyof Theme>(section: Section): Record<string, ThemeSectionType<Theme[Section]>>;
     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:13:67
           Declaration or statement expected.

     L12:  <Section extends keyof Theme>(section: Section): Record<string, ThemeSectionType<Theme[Section]>>;
     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:13:102
           '(' expected.

     L12:  <Section extends keyof Theme>(section: Section): Record<string, ThemeSectionType<Theme[Section]>>;
     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:13:113
           ')' expected.

     L12:  <Section extends keyof Theme>(section: Section): Record<string, ThemeSectionType<Theme[Section]>>;
     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:14:33
           '?' expected.

     L13:  <Section extends keyof Theme>(keypath: `${Section}.${string}`): ThemeSectionType<Theme[Section]> | undefined;
     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<The
     L15:  <Section extends keyof Theme>(section: Section, key: string | string[]): ThemeSectionType<Theme[Section]> | undefined;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:15:74
           An element access expression should take an argument.

     L14:  <Section extends keyof Theme>(keypath: `${Section}.${string}`, defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;
     L15:  extends keyof Theme>(section: Section, key: string | string[]): ThemeSectionType<Theme[Section]> | undefined;
     L16:  <Section extends keyof Theme>(section: Section, key: string | string[], defaultValue: NonNullable<ThemeSectionType<Theme[Section]>>): NonNullable<ThemeSectionType<Theme[Section]>>;

[ ERROR ]  TypeScript: ./node_modules/twind/twind.d.ts:253:25
           ']' expected.

    L252:  declare type CSSSimplePseudos = {
    L253:      [K in SimplePseudos as `&${string & K}`]?: CSSRules;
    L254:  };

[12:01.9]  build failed, watching for changes... in 16 ms

[12:01.9]  http://localhost:3333/
```
```tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';
import { tw } from 'twind'`;


@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
  ...
  render() {
    return <div class={tw`bg-blue`}>Hello, World! I'm {this.getText()}</div>;
  }
}
```

**Other information:**

https://github.com/tw-in-js/twind

**Comment by rwaskiewicz** [comment] 2022-12-01 16:51
Hello 👋 

I apologize that it took so long for someone on the team to take a look at this issue.

I created a new Stencil project with `npm init stencil component twind-test`, installed twind (`npm i twind`) and updated the default `my-component.ts` file like so:
```diff
@@ -1,6 +1,6 @@
 import { Component, Prop, h } from '@stencil/core';
 import { format } from '../../utils/utils';
-
+import {tw} from 'twind';
 @Component({
   tag: 'my-component',
   styleUrl: 'my-component.css',
@@ -27,6 +27,6 @@ export class MyComponent {
   }
 
   render() {
-    return <div>Hello, World! I'm {this.getText()}</div>;
+    return <div class={tw`bg-blue`}>Hello, World! I'm {this.getText()}</div>;
   }
 }
```
per the reproduction case. With the latest and greatest version of Stencil (v2.19.3) I'm unable to reproduce this issue with `stencil build`:
```
npm run build

> enum-test@0.0.1 build
> stencil build --docs

[49:36.5]  @stencil/core
[49:36.6]  v2.19.3 🌏
[49:37.5]  build, enum-test, prod mode, started ...
[49:37.5]  transpile started ...
[49:40.1]  transpile finished in 2.60 s
[49:40.1]  copy started ...
[49:40.2]  generate custom elements started ...
[49:40.2]  generate lazy started ...
[49:40.2]  copy finished (0 files) in 107 ms
[49:40.6]  generate custom elements finished in 405 ms
[49:41.0]  generate lazy finished in 823 ms
[49:41.0]  build finished in 3.46 s
```

As a result, I'm going to close this issue. Should it re-appear, please feel free to open a new issue.

Thanks!

**Closed by rwaskiewicz** 2022-12-01 16:51 UTC
Labels: triage
