### ISSUE TITLE
ShadowRoot functions not available in Jest

### ISSUE THREAD

**Issue by hartjus** [ionic-team/stencil#895] opened 2018-07-02 04:27 UTC
**Stencil version:**

```
 @stencil/core@0.9.7
```

**I'm submitting a:**

[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When writing a spec for a stencil component that uses shadow DOM, functions that are called off of the `shadowRoot` are not available in Jest (in addition, with no way to mock them).  When running the Jest spec, it results in the following error:

```
Error: Cannot read property 'getElementById' of undefined
    TypeError: Cannot read property 'getElementById' of undefined
```

**Expected behavior:**

When the component is rendered, in Jest, there should not be any errors with regards to using shadow DOM functions.

**Steps to reproduce:**

1.  Create component with `shadow: true`
2.  Import `Element` from '@stencil/core`
3.  In the `render()` function, make a call to a shadow DOM function: 
`const someElement = this.el.shadowRoot.getElementById('some-id');`
4.  Render in Jest spec:
```
element = await window.load({
                components: [SomeComponent],
                html: '<some-component></some-component>'
            });
```

**Comment by jthoms1** [comment] 2018-07-09 18:18
Duplicate of https://github.com/ionic-team/stencil/issues/381

**Closed** 2018-07-09 18:18 UTC
Labels: duplicate
