### ISSUE TITLE
SSG can't handle Dynamic import 

### ISSUE THREAD

**Issue by mahyar33** [ionic-team/stencil#2916] opened 2021-05-27 11:20 UTC
**Stencil version:**
```
 @stencil/core@2.0.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
when I'm using dynamic import I got an error with --prerender flag during build time.

**Expected behavior:**
it can build properly 

**Steps to reproduce:**
use some dynamic import codes like this:
```
import('@shoelace-style/shoelace/dist/components/button/button').then(module => {
  if (!customElements.get('sl-button')) customElements.define('sl-button', module.default);
});
```
then put this in package.json and run it:

`    "build": "stencil build --prerender --docs",`

**Comment by splitinfinities** [comment] 2021-09-07 18:20
Hey there, thank you for submitting this bug report. Could you help out by adding a reproduction repo? 

My instinct says this may be out of scope for our SSG, but worth investigating if there's community interest.

**Comment by tricki** [comment] 2021-09-07 18:50
You should always add the exact error message, it might help.

Dynamic imports are executed at runtime which means that file must be copied to the output folder ('e.g. `my-app/www/@shoelace-style/.../button`) and cannot be imported from node_modules.
Also, AFAIK you need to specify the full file name including the extension.

**Comment by rwaskiewicz** [comment] 2022-04-12 16:19
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!

**Comment by rwaskiewicz** [comment] 2022-04-18 13:10
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Stencil, please create a new issue and ensure the template is fully filled out.

Thank you for using Stencil!

**Closed by rwaskiewicz** 2022-04-18 13:10 UTC
Labels: ionitron: needs reproduction
