### ISSUE TITLE
Provide suport for HTML template literals in JavaScript (lit-html / Viperhtml)

### ISSUE THREAD

**Issue by ansarizafar** [ionic-team/stencil#357] opened 2017-12-11 07:49 UTC
There are many developers like me who don't like JSX. Please consider replacing JSX with lit-html https://github.com/PolymerLabs/lit-html or ViperHtml https://viperhtml.js.org/viper.html

**Comment by cary-smith** [comment] 2017-12-11 14:56
Given the option I think template literal frameworks will end up taking us away from as much DSL work and closer to pure JavaScript/HTML. Might even simplify DOM manipulations because the template can be directly modified instead of patching vdom for things like slots in non-shadow browsers.

**Comment by kylecordes** [comment] 2017-12-11 15:05
I have not closely followed lit and viper; so I don't know if they can achieve the following.

It's possible that the right template solution could move a bit more of the work to happen at compile/build time, and less of it to happen at run time. It could potentially achieve both smaller size and faster runtime performance than the VDOM solution (which is already quite decent).

**Comment by obedm503** [comment] 2017-12-11 17:25
the problem is that stencil already has it's own async rendering engine. it would be better if they separated the rending engine from the rest and people could choose lit or hyper, and default to the currently async rending. giving developers more freedom

**Comment by mg1075** [comment] 2017-12-20 00:26
related: https://github.com/ionic-team/stencil/issues/94

**Comment by jgw96** [comment] 2018-01-09 16:19
Hello! I am going to close this issue as a duplicate of #285 as that issue will also resolve this feature. Thanks for using Stencil!

**Closed by jgw96** 2018-01-09 16:19 UTC
Labels: feature request, post 1.0

**Comment by claytongulick** [comment] 2021-03-07 21:34
Do we have an example of using lit-html with stencil anywhere?

I currently use ionic in vanilla js with lit-html as renderer.

I'm considering whether I should switch from vanilla web components to stencil, but I'm not willing to move away from lit-html, since it's pretty much the best rendering technology I've seen so far (relies on native template, etc... instead of vdom/js solutions).
