### ISSUE TITLE
Support ShadowDom Polyfills (not just Scoped Fallback)

### ISSUE THREAD

**Issue by umdjm** [ionic-team/stencil#2012] opened 2019-11-15 12:44 UTC
**Stencil version:**
```
 @stencil/core@1.8.0
```

**I'm submitting a:**
[X] bug report
[X] feature request
[ ] support request 

**Current behavior:**
Using a stencil component with slots doesn't work correctly in React on IE11.   

The [fallback to scoped](https://stenciljs.com/docs/component#component-options) approach doesn't work for React because the light-dom elements are moved and React gets confused.

To demonstrate, I created https://umdjm.github.io/StencilFallbackDemo/, which is adapted from the [React in One Minute Demo](https://reactjs.org/docs/add-react-to-a-website.html#add-react-in-one-minute).

On IE11, when you click "Like" the Stencil component fails to render with the template:
![](https://raw.githubusercontent.com/umdjm/StencilFallbackDemo/master/www/assets/img/IE11_React_Screenshot.png)

On Chrome, when you click "Like" the Stencil component shows the slot as expected:
![](https://github.com/umdjm/StencilFallbackDemo/blob/master/www/assets/img/Chrome_React_Screenshot.png?raw=true)

FWIW, this repro worked fine when we created the same Web Component with [LitElement](https://lit-element.polymer-project.org/).

I think the right fix for this is to support using Shadow Dom polyfills instead of the [fallback to scoped](https://stenciljs.com/docs/component#component-options) approach.  

We tried to load the ShadowDom polyfills ourselves, but ran into issues with CSS selectors.  The scoped CSS rewrites don't happen when the polyfills exist.  Stencil should provide us with a way to enable ShadowDom polyfills correctly so that slots and CSS work well.

**Steps to reproduce:**
1) Create a [stencil component](https://github.com/umdjm/StencilFallbackDemo/blob/master/src/components/my-component/my-component.tsx) that has a slot
2) Fix the fact that IE11 doesn't call render when children change by adding a mutation observer - see https://github.com/ionic-team/stencil/issues/2004#issuecomment-552691394
3) Use that component in a [React App](https://github.com/umdjm/StencilFallbackDemo/blob/master/www/index.html) 

**Related code:**

Stencil Component:
```tsx
  render() {
    return <div>
      HEADER

      <br/>

      SLOT (
        <slot />
      )

      <br/>
      FOOTER
    </div>;
  }
```

React App:
```tsx
          <my-component>
            {this.state.liked
              ? <p>Button was clicked!</p>
              : "Click the button"
            }
          </my-component>
```

**Comment by schadenn** [comment] 2019-11-22 09:29
Opened #2031 with a quick fix to enable forcing shadow Dom in IE - tested it in our codebase together with @webcomponents/webcomponentsjs

**Comment by patrickalima98** [comment] 2019-11-23 19:16
The same problem here, I'm using the version 1.8.1, in my case, I'm make a library like Bootstrap, and all my componentes have this problem in the SSR in Firefox and Chrome.

**Comment by mkay581** [comment] 2020-01-09 02:46
FWIW, I definitely agree with @schadenn's comment in https://github.com/ionic-team/stencil/pull/2031#issuecomment-565384678.

Stencil should just remove the "scope fallback code" and just let consumers use webcomponentsjs  polyfills if needed. That would likely help with these issues.

**Comment by sschottler** [comment] 2020-02-02 16:45
There are three work-arounds that will render correctly:

1) wrap each conditional result in same tag type:

```jsx
              <my-component>
                {this.state.liked ? (
                  <p>Button was clicked!</p>
                ) : (
                  <p>Click the button</p>
                )}
              </my-component>
```

2) wrap the conditional expression in an extraneous tag like span or div (not ideal for semantic markup, but gets the job done):

```jsx
              <my-component>
                <div>
                  {this.state.liked ? (
                    <p>Button was clicked!</p>
                  ) : (
                    "Click the button"
                  )}
                </div>
              </my-component>
```

3) use `<React.Fragment>` (or the shorthand `<>…</>`) for simple cases with just string messages where you don’t want extraneous markup:

```jsx
              <my-component>
                {this.state.liked ? (
                  <React.Fragment>Button was clicked!</React.Fragment>
                ) : (
                  <React.Fragment>Click the button</React.Fragment>
                )}
              </my-component>
```

Basically anything that ensures the first child node that gets relocated to the slot remains the same type could work. I suspect the issue is because react's internal fiber tree probably has the relocated child node at different position then it ultimately ends up after slot relocation. Then after state change, reconciliation detects tag type change so react tries to remove child and append new child based on incorrect fiber model of committed dom structure. 

[This commit](https://github.com/ionic-team/stencil/commit/373fa6e099a183fbf42ab46112396d9733f025e7) addressed a bug with appendChild and stencil's light-dom slot logic. Not sure if that fix also addresses this issue and have not tested it myself yet.

Also, it seems stencil's slot relocation logic correctly renders surrounding template elements on initial render, but not on update, so maybe something in [connectedCallback](https://github.com/ionic-team/stencil/blob/228e38201390327dbb4198cfb0e53d6218415068/src/runtime/connected-callback.ts#L43-L54) or in the [relocateSlotContent](https://github.com/ionic-team/stencil/blob/9ac767b2ccf0915e025a250758831b75f2fc8506/src/runtime/vdom/vdom-render.ts#L626-L628) logic needs to be refreshed when children change.

**Comment by hypery2k** [comment] 2020-02-12 11:35
the same is happening in Angular when using `innerHTML` directive. But if you wrap it within one native dom element it's working
So this doesn't work in Edge/IE:

```
<my-comp [innerHTML]="data.html">
</my-comp>
```
But this does:


```
<my-comp>
   <div [innerHTML]="data.html"></div>
</my-comp>
```

**Comment by Sanderand** [comment] 2020-11-17 10:11
Is there an update on this issue?

**Comment by rwaskiewicz** [comment] 2023-09-06 19:55
Hey there 👋 

I apologize that it took so long for a member of the team to acknowledge this ticket. With Stencil v3, we've officially deprecated support for IE 11/older versions of Edge. At this time, we're not looking to add support for ShadowDom polyfills. As such, I'm going to close this out. Again, I apologize for the lack of response from the team here.

**Closed by rwaskiewicz** 2023-09-06 19:55 UTC
Labels: triage
