### ISSUE TITLE
Stencil worker bundling breaks CDN distribution

### ISSUE THREAD

**Issue by glenveegee** [ionic-team/stencil#2466] opened 2020-05-24 14:31 UTC
**Stencil version:**

```
 @stencil/core@1.13.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If I distribute a web component that utilises a web worker (as recommended in the stencil guides with a .worker.ts extension) then loading of the component over a CDN like `unpkg` (also suggested in the stencil guides) will fail with the following error:

assuming we have published an NPM package `my-component` then

```
DOMException: Failed to construct 'Worker': Script at 'https://unpkg.com/my-component/dist/my-component/p-afa954be.js' cannot be accessed from origin 'WHEREVER THE COMPONENT IS LOADED'

Uncaught (in promise) TypeError: Cannot read property 'isProxied' of undefined
```

**Expected behavior:**
Components that ship with web workers should load worker scripts correctly

**Steps to reproduce:**
1. Create a component that implements and calls a function in a `.worker.ts` file
2. Publish on NPM
3. Load component in a script tag from a CDN
4. View console for the error

**Related code:**
N / A

**Other information:**
### Github
I have created a demo project here: 
https://github.com/glenveegee/jmespath-tester

### NPM
I have published the component in NPM which you can use to test CDN here 
https://www.npmjs.com/package/jmespath-tester

### Integration
Loading the script over CDN would be done as follows:
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>WORKER DEMO</title>
  <script src="https://unpkg.com/jmespath-tester@develop/dist/jmespath-tester.js"></script>
</head>
<body>
  <jmespath-preview/>
</body>
</html>

```

The error trace as follows:

<img width="1108" alt="Screenshot 2020-05-24 at 15 28 49" src="https://user-images.githubusercontent.com/1570698/82756641-55b7f180-9dd3-11ea-98be-9a3c4145080a.png">

Extra notes: 

- The error appears whether I import a third party package or not.
- The error appears if the component is loaded over CDN in any page. This is **NOT** related to serving an HTML file in localhost

**Comment by manucorporat** [comment] 2020-05-26 15:58
Removing as it's a duplicate of https://github.com/ionic-team/stencil/issues/2438

**Closed by manucorporat** 2020-05-26 15:58 UTC
Labels: triage
