### ISSUE TITLE
bug: Stencil Hydrate | value.split is not a function when using <svg>

### ISSUE THREAD

**Issue by mayerraphael** [ionic-team/stencil#4278] opened 2023-04-18 13:09 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

Builds based on #2938 

### Current Behavior

If i add an `<svg>` to the jsx, Stencil hydrate adds a class to this element on server-side rendering.

Upon Hydration, Stencil tries to parse the classList of this element, but an error is thrown in `parseClassList` function:
https://github.com/ionic-team/stencil/blob/main/src/runtime/vdom/set-accessor.ts#L157

```
index-1d3c5472.js:3001 TypeError: value.split is not a function
    at parseClassList (index-1d3c5472.js:1780:56)
    at setAccessor (index-1d3c5472.js:1640:32)
    at updateElement (index-1d3c5472.js:1794:17)
    at patch (index-1d3c5472.js:2193:17)
    at updateChildren (index-1d3c5472.js:2002:13)
    at patch (index-1d3c5472.js:2199:13)
    at updateChildren (index-1d3c5472.js:2002:13)
    at patch (index-1d3c5472.js:2199:13)
    at updateChildren (index-1d3c5472.js:2002:13)
```

The problem seems that `element.className` returns an `SvgAnimatedString` for svg-Elements instead of an expected string.

![image](https://user-images.githubusercontent.com/25869389/232785855-741c5ed5-d128-4f4a-8b3c-08ec4920f41f.png)

In the `updateElement` method we see that `oldVNodeAttrs` holds the `SvgAnimatedString` instead of a normal string.
![image](https://user-images.githubusercontent.com/25869389/232786579-46c61aab-3a42-4b3e-8bee-51c222019707.png)

### Expected Behavior

Updating the class in Stencil Hydrate on svg Elements should work.

### System Info

```shell
Stencil 2.23.2, don't know if v3 is also affected.
```

### Steps to Reproduce

Add an `<svg>` element to a component. Use Stencil Hydrate and render the components server-side. Error occurs on client side hydration.

```jsx
render() {
   return <svg></svg>;
}
```
### Code Reproduction URL

Maybe later when i have time.

**Comment by alicewriteswrongs** [comment] 2023-04-19 18:29
Hey @mayerraphael thanks for filing this issue!

If you have time, would you mind adding a reproduction case? It really helps us to diagnose and fix bugs.

**Comment by mayerraphael** [comment] 2023-04-20 04:54
@alicewriteswrongs  I hope i find time till tomorrow. Thanks for taking your time looking into the issue.

**Comment by mayerraphael** [comment] 2023-08-11 06:09
@alicewriteswrongs This bug seems to be related to #2938 . Other people are reporting this error there too.

**Comment by alicewriteswrongs** [comment] 2023-08-11 16:46
Yeah this is definitely something I would like to fix, however I just tried
my hand at reproducing it and wasn’t able to (using Stencil 4.0.4). Would
you be able to put together a reproduction case? You can start with the
output of `npm init stencil` and then make the modifications you need to
reproduce the issue. If you then put it on GitHub as a separate repro we
can use it to diagnose the problem and fix the bug.

Without a reliable way to reproduce bugs it’s hard for us to know what to
fix!

**Comment by rwaskiewicz** [comment] 2023-08-14 14:28
👋 

FYI, I've removed the assignments/'bug: validated' labels from this issue. To echo @alicewriteswrongs  @mayerraphael if you could create a minimal repro case for us, we'd greatly appreciate it!

**Comment by mayerraphael** [comment] 2023-08-18 09:57
Cant reproduce the error in an isolated example (2.22.3 and NextJS 13.3). Will have to look on my part what may cause this. Weird, as i'm not the only one having this problem.

**Comment by mayerraphael** [comment] 2023-08-21 07:57
@rwaskiewicz @alicewriteswrongs I could reproduce it, finally!

This error seems to be related to #2938 because i only get the error message on  `@stencil/core@3.3.0-dev.1685496483.a311f36` or the johnjenkins community version.

But also with Stencil v3 or v4 it does not work correctly. No console error with value.split, but the SVG still has the SSR class attached, which should've been removed. At least it does not break the application here. I guess the error is only not emitted.

![image](https://github.com/ionic-team/stencil/assets/25869389/41e39ebf-bbc5-4646-a55d-025bd6fd7bf7)
    
**Here the reproduction repository**: https://github.com/mayerraphael/stencil-bug-playground

**Comment by alicewriteswrongs** [comment] 2023-09-14 17:21
Hey @mayerraphael, I just added a regression test for this issue in #4783. This should ensure that as we're fixing various slot-behavior-related issues in Stencil's runtime code we can't accidentally introduce the bug documented here into `main`. Since we now have that assurance I'm going to close this issue.

**Closed by alicewriteswrongs** 2023-09-14 17:21 UTC
Labels: Resolution: Refine
