### ISSUE TITLE
Testing shadow dom component

### ISSUE THREAD

**Issue by Tallyb** [ionic-team/stencil#311] opened 2017-11-16 13:31 UTC
**Stencil version:**
```
@stencil/core@0.0.8-0
```

**I'm submitting a:**

- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When trying to run tests on shadow dom component `shadow: true` - the element is rendered as null and cannot be tested. Even if the element is wrapped with a <div>. 

**Expected behavior:**
Return a testable element. 

**Steps to reproduce:**
on demo app, just add shadow: true to component and run tests jest. All specs under rendering suite will fail. 

**Related code:**

```tsx

import { Component, Prop } from '@stencil/core';
@Component({
  tag: 'my-name',
  styleUrl: 'my-name.scss',
  shadow: true // added this part
})
export class MyName {
  @Prop() first: string;
  @Prop() last: string;
  render() {
    return (
      <div>
        Hello, my name is {this.first} {this.last}
      </div>
    );
  }
}

testing code is from starter project: https://github.com/ionic-team/stencil-app-starter/blob/master/src/components/my-name/my-name.spec.ts
```

**Other information:**
```bash
TypeError: Cannot read property 'textContent' of null

      at Object.<anonymous> (src/components/my-name/my-name.spec.ts:69:28)
          at new Promise (<anonymous>)
          at <anonymous>
```

**Comment by dimi-nk** [comment] 2017-11-16 13:40
+1

**Comment by cary-smith** [comment] 2017-11-16 14:06
Related: https://github.com/ionic-team/stencil-component-starter/issues/37

**Comment by mattdsteele** [comment] 2017-11-16 19:06
This is just a guess, but I'm assuming this is due to JSDOM's lack of support for Shadow DOM: https://github.com/tmpvar/jsdom/issues/1030

One solution is to use skatejs/ssr, which patches UnDOM to make Jest work with Web Components: https://github.com/skatejs/ssr#running-in-jest

But going through those steps didn't seem to resolve this.

**Comment by jgw96** [comment] 2018-01-09 16:12
Hello! I am going to close this issue as a duplicate of https://github.com/ionic-team/stencil/issues/381 for now. Thanks for using Stencil!

**Closed by jgw96** 2018-01-09 16:12 UTC
Labels: bug
