### ISSUE TITLE
bug: Loss of ts type after packing

### ISSUE THREAD

**Issue by wabi-habi** [ionic-team/stencil#4596] opened 2023-07-20 04:45 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

^4.0.1

### Current Behavior

Example: The component has a `prop` parameter of `color`, which has a parameter type of `MyColor | string`.

```ts
type MyColor = 'red' | 'pink'
```

```jsx
@Prop() color: MyColor | string
```

But in the `readme.md` file generated by packaging, the type of `color` is left as `string`! So there is no ts prompt when using the component!

### Expected Behavior

The `MyColor` type should not be lost.

### Steps to Reproduce

```jsx
import { Component, Host, Prop, h } from '@stencil/core';

type MyColor = 'pink' | 'red'

@Component({
  tag: 'my-component',
})
export class MyConponent {
  /**
   * color
   */
  @Prop() color: MyColor | string;

  render() {
    return (
      <Host>
        <slot></slot>
      </Host>
    );
  }
}
```

### Code Reproduction URL

The above steps are a complete reproduction of the code

**Comment by rwaskiewicz** [comment] 2023-07-20 15:50
Hey @wabi-habi  👋 

I think there are a few separate things going on here:

1. > But in the readme.md file generated by packaging, the type of color is left as string!

This is a known issue, and is currently being tracked by https://github.com/ionic-team/stencil/issues/3603

2. > So there is no ts prompt when using the component!

Can you clarify which output target are you using to generated the README for us please? And which editor you're not seeing the prompts in?

**Comment by wabi-habi** [comment] 2023-07-21 03:11
> Hey @wabi-habi 👋
> 
> I think there are a few separate things going on here:
> 
> 1. > But in the readme.md file generated by packaging, the type of color is left as string!
> 
> This is a known issue, and is currently being tracked by #3603
> 
> 2. > So there is no ts prompt when using the component!
> 
> Can you clarify which output target are you using to generated the README for us please? And which editor you're not seeing the prompts in?

Hey there, I'm using the default packaging configuration, no changes, and the editor is `vscode`.

**Comment by rwaskiewicz** [comment] 2023-07-21 13:44
> Hey there, I'm using the default packaging configuration, no changes, and the editor is vscode.

Ah, I see.

For what it's worth, the default generated docs (README.md files) do not affect/play a role in type generation in any IDE. We do however, have a `docs-vscode` output target to help inform VS Code about custom elements that can be added to your `stencil.config.ts` to help with some intellisense in HTML files ([docs](https://stenciljs.com/docs/docs-vscode)).

However, without configuring this functionality, I am able to get Intellisense on the component in the reproduction case:

![Screenshot 2023-07-21 at 9 33 56 AM](https://github.com/ionic-team/stencil/assets/1930213/bbaed3f4-65f0-4dcc-aff7-86b2de6ffbf2)

This requires the dev server to be running _or_ a build of Stencil to have occurred in order for typings to be generated. Work related to removing this limitation is related to https://github.com/ionic-team/stencil/issues/3534.

Since this issue relates to an existing one, I'm going to close this out. Thanks!

**Closed by rwaskiewicz** 2023-07-21 13:44 UTC

**Comment by wabi-habi** [comment] 2023-07-21 15:10
> > Hey there, I'm using the default packaging configuration, no changes, and the editor is vscode.
> 
> Ah, I see.
> 
> For what it's worth, the default generated docs (README.md files) do not affect/play a role in type generation in any IDE. We do however, have a `docs-vscode` output target to help inform VS Code about custom elements that can be added to your `stencil.config.ts` to help with some intellisense in HTML files ([docs](https://stenciljs.com/docs/docs-vscode)).
> 
> However, without configuring this functionality, I am able to get Intellisense on the component in the reproduction case:
> 
> ![Screenshot 2023-07-21 at 9 33 56 AM](https://user-images.githubusercontent.com/1930213/255188498-bbaed3f4-65f0-4dcc-aff7-86b2de6ffbf2.png)
> 
> This requires the dev server to be running _or_ a build of Stencil to have occurred in order for typings to be generated. Work related to removing this limitation is related to #3534.
> 
> Since this issue relates to an existing one, I'm going to close this out. Thanks!

You misunderstood me, I meant that the d.ts file generated has only `string` in its type, which results in no hints for the color value.

**Comment by rwaskiewicz** [comment] 2023-07-21 15:24
> You misunderstood me, I meant that the d.ts file generated has only string in its type, which results in no hints for the color value.

That's a result of how TypeScript interprets `MyColor` in the `@Prop color`'s type. In the reproduction case, it's typed as:
```ts
type MyColor = 'red' | 'pink;
```
where `color` is typed as:
```ts
@Prop() color: MyColor | string
```

since 'red' and 'pink' are subtypes of `string`, TypeScript widens the types to `string`. 

We can observe this behavior outside of Stencil, in the TS Playground.

In the image below, I've typed out `MyColor` and a variable `color` (same thing we have in the Stencil example, just without Stencil). The type hints widen to `string` when I hover over `color`:
![Screenshot 2023-07-21 at 11 20 32 AM](https://github.com/ionic-team/stencil/assets/1930213/4b86a154-6aae-482d-b6ae-0c7a4897427e)

If I remove `string` from the typing of `color`, then it can be constrained to `'pink' | 'red'`:
![Screenshot 2023-07-21 at 11 21 03 AM](https://github.com/ionic-team/stencil/assets/1930213/3cd5806f-8709-45f2-b485-193ec36b2db8)

Here, Stencil is just following TypeScript's lead as to how these typings can be represented. Hope that makes sense!

**Comment by wabi-habi** [comment] 2023-07-21 16:18
> > You misunderstood me, I meant that the d.ts file generated has only string in its type, which results in no hints for the color value.
> 
> That's a result of how TypeScript interprets `MyColor` in the `@Prop color`'s type. In the reproduction case, it's typed as:
> 
> ```ts
> type MyColor = 'red' | 'pink';
> ```
> 
> where `color` is typed as:
> 
> ```ts
> @Prop() color: MyColor | string
> ```
> 
> since 'red' and 'pink' are subtypes of `string`, TypeScript widens the types to `string`.
> 
> We can observe this behavior outside of Stencil, in the TS Playground.
> 
> In the image below, I've typed out `MyColor` and a variable `color` (same thing we have in the Stencil example, just without Stencil). The type hints widen to `string` when I hover over `color`: ![Screenshot 2023-07-21 at 11 20 32 AM](https://user-images.githubusercontent.com/1930213/255215763-4b86a154-6aae-482d-b6ae-0c7a4897427e.png)
> 
> If I remove `string` from the typing of `color`, then it can be constrained to `'pink' | 'red'`: ![Screenshot 2023-07-21 at 11 21 03 AM](https://user-images.githubusercontent.com/1930213/255216002-3cd5806f-8709-45f2-b485-193ec36b2db8.png)
> 
> Here, Stencil is just following TypeScript's lead as to how these typings can be represented. Hope that makes sense!

Okay, thanks. I think I got it.
