### ISSUE TITLE
Importing another stencil component breaks unit tests

### ISSUE THREAD

**Issue by javo2222** [ionic-team/stencil#1883] opened 2019-09-23 12:18 UTC
**Stencil version:**

```
 @stencil/core@1.4.0
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

```js
import "@my-company/another-component";
```

With this line my unit test doesn't work. Locally everything is fine. I have a windows machine. But on Jenkins (Linux) the test throws the following error message:

```
14:02:00  lerna ERR! yarn run test stderr:
14:02:00  PASS src/utils/helper.spec.ts
14:02:00  FAIL src/components/my-component.spec.ts
14:02:00    ● Test suite failed to run
14:02:00  
14:02:00      Cannot find module '@my-company/another-component' from 'my-component.tsx'
14:02:00  
14:02:00      However, Jest was able to find:
14:02:00      	'./my-component.scss'
14:02:00      	'./my-component.spec.ts'
14:02:00      	'./my-component.tsx'
14:02:00  
14:02:00      You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'jsx', 'ts', 'tsx', 'mjs', 'json'].
14:02:00  
14:02:00      See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
14:02:00  
14:02:00         import { Component, Element, h, Listen, Prop, State } from "@stencil/core"; 
14:02:00      >  import { calcNumberOfViews, getOptimizedPerPage } from "../../utils/helper";
14:02:00         ^       
14:02:00         @Component({
14:02:00  
14:02:00        at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:230:17)
14:02:00        at Object.<anonymous> (src/components/my-component.tsx:4:1)
14:02:00  
14:02:00  Test Suites: 1 failed, 1 passed, 2 total
14:02:00  Tests:       16 passed, 16 total
14:02:00  Snapshots:   0 total
14:02:00  Time:        3.647s
14:02:00  Ran all test suites.
14:02:00  error Command failed with exit code 1.
```

package.json of "another-component"
```
{
  "name": "@my-company/another-component",
  "version": "1.0.6",
  "description": "desc",
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/types/index.d.ts",
  "collection": "dist/collection/collection-manifest.json",
  "collection:main": "dist/collection/index.js",
  "unpkg": "dist/another-component/another-component.js",
  "files": [
    "dist/"
  ],
  "scripts": {
    "build": "stencil build --es5  && stencil build --es5 ",
    "start": "stencil build --es5 --dev --watch --serve",
    "test": "stencil test --spec",
    "test.watch": "stencil test --spec --watchAll"
  },
  "devDependencies": {
    "@stencil/core": "^1.2.0",
    "@stencil/sass": "^1.0.1",
    "@types/jest": "24.0.15",
    "jest": "24.8.0",
    "jest-cli": "24.8.0",
    "workbox-build": "4.3.1"
  },
  "license": "MIT"
}
```

**Expected behavior:**

Tests work on windows and on linux machines.

**Steps to reproduce:**

Import another stencil component in a lerna monorepo in my-component and write a unit test spec file my-component.spec.ts. This test doesn't work on linux machines. 

**Related code:**

```tsx
import "@my-company/another-component";
```

**Other information:**

**Comment by viljamis** [comment] 2019-09-28 07:36
@javo2222 Where exactly do you have that import line? In your tests or inside one of the components you’re trying to test?

**Comment by bitflower** [comment] 2021-07-19 18:58
Related: https://github.com/ionic-team/stencil/issues/2221

**Comment by splitinfinities** [comment] 2021-08-10 20:04
Duplicate of #2648

If folks can share all their learnings in that issue, I would appreciate it.

**Closed by splitinfinities** 2021-08-10 20:04 UTC
Labels: triage
