### ISSUE TITLE
feat: remove support for puppeteer and move to playwright

### ISSUE THREAD

**Issue by klh** [ionic-team/stencil#3169] opened 2021-12-03 17:07 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

if you're still going for the kitchen sink approach for v3.
you might want to consider removing puppeteer and using playwright instead:

https://playwright.dev/docs/browsers/
better browser support and near 1:1 the same interface as puppeteer.

### Describe the Use Case

would just make sense to test in other things than chrome

### Describe Preferred Solution

remove puppeteer, use playwright intead

**Comment by rwaskiewicz** [comment] 2021-12-03 18:03
Thanks for this. I'm going to mark this as a duplicate of https://github.com/ionic-team/stencil/issues/2223, please feel free to upvote that issue

**Closed by rwaskiewicz** 2021-12-03 18:03 UTC
Labels: triage
