### ISSUE TITLE
stencil doesn't work in IE11 

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil#356] opened 2017-12-08 12:09 UTC
**Stencil version:**

```
 @stencil/core@8
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Page load errors out in app.js

![image](https://user-images.githubusercontent.com/1223799/33765252-34d489a8-dc18-11e7-883e-039023312d36.png)

although `components` is array, it looks like some polyfills are doing harm here, because Array.prototype.filter is in IE since ver 9

![image](https://user-images.githubusercontent.com/1223799/33765226-1fe91b44-dc18-11e7-89b8-38f506e9078b.png)

**Expected behavior:**
app works in IE11

**Steps to reproduce:**
stencil-app-starter

`npm run dev --es5`

**Comment by adamdbradley** [comment] 2017-12-08 14:31
ARG!! Thanks for the report, we'll fix that up quick

(sry, bonehead mistake, my bad)

**Comment by jgw96** [comment] 2017-12-08 14:47
Hey @Hotell ! I just cloned the stencil-app-starter, did a fresh npm install and I cannot reproduce the above issue on my Surface Book on IE11. So just to double check things, this is with your app running 0.0.8 of stencil/core correct? Is it just the vanilla app starter?

**Comment by jgw96** [comment] 2017-12-08 14:47
If it is, would you be able to zip it up and send it to me? Just want to find what the difference is that were seeing here.

**Comment by Hotell** [comment] 2017-12-08 15:19
yup it's latest raw stencil-app-starter with stencil 0.0.8
![image](https://user-images.githubusercontent.com/1223799/33772039-8c83b208-dc33-11e7-9ac1-59ad8587d392.png)

**Comment by jgw96** [comment] 2017-12-08 16:24
Hmmm, trying to figure out why i cant repro with the same exact setup. Could you zip that up and shoot it to me on slack? I cannot repro this at all

**Comment by Hotell** [comment] 2017-12-11 12:31
I guess I found the culprit. IE renders stencil apps in ie7 mode, some meta tags are missing probably. Still when I manually to ie11 mode, there is error within router and `Array.prototype.find`

![stencil-ie11-bug](https://user-images.githubusercontent.com/1223799/33831232-84900470-de77-11e7-8de3-8eb034ca883f.gif)

**Comment by Hotell** [comment] 2017-12-11 12:45
following fixes the issue:

`<meta http-equiv="x-ua-compatible" content="IE=Edge"/>`

![image](https://user-images.githubusercontent.com/1223799/33831745-94cb861e-de79-11e7-9cf0-7cd9ce3285a1.png)

I can submit PR if you want :)

cheers

**Comment by jgw96** [comment] 2017-12-11 17:08
Hey @Hotell (: A PR would be awesome, thanks for looking into this. Not sure at all why my IE seems to render in IE11 mode by default and yours is IE7. Also, the router issue in IE is a known issue with the site that will be fixed soon. The site is currently stuck on an older version of Stencil and the Stencil router because of a blocking issue. Unfortunately, the versions its stuck on do not work in IE but this will be fixed asap.

**Comment by ruudud** [comment] 2017-12-17 09:20
There's lots of reasons why IE can decide to use compatability mode, like group policies etc. The X-UA-Compatible meta tag at some point also needed to be the first meta tag appearing in `<head>` to take effect.. here's a rabbit hole, if you want to jump into it: https://msdn.microsoft.com/en-us/library/cc288325.aspx

**Closed** 2017-12-27 16:23 UTC
Labels: bug

**Comment by jgw96** [comment] 2017-12-27 16:27
Hello all! I just fixed this issue with the above commit. Thanks!
