### ISSUE TITLE
RxJS import breaks

### ISSUE THREAD

**Issue by pixelbucket-dev** [ionic-team/stencil#2576] opened 2020-07-16 10:09 UTC
**Stencil version:**

```
 @stencil/core@1.16.x
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Build output shows error:

`[ ERROR ]  Rollup: Missing Export
           'default' is not exported by ./node_modules/rxjs/_esm2015/index.js, imported by rxjs?commonjs-external 1:
           import rxjs from "rxjs"; export default rxjs; ^`

We're using RxJS 6.3.1. 

There are also lots of warning since the 1.16.0 release, example:

`[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'resize-observer-polyfill' is imported by
           ./node_modules/nano-shell-heatmap/dist/collection/components/nsh-heatmap/nsh-heatmap.js, but could not be
           resolved – treating it as an external dependency`

**Expected behavior:**
Clean terminal output, no errors, no warnings. This was the behaviour in v1.15.x.

Interestingly, the app still renders without issues, despite the RxJS error.

**Comment by glenveegee** [comment] 2020-07-16 14:00
Exactly the same thing happens to me when we try update our stencil components (which also have the rxjs dependency) to 1.16.x. The UNRESOLVED_IMPORT thing is also new and the builds break but it's not clear if the rxjs or the UNRESOLVED_IMPORT is the primary cause of failure

**Comment by chrisweight** [comment] 2020-07-16 14:57
Yep, we're getting a very similar issue here with RxJS, but also with `Event` imported from `@stencil/core` strangely.

**Comment by glenveegee** [comment] 2020-07-19 07:49
Stencil 1.16.4 fixed the unresolved imports for me

**Comment by denyo** [comment] 2020-07-20 14:21
Dupe of #2554

**Comment by pixelbucket-dev** [comment] 2020-07-20 15:06
@glenveegee is correct, fixed with 1.16.4. Can be closed. Thank you all 😃 .

**Closed** 2022-09-02 17:18 UTC
Labels: triage
