### ISSUE TITLE
Bug: docs-readme doesn't properly parse variables used as @Prop default values.

### ISSUE THREAD

**Issue by pr3tori4n** [ionic-team/stencil#1709] opened 2019-07-03 22:28 UTC
**Stencil version:**
```
@stencil/core@1.1.3
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When running a build that [auto-generates docs ](https://stenciljs.com/docs/docs-readme), the value added to the default value for a property adds the variable name as a string instead of parsing the variable and adding it's value.

**Expected behavior:**
Any variables referenced for @Prop() default values would be parsed and the value reflected accurately in the generated docs.

**Steps to reproduce:**
1. Add a variable to a component file `foo = 'bar'`.
2. Add a property with the @Prop() decorator `textMyString = foo;`
3. $npm run build
4. See readme.md generated file has incorrect default value `foo` for `textMyString`. Default value should be string `bar`.

**Related code:**

```tsx
const foo = "bar";

@Component({
  tag: "some-example",
  styleUrl: "some-example.scss",
  shadow: true
})
export class SomeExample {
  @Prop() someProp = true;
  @Prop() textMyString = foo;
   /*  other code */
}
```

```md
## Properties

| Property       | Attribute        | Description | Type      | Default |
| -------------- | ---------------- | ----------- | --------- | ------- |
| `someProp`     | `some-prop`      |             | `boolean` | `true`  |
| `textMyString` | `text-my-string` |             | `string`  | `foo`   |
```

**Comment by manucorporat** [comment] 2019-07-07 12:18
This is necesarity not the expected behaviour, ideally you want to expose the API, not the actual value.
- It can get really complicated to infer the actual value at compiler time.
- You don't want to expose the value:
```
@Prop() flags = fs.constants.SOMETHING;
```
Developer might want to document, ` fs.constants.SOMETHING`.

Closing as won't fix, since this is not necessarily the expected behavior, and we will need a full proposal covering all use cases, in addition, it's a hard problem from a technical point of view.

**Closed by manucorporat** 2019-07-07 12:18 UTC
Labels: triage
