### ISSUE TITLE
bug: Adding Storybook with Vite options fails

### ISSUE THREAD

**Issue by thebrandonlucas** [ionic-team/stencil#5654] opened 2024-04-12 03:32 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

4.7.0

### Current Behavior

When attempting to add and run storybook to [my StencilJS project](https://github.com/thebrandonlucas/bitcoin-qr) choosing the `web-components` -> `vite` options, I get the following error when running `storybook dev -p 6006` after the server starts up:
```
./sb-common-assets/fonts.css doesn't exist at build time, it will remain unchanged to be resolved at runtime
✓ 52 modules transformed.
x Build failed in 249ms
=> Failed to build the preview
RollupError: Could not resolve "../dist/esm/polyfills/index.js" from "loader/index.js"
file: ./loader/index.js
    at getRollupError (file://./node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file://./node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.handleInvalidResolvedId (file://./node_modules/rollup/dist/es/shared/node-entry.js:18925:24)
    at file://./node_modules/rollup/dist/es/shared/node-entry.js:18885:26
transforming (421) node_modules/lodash/_baseIteratee.js%                                                 
```

This is my stencil.config.ts file:
```
import { Config } from '@stencil/core';

export const config: Config = {
  namespace: 'bitcoin-qr',
  globalScript: 'src/global/app.ts',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
  testing: {
    browserHeadless: 'new',
  },
  sourceMap: false,
  extras: {
    enableImportInjection: true,
  },
};
```

I also receive the same error when trying to build with `storybook build`.  I confirmed that `../dist/esm/polyfills/index.js` does not exist, though I'm not sure why.

It's worth noting that to get to this error I had to first get past this error by manually running `yarn add --dev vite`. I'd assume the storybook command could handle this?:
```
=> Failed to build the preview
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from ./node_modules/@storybook/builder-vite/dist/index.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/cjs/loader:1261:33)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:21)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
```

### Expected Behavior

The storybook loads the dev server and can produce a build without error.

### System Info

```shell
System: node 20.11.1
    Platform: darwin (22.5.0)
   CPU Model: Apple M1 Pro (8 cpus)
    Compiler: /Users/user/bitcoin-qr/node_modules/@stencil/core/compiler/stencil.js
       Build: 1710782619
     Stencil: 4.13.0 🚞
  TypeScript: 5.4.2
      Rollup: 2.56.3
      Parse5: 7.1.2
      jQuery: 4.0.0-pre
      Terser: 5.29.2
```

### Steps to Reproduce

1. Clone [this repo](https://github.com/thebrandonlucas/bitcoin-qr).
2. Run `yarn`.
3. Run `npx stencil@latest init`
4. Run `yarn add --dev vite`
5. `Do you want to manually choose a Storybook project type to install? Y`
6. `Please choose a project type from the following list: web_components`
7. `We were not able to detect the right builder for your project. Please select one: Vite`

The server should start and you'll see the error. You can also see the error running `yarn build-storybook`.

### Code Reproduction URL

https://github.com/thebrandonlucas/bitcoin-qr

**Comment by tanner-reits** [comment] 2024-04-12 14:56
@thebrandonlucas Stencil does not currently officially support integrating with Storybook. There is an existing feature request for support [here](https://github.com/ionic-team/stencil/issues/2328). Closing this as a duplicate of that request, as this would likely be covered by that effort.

**Closed by tanner-reits** 2024-04-12 14:56 UTC
Labels: triage
