### ISSUE TITLE
interface IteratorResult

### ISSUE THREAD

**Issue by jafarlie** [ionic-team/stencil#2256] opened 2020-03-09 21:20 UTC
**Stencil version:**

```
 @stencil/core@1.8.8
```

**I'm submitting a:**

[+ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When I issue npm start command after npm init stencil, I run into an error "TypeScript Duplicate Identifier 'IteratorResult' "

**Expected behavior:**

Should be able to spin up the app and run it in localhost:3333
**Steps to reproduce:**

npm init stencil
npm start

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

Errors are in:
node_modules/typescript/lib/lib.es2015.iterable.d.ts
../../../node_modules/@types/node/index.d.ts

**Comment by joshuamorony** [comment] 2020-04-02 03:53
This was an issue I was facing, it only happened on my old laptop and I had no idea why. Turns out I had a global node_modules folder (at `~/node_modules`) that contained the `@types` folder listed in the error. Deleting the `@types` folder resolved this conflict.

**Comment by rwaskiewicz** [comment] 2022-12-01 16:21
Hello 👋 

I apologize it took so long for someone on the Stencil team to acknowledge this issue report.

I've attempted to reproduce this issue locally, but was unable to with the latest version of the `create-stencil` CLI (v3) and Stencil (v2.19.3). However, it's difficult to say if this is an issue with Stencil itself, the project the CLI was creating at the time, or the environment.  This comment:
> Errors are in:
> node_modules/typescript/lib/lib.es2015.iterable.d.ts
> ../../../node_modules/@types/node/index.d.ts 

makes me believe this has something to do with the directory structure of the project/environment. However, it's unclear if that's interacting weirdly with the reported version of Stencil or not.

Because I'm unable to reproduce this issue with the latest version of Stencil + the CLI, I'm going to close this issue. Please feel free to open a new issue should it reappear. Thanks again!

**Closed by rwaskiewicz** 2022-12-01 16:21 UTC
Labels: triage
