### ISSUE TITLE
stencil generate not working 1.8.8/1.8.9

### ISSUE THREAD

**Issue by peterennis** [ionic-team/stencil#2203] opened 2020-02-18 03:03 UTC
@adamdbradley 

**Stencil version:**

```
1.8.8
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Create stencil component using the starter and it drops the first
dash prefix

**Expected behavior:**

Prefix should be kept.

**Steps to reproduce:**

Use stencil-component-starter
Delete my-component
generate my-component

Sample results:

```
C:\ae\stencil-component-starter-test>npm run generate

> stencil-starter-project-name@0.0.1 generate C:\ae\stencil-component-starter-test
> stencil generate

√ Component tag name (dash-case): ... my-component
√ Which additional files do you want to generate? » Stylesheet, Spec Test, E2E Test

$ stencil generate my-component

The following files have been generated:
  - src\components\component\component.tsx
  - src\components\component\component.css
  - src\components\component\component.spec.ts
  - src\components\component\component.e2e.ts

C:\ae\stencil-component-starter-test>npm run generate

> stencil-starter-project-name@0.0.1 generate C:\ae\stencil-component-starter-test
> stencil generate

√ Component tag name (dash-case): ... my-dash-component
√ Which additional files do you want to generate? » Stylesheet, Spec Test, E2E Test

$ stencil generate my-dash-component

The following files have been generated:
  - src\components\dash-component\dash-component.tsx
  - src\components\dash-component\dash-component.css
  - src\components\dash-component\dash-component.spec.ts
  - src\components\dash-component\dash-component.e2e.ts

C:\ae\stencil-component-starter-test>npm run generate

> stencil-starter-project-name@0.0.1 generate C:\ae\stencil-component-starter-test
> stencil generate

√ Component tag name (dash-case): ... my-long-dash-component
√ Which additional files do you want to generate? » Stylesheet, Spec Test, E2E Test

$ stencil generate my-long-dash-component

The following files have been generated:
  - src\components\long-dash-component\long-dash-component.tsx
  - src\components\long-dash-component\long-dash-component.css
  - src\components\long-dash-component\long-dash-component.spec.ts
  - src\components\long-dash-component\long-dash-component.e2e.ts

C:\ae\stencil-component-starter-test>
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by peterennis** [comment] 2020-02-18 03:40
```
C:\ae\stencil-component-starter-test>npm run generate

> stencil-starter-project-name@0.0.1 generate C:\ae\stencil-component-starter-test
> stencil generate

√ Component tag name (dash-case): ... one-component
√ Which additional files do you want to generate? » Stylesheet, Spec Test, E2E Test

[ ERROR ]  EEXIST: file already exists, open
           'C:\ae\stencil-component-starter-test\src\components\component\component.tsx' Error: EEXIST: file already
           exists, open 'C:\ae\stencil-component-starter-test\src\components\component\component.tsx'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stencil-starter-project-name@0.0.1 generate: `stencil generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stencil-starter-project-name@0.0.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2020-02-18T03_36_44_108Z-debug.log

C:\ae\stencil-component-starter-test>
```

**NOTE:** The file does not exist and the error is due to the missing prefix.

```
C:\ae\stencil-component-starter-test>npm list @stencil/core
stencil-starter-project-name@0.0.1 C:\ae\stencil-component-starter-test
`-- @stencil/core@1.8.8
```

**Comment by peterennis** [comment] 2020-02-20 03:17
```
C:\ae\stencil-component-starter-test>npm list @stencil/core
stencil-starter-project-name@0.0.1 C:\ae\stencil-component-starter-test
`-- @stencil/core@1.8.9
```

```
C:\ae\stencil-component-starter-test>npm run generate

> stencil-starter-project-name@0.0.1 generate C:\ae\stencil-component-starter-test
> stencil generate

√ Component tag name (dash-case): ... one-component
√ Which additional files do you want to generate? » Stylesheet, Spec Test, E2E Test

[ ERROR ]  EEXIST: file already exists, open
           'C:\ae\stencil-component-starter-test\src\components\component\component.tsx' Error: EEXIST: file already
           exists, open 'C:\ae\stencil-component-starter-test\src\components\component\component.tsx'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stencil-starter-project-name@0.0.1 generate: `stencil generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stencil-starter-project-name@0.0.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2020-02-20T03_16_02_125Z-debug.log

C:\ae\stencil-component-starter-test>
```

**Comment by karthikrp** [comment] 2020-02-20 12:58
Duplicate of #2141

**Closed** 2022-12-01 16:09 UTC
Labels: triage
