### ISSUE TITLE
Error: connect ECONNREFUSED in e2e test

### ISSUE THREAD

**Issue by adiandroo** [ionic-team/stencil#3853] opened 2022-11-29 01:38 UTC
Hello, I'm having trouble on e2e test on GitHub CI run on production, it gives me this error
```
Failed: ErrorEvent {
  "error": [Error: connect ECONNREFUSED 127.0.0.1:39813],
  "message": "connect ECONNREFUSED 127.0.0.1:39813",
  "target": WebSocket {
    "_binaryType": "nodebuffer",
    "_bufferedAmount": 0,
    "_closeCode": 1006,
    "_closeFrameReceived": false,
    "_closeFrameSent": false,
    "_closeMessage": "",
    "_closeTimer": null,
    "_events": Object {
      "error": [Function onError],
      "open": [Function onOpen],
    },
    "_eventsCount": 2,
    "_extensions": Object {},
    "_isServer": false,
    "_maxListeners": undefined,
    "_protocol": "",
    "_readyState": 3,
    "_receiver": null,
    "_redirects": 0,
    "_req": null,
    "_sender": null,
    "_socket": null,
    "_url": "ws://127.0.0.1:39813/devtools/browser/a29532b7-3b31-46c2-add5-438c0b7b9e3e",
    Symbol(kCapture): false,
  },
  "type": "error",
}

  2 |
  3 | describe('comp paywall', () => {
> 4 |   it('renders', async () => {
    |   ^
  5 |     const page = await newE2EPage();
  6 |     await page.setContent('<comp-paywall></comp-paywall>');
  7 |

  at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
  at Suite.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:4:3)
  at Object.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:3:1)
```
My version on stencil is v2.5.2

My dependencies version
```
"devDependencies": {
"@stencil/postcss": "^2.0.0",
"@types/autoprefixer": "^10.2.0",
"@types/jest": "^26.0.23",
"@types/puppeteer": "^5.4.3",
"autoprefixer": "^10.2.5",
"axios": "^1.0.0",
"base-64": "^1.0.0",
"jest": "^26.6.3",
"jest-cli": "^26.6.3",
"postcss-nested": "^5.0.5",
"puppeteer": "^5.5.0",
"stencil-inline-svg": "^1.0.1",
"stencil-tailwind-plugin": "^0.5.0",
"tailwindcss": "^2.1.2",
"typescript": "^4.4.4"
}
```

The problem is in my local unit test is all is passed but in the production is give me this error on github CI run.

**Comment by rwaskiewicz** [comment] 2022-11-29 12:55
Hey @adiandroo, 

Can you please create a minimal reproduction case that demonstrates this issue? Unfortunately, there are too many variables here for the Stencil team to try to recreate the reported issue. Thanks!

**Comment by benelan** [comment] 2022-12-08 00:39
We also ran into this issue, and after investigating I found that GitHub just upgraded their Action runner's `ubuntu-latest` version to `v22.04`.
- [11/9 GitHub blog post](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/)
- [12/1 GitHub blog post](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/)

You can downgrade back to Ubuntu `v20.04`, which fixed the issue for me.

```diff
-   runs-on: ubuntu-latest
+   runs-on: ubuntu-20.04
```

This issue appears to be specific to Ubuntu `v22.04` and its derivatives. For example, I still get the error on my Pop_OS! `v22.04` machine (which is a lot harder to downgrade to `v20.04`). 

Although there is a workaround for GitHub Actions, it would still be great if we can figure out what's going so those of us with affected machines can run tests locally. 

I don't have the cycles right now, but I'll try to put together a minimal sample when I can. Until then, the issue can be reproduced with this (not minimal) repo: https://github.com/Esri/calcite-components

**Comment by rwaskiewicz** [comment] 2022-12-08 14:59
Thanks @benelan!

This is interesting that is occurs on Pop_OS 22.04 (locally). @adiandroo what OS are you running locally? I'd like to get a baseline as to what's working vs what's not.

I tried to create a [minimal reproduction case using `npm init stencil component`](https://github.com/rwaskiewicz/run-on-ubuntu-twenty-two) and [wired it up to GitHub Actions](https://github.com/rwaskiewicz/run-on-ubuntu-twenty-two/blob/main/.github/workflows/main.yml), using:
- Ubuntu 22.04
- The same versions of Node and NPM Calcite Components CI is using (I used [Volta](volta.sh) to achieve this, so I could switch versions easily if needed)

That didn't work, so I [tried to replicate ](https://github.com/rwaskiewicz/run-on-ubuntu-twenty-two/commit/0959466fb6fbeaeee02cf659773133dd641574e6)an [existing test in Calcite-Components](https://github.com/Esri/calcite-components/blob/master/src/components/tree/tree.e2e.ts#L9 that was failing). To no avail.

I'm going to get an Ubuntu 22 VM spun up locally to test my reproduction case, to see if that helps figure out what's going on here and/or what's missing from the repro

**Comment by rwaskiewicz** [comment] 2022-12-08 16:25
Update: I couldn't reproduce this locally with Ubuntu 22 and my reproduction case. @benelan if you have a minimal repro case/an area to point us to, that'd be much appreciated

**Comment by benelan** [comment] 2022-12-09 09:59
Thanks for spending some time looking into this. I wasn't able to repro locally with `stencil-app-starter` either, so there must be something else going on. We have our v1 release coming up in next month but I'll do some more digging and put together a minimal repro sample after that. At this point this is low priority for us since our prod CI is fix, thanks again!

**Comment by adiandroo** [comment] 2022-12-10 07:54
Hello @rwaskiewicz I'm sorry for late reply, my local OS is Windows 10 which is running normally, but it GitHub action it got error

**Comment by andysabtian** [comment] 2022-12-12 02:52
hi @adiandroo , I tried to replicate your issue, and found the same error

```
      3 | describe('comp-paywall', () => {
    > 4 |   it('renders', async () => {
        |   ^
      5 |     const page = await newE2EPage();
      6 |     await page.setContent('<comp-paywall></comp-paywall>');
      7 |

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
      at Suite.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:4:3)
      at Object.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:3:1)
```


so I tried changing the @stencil/core version to 2.20.0 it worked, but the unit test got error like this
```
[ ERROR ]  Protocol error (Target.setDiscoverTargets): Target closed. Error:
           Protocol error (Target.setDiscoverTargets): Target closed. at
           /home/runner/work/...
```
and I tried changing the puppeteer version to the latest 10.0.0 and now running normally

I don't know why with that version, but after I tried several versions, this is what makes it work

**Comment by rwaskiewicz** [comment] 2022-12-12 14:00
For anyone coming upon this issue (and if you're encountering it), some things you can provide to help the team diagnose this issue:

1. A minimal reproduction case - this would be ideal, although we aren't asking anyone to violate non-disclosure (or similar) agreements
2. The version of Stencil + Puppeteer your project is using
3. A list of any changes that were recently made to the project (if any)
4. Environment where E2E tests are failing - Operating System, Location (locally, in GitHub Actions, etc.)

Thanks!

**Comment by benelan** [comment] 2023-02-17 01:30
For anyone who comes across this issue, I'm using a Docker image to run the tests locally as a temporary work around. I still plan on investigating when I have a bit more time.

Here is a PR with the Dockerfile and associated npm scripts : https://github.com/Esri/calcite-components/pull/6491

You should be able to get it working in CI too if necessary. Although I haven't tried since GitHub Actions make it easy to switch OS versions.

**Comment by rwaskiewicz** [comment] 2023-08-10 13:41
Hey folks 👋 

It's been a while since this issue was opened. We have reason to believe that the Ubuntu 22 image that gets provided has been updated/improved over the last 8-10 months. Since we were never able to reproduce this, can someone who was/is do me a favor and see if this issue still persists? Thanks!

**Comment by rwaskiewicz** [comment] 2023-10-06 17:35
I'm going to close this due to lack of reproduction case. If this is still occurring, please feel free to open a new issue. Thanks!

**Closed by rwaskiewicz** 2023-10-06 17:35 UTC
Labels: ionitron: needs reproduction

**Comment by benelan** [comment] 2023-11-08 02:45
Sorry for the delay - we are in the process of migrating from Stencil v2 to v4 and I can confirm I no longer experience the issue locally (same machine as above) on `v4.7.0`. For what it's worth, I still get the error on Stencil v2, likely due to the outdated version of puppeteer (v10). I'd call it resolved on my end, thanks!
