### ISSUE TITLE
bug: SVGs won't load in leaflet context

### ISSUE THREAD

**Issue by RoboVij** [ionic-team/stencil#3231] opened 2022-02-03 13:35 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.13.0 and 2.11.0

### Current Behavior

I'm using a plugin `leaflet.fullscreen`. When I use it, the default icon (SVG) that comes bundled should be displayed automatically. But this and other SVGs aren't loading at all. I just import the plugin's css file which has the following class: 
```javascript
.fullscreen-icon { background-image: url(icon-fullscreen.svg); background-size:26px 52px; }
```
The file is imported properly because other classes are working fine.
I'm getting following error:
```javascript
GET http://localhost:3333/build/icon-fullscreen.svg 404 (Not Found)
```
The icon is not present in the build folder. But it exists in the plugin's node modules. This plugin works and icon shows up when I use it in a non-stencil project.

And in addition, the icon appears when I give a PNG with absolute url.
```javascript
.fullscreen-icon { background-image: url(https://img.icons8.com/external-sbts2018-mixed-sbts2018/58/000000/external-globe-social-media-sbts2018-mixed-sbts2018.png); background-size:26px 52px; }
```
But it doesn't work with the absolute path of SVG.
```javascript
.fullscreen-icon { background-image: url(https://github.com/brunob/leaflet.fullscreen/blob/master/icon-fullscreen.svg); background-size:26px 52px; }
```

### Expected Behavior

SVGs should be dispalyed.

### Steps to Reproduce

Refer Current Behavior section.

### Code Reproduction URL

https://github.com/RoboVij/stencil-svg-bug/tree/master

**Comment by rwaskiewicz** [comment] 2022-02-03 13:42
👋 

Hey @RoboVij! Thanks for the bug report. Would you be able to provide us with a minimal reproduction case in the form of a GitHub repo? It greatly helps the team diagnosing issues, as it gives us the ability to see the various configuration settings folks are using, the exact structure of their code, etc.  Thanks!

**Comment by RoboVij** [comment] 2022-02-03 15:04
Updated above

**Comment by rwaskiewicz** [comment] 2022-02-03 22:50
The reason this appears to be happening is that leaflet.fullscreen is requesting this SVG by performing the following steps:

1. [By creating a CSS class selector](https://github.com/brunob/leaflet.fullscreen/blob/d1f12fa4432bb2225979ff4051e65e647056b7d1/Control.FullScreen.css#L1) (`.fullscreen-icon`) that works similar to the example in the issue summary
2. The [class name is appended to a dynamically created string](https://github.com/brunob/leaflet.fullscreen/blob/d1f12fa4432bb2225979ff4051e65e647056b7d1/Control.FullScreen.js#L228) when the button is being added
3. The button is created/added to the leaflet map, which is causing the request to fire for the SVG. The `url` from Step 1 appears to be looking at the root of the `build` directory because the `url` value is relative to the root of the `leaflet.fullscreen` package.


With that being said, this is a difficult problem for Stencil to solve on its own. The compiled output (found in `www/build/app-home.entry.js`) will have a line in it looking something like:
```js
const controlFullScreenCss = ".fullscreen-icon{background-image:url(icon-fullscreen.svg);background-size:26px 52px}.fullscreen-icon.leaflet-fullscreen-on{background-position:0 -26px}.leaflet-touch .fullscreen-icon{background-position:2px 2px}.leaflet-touch .fullscreen-icon.leaflet-fullscreen-on{background-position:2px -24px}.leaflet-container:-webkit-full-screen{width:100% !important;height:100% !important;z-index:99999}.leaflet-container:-ms-fullscreen{width:100% !important;height:100% !important;z-index:99999}.leaflet-container:full-screen{width:100% !important;height:100% !important;z-index:99999}.leaflet-container:fullscreen{width:100% !important;height:100% !important;z-index:99999}.leaflet-pseudo-fullscreen{position:fixed !important;width:100% !important;height:100% !important;top:0px !important;left:0px !important;z-index:99999}";
```

where that first bit - `.fullscreen-icon{background-image:url(icon-fullscreen.svg)` shows the compiled output is pulling in the CSS from leaflet-fullscreen, but doesn't know it needs to update the URL (nor does it know that the SVG should be included)

We can test this out by modifying [this line](https://github.com/brunob/leaflet.fullscreen/blob/d1f12fa4432bb2225979ff4051e65e647056b7d1/Control.FullScreen.css#L1) in our `node_modules` directory and see that the URL changes when the page loads:
```diff
- .fullscreen-icon { background-image: url(icon-fullscreen.svg); background-size:26px 52px; }
+ .fullscreen-icon { background-image: url(hello/world/icon-fullscreen.svg); background-size:26px 52px; }
```
![Screen Shot 2022-02-03 at 5 38 20 PM](https://user-images.githubusercontent.com/1930213/152441006-18b7c047-e3cc-4185-9da7-17dfbd29c305.png)

to confirm our suspicions the changing the URL in the source package affects the output of `www/build/app-home.entry.js`.

I'm going to label this issue to get ingested for further investigation.

In the meantime, I would see if serving this asset up using the [`assets` field of the `@Component` decorator](https://stenciljs.com/docs/local-assets) (and may require copying the SVG into a separate directory and checked into source control)

**Comment by RoboVij** [comment] 2022-02-04 08:03
Thanks for inspecting.
Few more things. As I wrote, the same problem persists with absolute url SVGs, but not PNGs.

Second is, our stencil project is to create our own leaflet wrapper. In this stencil project we had been using our own styling library as a package, similar to fullscreen package. There are some zoom in/out buttons with SVG icons in this library. 

With stencil 2.11.0, when testing the stencil project the icons are showing up.

![Screenshot 2022-02-04 084202](https://user-images.githubusercontent.com/62998286/152491610-cd8a4abc-232e-476f-b7b5-af5490937c6f.png)

![Screenshot 2022-02-04 084749](https://user-images.githubusercontent.com/62998286/152491633-7d67ddae-ee63-4161-b7ec-fe42e4ddff69.png)

![Screenshot 2022-02-04 085421](https://user-images.githubusercontent.com/62998286/152492515-2e04afd4-4087-4c8d-b8ac-c972a2f624b7.png)


But after building this project and using it (the leaflet wrapper) in our main project, the icons aren't showing up in dev mode.

![Screenshot 2022-02-04 084507](https://user-images.githubusercontent.com/62998286/152491663-cc375882-4653-4192-958a-575553037b75.png)

![Screenshot 2022-02-04 084655](https://user-images.githubusercontent.com/62998286/152491675-df7630e6-d003-473a-9101-2a7da48065cd.png)

![Screenshot 2022-02-04 090228](https://user-images.githubusercontent.com/62998286/152493208-e3364f44-9bdf-4783-be82-94722c4309cf.png)


Where as, when we use it in a different main project, the icons show up in dev mode but not after deploying.

In some earlier versions (2.5.2) these icons are working fine everwhere - testing, dev mode, deploying.

![Screenshot 2022-02-04 090034](https://user-images.githubusercontent.com/62998286/152493068-077b074f-4232-4d87-ba3a-16ee4401fe91.png)

![Screenshot 2022-02-04 090103](https://user-images.githubusercontent.com/62998286/152493078-cbe29eda-ed17-4649-a3d8-d87cb4a30c64.png)


It's a strange problem. Unfortunately, I can't share any code for this. But it's the exact same problem as the fullscreen icon.

**Comment by RoboVij** [comment] 2022-02-11 07:52
@rwaskiewicz The SVG is loading when used in `assets` field. So it's a working solution for now, and working good enough while testing. But once I build the package and install it in my project, I'm suddenly getting the following errors in dev mode:
```javascript
Error: Module parse failed: Unexpected token (652:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| 	for (const methodList of methodMap) {
> 		const exitFullscreenMethod = methodList?.[1];
| 		if (exitFullscreenMethod in document) {
| 			for (const [index, method] of methodList.entries()) {
    at eval (uic-button_17.entry.js:1:7)
    at Object../node_modules/wrapper-project/dist/esm/uic-button_17.entry.js (27.js:10:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at Function.fn.t (app.js:195:35)
    at eval (eval at ./node_modules/wrapper-project/dist/esm lazy recursive ^\.\/.*\.entry\.js$ include: \.entry\.js$ exclude: \.system\.entry\.js$ (app.js:1006:1), <anonymous>:231:30)
    at async initializeComponent (index-2d509526.js?e80e:1436:1) undefined
```
Also:
```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isProxied')
    at initializeComponent (index-2d509526.js?e80e:1439:1)
```
I've seen that there's still an open issue #2774  about the isProxied error. Is it similar to that? If yes, is there still no fix?

**Comment by rwaskiewicz** [comment] 2022-02-11 13:46
@RoboVij could update your reproduction case? I can't guarantee any timelines on getting a chance to look at it, but if it's ready when we can/do get around to looking at this further, it'd be a huge help - thanks!

**Comment by christian-bromann** [comment] 2024-06-13 18:18
Hi @RoboVij  👋

We apologize for the delay in addressing this issue. The StencilJS team has been hard at work, and we appreciate your patience.

As StencilJS has undergone significant updates and improvements since this issue was originally posted, we believe that this specific concern may no longer be relevant with the latest version. Therefore, we are closing this issue.

If you are still experiencing this problem or have any new issues, please feel free to open a new issue with the latest details, and we will be happy to assist you.

Thank you for your understanding and support of StencilJS!

**Closed by christian-bromann** 2024-06-13 18:18 UTC
Labels: Awaiting Reply, Resolution: Needs Investigation
